### ISSUE TITLE
Akademy training not working

### ISSUE THREAD

**Issue by scorpion451** [BobPalmer/MKS#1005]
So after seeing a post confirming this as a bug and not an intention change, figured I'd log an issue.

For myself and some other people, the akademy does not have it's experienced-kerbals-train-inexperienced kerbals feature. I can level up crew with it- its just the signature feature that doesn't work. 

I currently have a level one scientist sitting with two level three scientists in an akademy solidly landed on Minimus as part of a large factory outpost  and no option to have them train him. One level 3 scientist was leveled up in a "grand tour" of the local system from Kerbin to Mun, Minimus, solar orbit and back, and the other was leveled up entirely in the field via a series of jaunts from and back to an orbital station with a pioneer module. 

As far as mods, I'm running the latest versions of:
* The USI Constellation
* Kerbal Engineer Redux
* Mechjeb2
* Extraplanetary Launchpads
* Indicator Lights
* KIS
* KAS
* Space-y lifters and lifters expanded
* Tweakscale
* All Y'all
* ScanSat
* DMagic Orbital Science
* Interstellar Fuel Switch
* HullCameraVDS ([the new version by its adopter linuxgurugamer](http://forum.kerbalspaceprogram.com/index.php?/topic/145633-12-hullcam-vds-continued/))
* Kerbal Alarm Clock
* Axial Aerospace cargo bays
* ModuleManager 2.7.3
I haven't had the training option since updating everything to 1.2, though, so if it's an interaction its a long-standing issue.

**Comment by BobPalmer** [comment]
Sorted in the next update
