### ISSUE TITLE
EnrichedUranium transfer -- critical to self-sufficiency

### ISSUE THREAD

**Issue by cbohrson** [BobPalmer/MKS#1007]
Maintenance will not move enriched uranium from nuclear reprocessing unit to reactors, and resource-transfer is unavailable.  EnrichedUranium generated from uraninite ends up stuck in the tundra module.

**Comment by zioperion** [comment]
I'm having the same issue. Enricheduranium will not transfer from any form of tank. My current mods are...

Umbra: MKS, KON, FTT, KER, MR, USI,SUR,KA, K+

Non-Umbra: TAC Life support, KIS, KAS, Extraplanetary Launchpads, and Mechjeb

**Comment by zioperion** [comment]
So I found the problem, it stems from the CommunityResourcePack folder, in file CommonResources.cfg

**The lines of code:**

RESOURCE_DEFINITION
{
	name = DepletedUranium // Depleted fuel to preserve mass when burned, can be recycled
	unitCost = 0
	density = 0.01097000000
	flowMode = NO_FLOW
	transfer = NONE
	isTweakable = true
    isVisible = true
	volume = 1
    ksparpicon = TriggerTech/KSPAlternateResourcePanel/Icons/DepletedUranium
}

RESOURCE_DEFINITION
{
	name = EnrichedUranium // Nuclear fuel
	density = 0.01097000000
	unitCost = 865.0000000
	isTweakable = true
    isVisible = true
	flowMode = NO_FLOW
	transfer = NONE
	volume = 1
    ksparpicon = TriggerTech/KSPAlternateResourcePanel/Icons/EnrichedUranium
}

**Should be changed to:**

RESOURCE_DEFINITION
{
	name = DepletedUranium // Depleted fuel to preserve mass when burned, can be recycled
	unitCost = 0
	density = 0.01097000000
	flowMode = ALL_VESSEL
	transfer = PUMP
	isTweakable = true
    isVisible = true
	volume = 1
    ksparpicon = TriggerTech/KSPAlternateResourcePanel/Icons/DepletedUranium
}

RESOURCE_DEFINITION
{
	name = EnrichedUranium // Nuclear fuel
	density = 0.01097000000
	unitCost = 865.0000000
	isTweakable = true
    isVisible = true
	flowMode = ALL_VESSEL
	transfer = PUMP
	volume = 1
    ksparpicon = TriggerTech/KSPAlternateResourcePanel/Icons/EnrichedUranium
}


This will fix the resource transfer of both enricheduranium and depleteduranium.

Sorry if this post is bad etiquette.. First time on here :)

**Comment by BobPalmer** [comment]
This is incorrect.  These are *BY DESIGN* not transferable.  You use the perform maintenance option to transfer them.

**Comment by BobPalmer** [comment]
Also.  Never change CRP - it affects other mods.

**Comment by cbohrson** [comment]
The issue I'm reporting is that maintenance doesn't transfer anything.

**Comment by zioperion** [comment]
As cbhorson said, the maintenance option doesn't work. In fact, there is no option to perform maintenance on the Tundra Power Distribution Unit, and performing maintenance on the Tundra Nuclear fuel plant it's connected to did nothing. This the first I have seen that's the new way to do it, since I am used to how it has been in the past. Hence why I tried to help fix it in the old method. I wont make the mistake of trying to help again.

**Comment by BobPalmer** [comment]
Right, still does not make that a bad patch (hence why I deleted it so someone would not accidentally copy it).  The text above did not say PDU.  And EVA / Right click for maintenance is how it has always been done.
