### ISSUE TITLE
EnrichedUranium not transferred through maintenance (right click or automated)

### ISSUE THREAD

**Issue by cbohrson** [BobPalmer/MKS#1010]
Not sure why the previous issue was closed, I can provide a savefile if that would help.

**Comment by Tuffey** [comment]
Just ran a test with the latest update and everything seems to be working when using a engineer to do the maintenance. I used a 2.5m reactor and had a waste container and fuel container.  I only had the fuel filled half way on the reactor. When I did the maintenance it drained the fuel container until the reactor was full.

I would recommend updating to the latest release and try the test again for yourself.

**Comment by cbohrson** [comment]
Can you confirm that this will move fuel from the tundra module that you would actually use to produce enriched uranium in-situ?  I.e., that enriched uranium in a tundra module will make its way into a PDU or reactor through maintenance and/or a waste and/or fuel container? That is mainly where I've encountered the problem.  Its always possible that I've been missing something, but I have been using the latest release.

**Comment by Tuffey** [comment]
(Currently running latest release that was release today)
I can confirm that I am unable to perform maintenance on the Tundra PDU. I can there seems to be no option for the maintenance, Unlike the 2.5m reactor or the Duna PDU. Both the 2.5m Reactor and Duna PDU allowed me to perform maintenance on them and would pull fuel from the fuel container.  

RoverDude could I be missing a step for the Tundra PDU. I have a waste container and fuel container. I only filled the PDU halfway in the hanger. I would start the PDU an time warp a few days, I would stop the reactor and then would take an engineer to the PDU and there would be no option for maintenance.

Hope this helps

**Comment by jd284** [comment]
The Tundra PDU is missing the USI_ModuleFieldRepair function, so it can have maintenance performed on it.
Until Roverdude fixes it, you can try the following MM patch:
```
@PART[Tundra_PDU]
{
        MODULE
        {
                name = USI_ModuleFieldRepair
        }
}
```

**Comment by BobPalmer** [comment]
Yep, the bit @jd284 noted is what the issue is.  I've fixed it in dev, but you can drop that in for now to sort the issue.
