### ISSUE TITLE
Agriculture modules stop producing when vessel is not actively viewed

### ISSUE THREAD

**Issue by GHRyanK** [BobPalmer/MKS#1034]
Agriculture modules appear to stop working when the vessel is not the one being actively viewed.  Supplies and timer go up, as expected, at a slow rate when capacity exceeds demand and vessel is actively viewed, but supplies and supply timer count down as if supplies are only being consumed and not produced while vessel is not the active one.  Recycler based supply consumption rate does not change (as expected) when switching between vessels.  I've tried this out with both Nom-O-Matics and Duna (CORRECTION: Ranger) Agriculture modules.  This may be another manifestation of MKS issue #1013.

Currently using KSP 1.2.1.1604 x64, USI-LS 0.5.6, MKS 0.50.7, and latest Karibou, Malemute, Survivability, and FTT packs.  I noticed this problem on previous version of USI-LS; no change after deleting all USI folders and re-installing with latest USI-LS.

**Comment by jd284** [comment]
What's your version of USITools (000_USITools folder)?

**Comment by GHRyanK** [comment]
My USITools.version file says 0.8.6.0; same as change log.  My SOP for MKS and LS updates is delete all USI folders, install LS first, then MKS, then remaining.  When there's a conflict, I check the box for keep all, with the assumption that a newer core LS or MKS takes precedence over the other part packs.

Also, quick correction to original post: I tried the Nom-O-Matics and Ranger Inflatable Ag module attached to a Duna Pioneer, not the Duna Ag module.

**Comment by GHRyanK** [comment]
Just updated to USI-LS 0.5.13.0, re-installed all USI mods (including MKS 0.50.7), and the problem still persists.  Additional detail: the ag module appears to produce when it is within camera range of the vessel currently being focused on, but still reverts to consumption-only when active vessel is not in proximity.

**Comment by GHRyanK** [comment]
I've deleted ALL KSP material and re-installed fresh with only KSP 1.2.2, USI-LS 0.5.13.0, and MKS 0.50.7.  With a new career game (with full tech tree cheated in), and no import of old save files, I put together a 3-crew command pod, Kerbitat in Hab Common mode, 3 radial recyclers, 3 large Nom-O-Matics, FTZ, SUP, mulch, and power then cheated it to orbit.  When focused on the test vessel, and all converters active, it creates supplies and consumes FTZ and mulch.  When focused on another vessel out of range, it consumes supplies instead of producing.

**Comment by GHRyanK** [comment]
Appears to be fixed in MKS 0.50.8
