### ISSUE TITLE
MKS 'Tundra' Habitation Ring in multiple tech tree locations

### ISSUE THREAD

**Issue by Baladain** [BobPalmer/MKS#1038]
My apologies if I'm posting this in the wrong place:
The hab ring is located in Advanced Construction and Colonization using CTT

**Comment by jd284** [comment]
Advanced Construction is the non-CTT tech node. Is it possible you've started the game without CTT and unlocked it there? Then you would see the unlocked part still in Advanced Construction and also the CTT node.

**Comment by Baladain** [comment]
I did start without CTT, I did not realize items would remain visible in the tree after CTT was added.
