### ISSUE TITLE
Ranger Agri Module (as {Greenhouse]) does not save state

### ISSUE THREAD

**Issue by Gilph** [BobPalmer/MKS#1046]
An uninflated Ranger AM used as an efficiency part and attached to a Tundra AM does not remain enabled after a scene change. If you start it, do any scene change and return, it is always stopped.

**Comment by jd284** [comment]
Should it even be doing anything uninflated? I think being able to start it at all while not inflated is the real bug here.

**Comment by Gilph** [comment]
Save for this issue is the same link for issue 1043:

[https://1drv.ms/f/s!AigvIEvgjetqvjxo_ayTvjaBNLkP](url)

Vessel is MinBase2Supplies

**Comment by BobPalmer** [comment]
Please test this in the next patch as I cannot repro this.
