### ISSUE TITLE
ASM / Ranger Crusher efficiency part too weak

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#1047]
The Ranger Crusher part set as efficiency part for the ASM (i.e. "[Crusher]" config), only increases the load by a few percent, it's almost negligible. It's even much less than the part would do on its own. To really be an efficiency part, the load increase for the ASM needs to be much higher.
 
See also [this forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/72032-12-usi-kolonization-systems-mksoks-0500/&do=findComment&comment=2888786).
Possibly related to #1043?

**Comment by BobPalmer** [comment]
By design
