### ISSUE TITLE
Klawing old med-bay instantly consumes supplies

### ISSUE THREAD

**Issue by Terwin1** [BobPalmer/MKS#1049]
[USI Test.zip](https://github.com/BobPalmer/MKS/files/656120/USI.Test.zip)

Reproduction steps using attached save file:
Mods: USI-LS, USI-MKS
* Resume USI.Test game from menu
* load quicksave
* sas aim at target
* Thrust forward at less then 1.0m/s to klaw med-bay  (starting at -0.1m/s relative speed at 15m distance)
* Just after klaw engages watch as supplies drop by 47 and mulch increases by 47

**Comment by BobPalmer** [comment]
Check and see if this is sorted in the next version
