### ISSUE TITLE
Add ModuleOverheatDisplay to MKS drills

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#1051]
Without this module it's impossible to tell if the drill has adequate cooling. Especially for the industrial strip miner, which also requires industrial cooling.

**Comment by dboi88** [comment]
Seconded, this has made troubleshooting bugs more difficult than it needed to be in the past. We've also had a number of bug reports that turned out to be down to under cooled drills.

**Comment by BobPalmer** [comment]
Next patch
