### ISSUE TITLE
Engineer bonus for drills doesn't work with disconnected bases

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#1052]
See also this [forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/72032-12-usi-kolonization-systems-mksoks-0500/&do=findComment&comment=2890489).

The engineer bonus for drill efficiency is only applied when the engineer is on the same vessel. It doesn't work when he's in a different MKS vessel less than 150 m away, then the drills only have 5% load, while they have e.g. 65% when a two-star engineer is one the same vessel.

**Comment by BobPalmer** [comment]
I may have mispoke on this one and that it should be vessel specific.  The area effect is only for things like couplers and logistics
