### ISSUE TITLE
CTT configuration for Manufacturing

### ISSUE THREAD

**Issue by kaa253** [BobPalmer/MKS#1053]
The Ranger Inflatable Workshop and the Tundra Assembly Plant appear on the same level (1000 science points) in the CTT tree. I suggest that Ranger workshop comes earlier in perhaps Meta-materials or Nanolathing (550 science level). Eg.

@PART[Ranger_Workshop]:NEEDS[CommunityTechTree]
{
	@TechRequired =  nanolathing
}

**Comment by BobPalmer** [comment]
Done
