### ISSUE TITLE
Ranger Heatpump shouldn't deactivate on minor jumps

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#1054]
Often a landed vessel will make brief jumps, e.g. while switching to it or after coming out of time warp.

This causes the situation to briefly change to "in space low" and the heatpump deactivates itself. So every time you have to manually reactivate it. That's very annoying.

It would be better if the heatpump just stopped pumping heat when not landed, instead of deactivating entirely.

It's fine if the error message is displayed as a warning, but please don't turn it off entirely. If you must turn it off, make sure the situation has actually persisted for some time, such as having no ground contact for several seconds or more. (One common solution for this sort of thing would be to count the physics frames with no ground contact, reset it to 0 when there is ground contact, and only deactivate when this counter has gotten too large.)

**Comment by BobPalmer** [comment]
Changed next patch
