### ISSUE TITLE
Add KIS volume to the Tundra Multi-hub

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#1061]
The part should contain mostly empty space, so it'd be nice if we could use that space to store items.

It's about 4/5ths of the large KIS container, which holds 18k liters. Compared to the Karibou multi-hub, which holds 5k liters, it's much larger.

So subtracting the room needed for the structural node connections, a reasonable volume might be 6000 - 8000 liters?

**Comment by BobPalmer** [comment]
Next patch
