### ISSUE TITLE
LightGlobe part is missing

### ISSUE THREAD

**Issue by fat-lobyte** [BobPalmer/MKS#1070]
Due to the large overhaul of 0.50, a lot of parts were removed. One of those parts was the LightGlobe, that looks like this:

![u8e6th6](https://cloud.githubusercontent.com/assets/173609/21595718/43c9f21a-d131-11e6-83d1-f2cc464483f3.png)

I can't really see any reason why it would be removed. Could it maybe be included in next release?

**Comment by MadMerlyn** [comment]
I grabbed it out of the old release and tested it. It seems to be working ok and has been merged in a pull request on an upcoming release.

**Comment by MadMerlyn** [comment]
It's back in 0.50.9 release.
