### ISSUE TITLE
Cannot inflate any module

### ISSUE THREAD

**Issue by tomforwood** [BobPalmer/MKS#1083]
I am attaching a save file from a clean install of 1.2.2 which has nothing but Kolonization and its required mods installed (installed using ckan). The quicksave attached has a vessel on the launchpad (craft file included)

[default.zip](https://github.com/BobPalmer/MKS/files/691384/default.zip)

Right clicking on the deployable modules on the craft doesn't offer the option to deploy them.

**Comment by dboi88** [comment]
You have warehouse disabled on the Kontainer. Engineers will only pull MaterialKits from warehouse enabled Kontainers. Modules Deploy as expected once warehouse was enabled.

![Expanded](http://i.imgur.com/KRNbJr0.jpg)

Recommend Close Issue

**Comment by tomforwood** [comment]
Ahh I see.
