### ISSUE TITLE
Karibou cab's landing legs are always extended at launch

### ISSUE THREAD

**Issue by Wyzard256** [BobPalmer/MKS#1094]
When launching a craft that has a Karibou cab, the cab's landing legs are initially extended on the launchpad/runway, even if they were retracted in the editor.  The legs on all the other Karibou parts behave correctly.

**Comment by Wyzard256** [comment]
Actually, the cab's legs re-extend when opening the craft from the tracking station, too.

**Comment by WuphonsReach** [comment]
I can replicate this on a vanilla install of KSP 1.2.2 with the Jan 4th USI constellation.

I've also seen it happen on the 10-kerbal passenger cabin, but can't get it to replicate in my MKS-only install.

**Comment by Wyzard256** [comment]
Fixed in 0.50.12.

**Comment by NaughtyGnosiophile** [comment]
I'm getting this behaviour in 0.50.18.0, but opposite.  The cab is fine, but now all the other modules are exhibiting the old cab behaviour.  The legs start deployed in the VAB, but the right-click menu says "deploy".  If you click on it, the legs will show the deployment animation again.  Now the right click menu says "Retract".  If you push it, it will then retract.  If you save the craft, then reload it or launch it, the legs will be deployed again.


[test.zip](https://github.com/BobPalmer/MKS/files/884485/test.zip)
