### ISSUE TITLE
Ranger mini-hab makes vessel jitter when extended

### ISSUE THREAD

**Issue by Wyzard256** [BobPalmer/MKS#1099]
I have a Karibou rover with a Ranger mini-hab attached, and when I deploy it, it jitters around and causes the whole rover to move.  It's on fairly flat ground, but the hab apparently clips into the ground a bit anyway.  Someone else reported a similar issue in the forum recently, so this may be a bug.

[Here's a save file.](https://github.com/BobPalmer/MKS/files/692780/jittery.hab.zip)  It's stock+MKS+USI-LS only — there were some other mod parts originally, but I disassembled them.

(For future reference, I'm using MKS v0.50.11 and USI-LS v0.5.16.)

**Comment by dboi88** [comment]
@Wyzard256 can you confirm if still present with the Pre2 release? https://www.dropbox.com/s/psurrvkcl0huvpw/MKS_PRE_2.zip?dl=0

**Comment by Wyzard256** [comment]
Hmm, I'd tried out that build earlier but somehow didn't notice the "ground tether" button.  At the time I'd noted that the jittering and movement was noticeably less, but testing again with the same build, I see that that was a fluke; without the tether enabled, sometimes I get lots of jitter when I load the rover and sometimes I don't.

Anyway, with the ground tether enabled:

* The hab still jitters around visually, but the rover doesn't move.  (KER shows a horizontal speed of 2 or 3 millimeters per second, which is negligible.)
* If I engage the tether while driving, the rover instantly stops.  Better than brakes!  Tested at 20m/s.
* I can take off with rockets while tethered.  When I come back down, the rover stops moving as soon as any part of it touches the ground — even if that's just one corner, with the rest still floating above the ground.  Then the rest of the rover *slowly* falls down until the whole thing is on the ground.

This solves the problem as far as I'm concerned; I don't mind some slight visual jitter of the hab dome as long as the vessel stays in place on the ground.  But I'd suggest disabling the tether automatically when the vessel takes off (to prevent the weirdness when it comes back down), and don't allow it to be engaged if the vessel is moving too fast (so it's not a cheaty emergency brake).

**Comment by Wyzard256** [comment]
One bug: if I activate the tether and then use an engineer to disassemble or detatch the hab, the rover remains tethered with no way to turn it off.

**Comment by Wyzard256** [comment]
Another bug in the pre2 release: inflatable parts don't receive aero shielding from payload fairings, so they produce drag during flight even while inside a fairing.  They do still receive shielding from cargo bays.  Version 0.50.11 is OK.

It seems to be a code bug, not directly related to the `USI_InertialDampener` module.  If I install MKS v0.50.11 and then overwrite `USITools.dll` with the version from the pre2 build, the problem occurs.  Switching back to the v0.50.11 `USITools.dll` fixes it.

Tested with the mini-hab, full-size inflatable hab, ISM, and agricultural module.

**Comment by Wyzard256** [comment]
Fixed in v0.50.12.  I opened BobPalmer/USI_Core#64 for the aero-shielding bug.
