### ISSUE TITLE
MKS 'Tundra' Power Distribution Unit doesn't distribute power

### ISSUE THREAD

**Issue by LouisCyfer** [BobPalmer/MKS#1106]
It seems the MKS 'Tundra' Power Distribution Unit misses a module called
> MODULE { name = ModulePowerDistributor }

(Duna_PDU has that tho!)

ty for your work!

**Comment by rspeed** [comment]
Just noticed this same problem. What's odd is that looking through the git log for Tundra_PDU.cfg, it never seems to have had that module in the first place!

**Comment by LouisCyfer** [comment]
well, whatever fits the idea of MKS .. I'm fine with either if it distributes and get the module added OR there should be a name change (because a car what doesn't have a motor can't drive)

**Comment by LouisCyfer** [comment]
current version includes that now WOOT! ty :)
