### ISSUE TITLE
Scout landing module's "weight transfer" ignores some parts

### ISSUE THREAD

**Issue by Wyzard256** [BobPalmer/MKS#1107]
The Scout landing module's "weight transfer" feature seems to ignore some parts; it doesn't account for their mass and therefore doesn't position the craft's CoM correctly when they're present.

Steps to reproduce:
* In the VAB, place a Scout as the root part of a new craft, and enable weight transfer on it.
* Turn on the VAB's CoM display marker.
* Place a Ranger airlock on one side of the Scout.  Note that the CoM marker moves off-center when the airlock is snapped to the attachment mode but not yet placed, and it returns to center when you click to place the part.  Toggle the Scout's weight transfer on and off, and the CoM moves back and forth.
* Repeat with a Ranger comm-lab, inflatable storage module, mini-hab, or the Scout-200 plutonium power source.  Weight transfer works correctly for these parts too.
* Now place a Mk-V Supply Redi-Pak on the Scout instead.  The CoM marker does *not* return to center when you place the part, and toggling the Scout's weight transfer does not move the CoM.
* Repeat with a MK-V Saddle Tank, and Ranger ball hub, and (just for variety) stock FL-T100 fuel tank.  Weight transfer doesn't work for those either.

**Comment by dboi88** [comment]
I've added a PR with the required changes.

**Comment by Wyzard256** [comment]
Thanks.  Just to have them linked here for future reference: the changes are in #1108 and #1109.

(BTW, you can still push more changes to a branch after you've submitted a pull request for it; you don't have to create another branch with another PR to make a followup fix.)

**Comment by dboi88** [comment]
I assumed so but I couldn't work out how.

**Comment by Wyzard256** [comment]
@dboi88, just commit more changes to your branch and then do another push.  The additional changes should automatically become part of the pull request (unless it's already been merged & closed.)

**Comment by Wyzard256** [comment]
And a related PR of my own: #1112, adding weight transfer to the small KIS container.  (I encountered this issue while trying to launch a craft that had one of those attached to a Scout.)

**Comment by BobPalmer** [comment]
Closing - if others come up please send a PR
