### ISSUE TITLE
Hab timer showing inconsistent numbers

### ISSUE THREAD

**Issue by sh1pman** [BobPalmer/MKS#1110]
In VAB the hab timer in LS window shows more than 3 years for 12 kerbals, but fully assembled base shows around one year of hab time. 
Save file: https://dl.dropboxusercontent.com/u/46597246/quicksave%20%231.sfs
Craft file (has mechjeb part): https://dl.dropboxusercontent.com/u/46597246/Base%20Lander.craft

**Comment by dboi88** [comment]
I've done some investigations. It's due to the inflatable Hab, set to Hab-Quarters having no effect.

**Comment by BobPalmer** [comment]
Stupid question.  You filled it with machinery correct?

**Comment by BobPalmer** [comment]
Just tested this out... are you referring to the Ranger hab module?  If so, it appears to be working fine
