### ISSUE TITLE
Uninstalling messes up astronaut complex and traits

### ISSUE THREAD

**Issue by Maxzhao1999** [BobPalmer/MKS#1111]
It seems that after uninstalling MKS, all traits of kerbals except from the four orange suits become "XP trait", also, astronaut complex becomes empty(well, almost). See [screenshot](https://s30.postimg.org/yggve662p/IMG_1882.jpg)

**Comment by Maxzhao1999** [comment]
I manually changed the traits in my save files to solve this, is there a better solution?

**Comment by BobPalmer** [comment]
Not without extra code, no.
