### ISSUE TITLE
MKS_EL.cfg | MKS_Workspace

### ISSUE THREAD

**Issue by LouisCyfer** [BobPalmer/MKS#1125]
I'm pretty sure line 19:
`@PART[MKS_Workspace]:NEEDS[ExtraplanetaryLaunchpads]`

should look like:
`@PART[MKS_Workspace]:NEEDS[Launchpad]`

NOTE: for the most parts EL changed, as far I noticed
[MKS_EL.cfg.txt](https://github.com/BobPalmer/MKS/files/710591/MKS_EL.cfg.txt)

**Comment by theRagingIrishman** [comment]
Seeing as I was the one who wrote that part MKS_EL.cfg let me explain. MM uses folder names (ExtraplanetaryLaunchpads) OR dll names (Launchpad) when looking at NEEDS so it works fine. More info available [here](https://github.com/sarbian/ModuleManager/wiki/Module%20Manager%20Syntax#mod-dependency-checking).

**Comment by LouisCyfer** [comment]
ok nvm this issue then
