### ISSUE TITLE
Tundra Agriculture organics input

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#1130]
It shouldn't have organics as input, output, _and_ required resource. From what I understand the input is not necessary.

**Comment by MadMerlyn** [comment]
I always assumed that it was because you needed some organics to "seed" the production of more organics.

**Comment by jd284** [comment]
Yes but having the organics a "required resource" takes care of that. But on the other hand having it both as input and output resource has some unintended side effects.

**Comment by BobPalmer** [comment]
Fixed next patch
