### ISSUE TITLE
Can only inflate from parts with MKSWarehouse

### ISSUE THREAD

**Issue by DanStaal** [BobPalmer/MKS#1138]
If it's possible, it would be nice to be able to use resources in parts that don't have the Warehouse module to deploy inflatable parts.  At the moment it's somewhat surprising that you can *only* use MaterialKits from USI - despite there being other mods that use the same resource.

So, what would be nice:
- If there is no Warehouse module, the resources can be used.
- If there is a Warehouse enabled, the resources can be used.
- If there is a *disabled* Warehouse, the resources can't be used.

**Comment by jd284** [comment]
Also, if there's a piloted logistics module, it would be nice to also pull MaterialKits in planetary storage for this, for a reason see [this forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/154587-12x-temporary-mks-karbonite-support-thread/&do=findComment&comment=2940023).

**Comment by BobPalmer** [comment]
PS can now be individually disabled/enabled, and the current vessel is always included as a potential source of material kits for inflating modules.
