### ISSUE TITLE
Toggle Scavenging separately from Planetary Storage Warehousing

### ISSUE THREAD

**Issue by fat-lobyte** [BobPalmer/MKS#1147]
Currently, enabling/disabling Warehousing on a container toggles the behaviour for *both* Planetary Storage and Scavenging Mechanics.

This however causes some hiccups, for example when the player wishes to feed their kerbals on nearby vessels via Scavenging, but *not* push supplies into the planetary storage.

Would it be possible to toggle Scavenging separately from Planetary Storage Warehousing on all Containers?

**Comment by BobPalmer** [comment]
Done, next release
