### ISSUE TITLE
[Low priority] Karibou RoverCab - change CFG file KerbalMonths to BaseKerbalMonths

### ISSUE THREAD

**Issue by wile1411** [BobPalmer/MKS#1151]
The CFG file for the KER_RoverCab.cfg has a value under "ModuleHabitation" giving KerbalMonths = 1
Based on the Previous KER_Shelter fix, I'm guessing this also needs to be corrected to BaseKerbalMonths = 1

Note: This make no difference to the hab value in the VAB - just for consistency sake across all capsules that use ModuleHabitation

**Comment by BobPalmer** [comment]
Fixed
