### ISSUE TITLE
NRE on Maintenance

### ISSUE THREAD

**Issue by Gilph** [BobPalmer/MKS#1152]
While hitting perform maintenance for Machinery update:

[EXC 21:19:35.889] NullReferenceException: Object reference not set to an instance of an object
	USITools.USI_ModuleFieldRepair.PushResources (System.String resourceName)
	USITools.USI_ModuleFieldRepair.FinalizeMaintenance (System.String msg)
	USITools.USI_ModuleFieldRepair.PerformMaintenance ()
	BaseEvent.Invoke ()
	UIPartActionButton.OnClick ()
	UnityEngine.Events.InvokableCall.Invoke (System.Object[] args)
	UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters)
	UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters)
	UnityEngine.Events.UnityEvent.Invoke ()
	UnityEngine.UI.Button.Press ()
	UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
	UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
	UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
	UnityEngine.EventSystems.EventSystem:Update()

**Comment by BobPalmer** [comment]
If this is not sorted in the next patch let me know as I cannot repro this (and also include specifically which module you are performing maintenance on)

**Comment by Gilph** [comment]
Made a new vessel and landed on Minmus, in same career save as above. Same issue. Also the same in USI only save.  Save and log are here: [(https://1drv.ms/f/s!AigvIEvgjetqwnIsiTUUARa4Tork)]

**Comment by Gilph** [comment]
Fixed in .17
