### ISSUE TITLE
[CKAN] ckan update failure

### ISSUE THREAD

**Issue by patton446** [BobPalmer/MKS#1154]
CKAN failing to update because CKAN thinks Karibou assets are still registered to KaribouExpiditionRover. This causes CKAN to crash and results in a failed update.

Suggesting an incopatiblity with Karibou Rover in metadata
[CKAN crash log.txt](https://github.com/BobPalmer/MKS/files/766150/CKAN.crash.log.txt)

[CKAN karibou error.txt](https://github.com/BobPalmer/MKS/files/766142/CKAN.karibou.error.txt)

**Comment by BobPalmer** [comment]
Should be sorted
