### ISSUE TITLE
Hab common multiplier disappears if other vessels are <150m

### ISSUE THREAD

**Issue by Gilph** [BobPalmer/MKS#1155]
If a vessel has a habitat configured with a hab common multiplier, and it moves within range of other vessels, meaning that the "vessels shared within 150m" does not equal 0, the hab common multiplier disappears.  Also, the hab sharing capability is causing high hab bases

I took a vessel with three large Kerbitats and a Colonization module. One was configured as hab quarters, one as hab common.  With one Kerbal inside, the hab values in orbit around Minmus are: 226D (everything off), 7Y353D (hab quarters only), 34Y219D (both on). Landed next to an unmanned miner with both hab common and hab quarters turned on and hab at 34Y.  At 150m away, hab drops to 7Y353D (not at physics range, like I first thought), right when the vessels shared changed from 0 to 1. Toggling the hab common button has no effect, so it essentially like the part is not there. Toggling the hab quarters does change hab like you would expect and appears to not be affected.

I reset everything and landed the same ship by my large base (9 vessels, 12 kerbals). At the 150m point, my hab changed from 34Y to 1Y135D. Not only did I lose the 5x hab common multiplier, the hab time was spread out with 9 other vessels and lowered the hab time considerably.  Which also means that, at the moment, it's very hard to have a high hab base within a colony. Putting that same vessel back in orbit restores everything.  The timers all go back to normal, the hab common multiplier returns, and you can toggle both on and off.

To reproduce, just follow similar steps described above on any save.  I was using Hyperedit Lander to position a test ship with the habs 200m above bases on the surface, opening up the LS windows, and waiting to cross the 150m range to see the numbers change, then reverting.

**Comment by BobPalmer** [comment]
This has been fixed in the upcoming patch
