### ISSUE TITLE
After upgrading, sometimes Duna converters won't stay active

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#1175]
See also this [forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/154587-122-modular-kolonization-system-mks/&do=findComment&comment=2967273).

In some rares cases after updating to a new MKS version (or a dependency?), Duna converters keep turning off whenever the vessel is focussed, although they stay active in the background while not focussed.

For some odd reason cycling the landing legs seems to fix this issue.

**Comment by Gilph** [comment]
Save file: https://1drv.ms/f/s!AigvIEvgjetqwnVzD_BeUG7Wucas

Steps:

1. Load Dunatest save
2. Select base Mun Kolony
3. Start Cultivate on both AMs and the Purifier in the center Kerbitat
4. switch to tracking
5. Select base Mun Kolony
6. The AMs and the Kerbitat have stopped their resource conversions
7. Deploy the center Kerbitat, then the four outer Duna parts
8. Start Cultivate on both AMs and the Purifier in the center Kerbitat
9. switch to tracking
10. Select base Mun Kolony
11. the resource converters are still functioning

**Comment by BobPalmer** [comment]
Ok - fixed in next patch (USITools issue)
