### ISSUE TITLE
water doesn't flow through flex-o-tubes

### ISSUE THREAD

**Issue by cthulhum** [BobPalmer/MKS#1186]
I'm getting spurious "missing water" or "water full" errors from modules that consume or produce water if water storage is connected to that module through a flex-o-tube.

Working example: ball hub with two greenhouses attached to the sides and a water storage tank attached to the top - greenhouses correctly detect water and function.

Broken example: same as above, but add a flex-o-tube connecting the ball hub to an ASM producing water.  ASM reports water full, even if there is space in tank.  Adding an additional tank connected directly to the ASM fixes the problem, though it looks like water won't transfer automatically between the tanks (maybe if the one connected to the ASM is full?), as if the two warehouses don't see each other.

Further broken example: Same as above, but the ASM and attached tank are connected by another flex-o-tube to another agriculture module.  The greenhouses and ASM will still function correctly, but the third agriculture module reports "missing water."

Modules can sometimes be "tricked" into seeing the water by moving the water storage (via KAS) from one section of the base to another, but this I haven't been able to do this consistently.

**Comment by cthulhum** [comment]
Further note:  Water **can** be manually transferred between tanks in different sections of the base.

**Comment by BobPalmer** [comment]
This is a KIS / KAS issue.  Make sure you enable crossfeed.
