### ISSUE TITLE
Scavenging transfers not completed correctly

### ISSUE THREAD

**Issue by Gilph** [BobPalmer/MKS#1189]
Video: [https://youtu.be/Tmd_AqpwQ6s](url)
Post: [http://forum.kerbalspaceprogram.com/index.php?/topic/154587-122-modular-kolonization-system-mks/&do=findComment&comment=2974263](url)

Summary: In bases that have both a warehouse Kontainer and non-warehouse Module storage of the same type, the scavenging function will mix them up.  Transfers between the local storage and remote warehousing storage will appear to be from the Module storage, not the Kontainer, including ignoring locks put on the Module storage.

The video and steps linked above from Kobymaru (Thanks) show it happening to Organics.  My posts above show it affecting Recyclables, and I have also seen it with Munch on another base

Thanks.

**Comment by Gilph** [comment]
Here are some screenshots that show the recyclables issue on a base.
Screenshot 1 shoes all recyclables empty. The NFP and Recycler have local storage disabled, and the NFP is idle. The Redi Pak is enabled.  When Recycler starts, the Redi Pak should store the recyclables from the Recycler and also scavenge from the other warehouse enabled tanks in the colony.

[img]http://i.imgur.com/XjTPbSl.png[/img]

Screenshot 2 is over 20 days later.  There is nothing in the Redi Pak, which is unlocked and should be scavenging, and there is 156 recyclables in the NFP tank that is locked. The Recycler has a "missing recyclables" message, even though there are over 1000 recyclables in the other tanks on the colony, so it is not scavenging

[img]http://i.imgur.com/UGkdGZV.png[/img]

Screenshot 3 is afer the NFP tank  is unlocked. THe Recycler starts to function.  The amount in the NFP tank is reducing, but there is small bumps, showing scavenging happening from the other tanks.  In short, the scavenging function has switched the NFP and the Redi Pak functionality.  But nothing else in confused, so you eventually get the situation in SS2

[img]http://i.imgur.com/REEINEs.png[/img]

**Comment by BobPalmer** [comment]
Sorted in next release.
