### ISSUE TITLE
MPUs with heat mechanics run at 0% efficiency off Kerbin

### ISSUE THREAD

**Issue by Wyzard256** [BobPalmer/MKS#1199]
I've been testing the (not-yet-released) new MPU configs that include heat generation, and I've found that they work fine on the launchpad, but when I land one on the Mun, it runs at 0% efficiency and doesn't produce any output.

[Here's a save that illustrates the problem.](https://github.com/BobPalmer/MKS/files/826837/mun-mpu.zip)  The setup for it is a little weird: I'm using MKS v0.50.17, but with the MPU `.cfg` files replaced with current latest versions from DEVELOP: [`MKS_Processor125.cfg`](https://github.com/BobPalmer/MKS/raw/16a00bfbd23958ec54c496e2a9070d74948296c6/FOR_RELEASE/GameData/UmbraSpaceIndustries/MKS/Parts/MKS_Processor125.cfg), [`MKS_Processor250.cfg`](https://github.com/BobPalmer/MKS/raw/16a00bfbd23958ec54c496e2a9070d74948296c6/FOR_RELEASE/GameData/UmbraSpaceIndustries/MKS/Parts/MKS_Processor250.cfg), [`MKS_Processor375.cfg`](https://github.com/BobPalmer/MKS/raw/16a00bfbd23958ec54c496e2a9070d74948296c6/FOR_RELEASE/GameData/UmbraSpaceIndustries/MKS/Parts/MKS_Processor375.cfg).

There's a lander on the Mun that's configured to produce fertilizer from gypsum.  It has plenty of gypsum stored, plenty of power, plenty of cooling, and plenty of fertilizer storage capacity, but its thermal efficiency is 0% and the converter's load just says "Operational".  It doesn't build up any core heat and doesn't produce any fertilizer.

If you edit the `.sfs` and change the vessel's `GeologyResearch` line from 0 to 99999999, the converter will show a load of 0.01% instead of "Operational".  I don't know whether that indicates that the problem is related to kolonization bonuses, or if the load is really nonzero all the time and the bonus just makes it big enough to show up in the UI.

**Comment by Wyzard256** [comment]
Determined to be a bad `ThermalEfficiency` float curve; details and solution in #1176.

**Comment by BobPalmer** [comment]
Closing as that merge is in place
