### ISSUE TITLE
incorrect Gypsum to Chemicals converter on MPU (medium and large)

### ISSUE THREAD

**Issue by caipi-** [BobPalmer/MKS#1200]
The Material Processing Units (2.5m) & (3.75m) (file names \GameData\UmbraSpaceIndustries\MKS\Parts\MKS_ProcessorXXX.cfg) are both affected by the following error:

The converter Fertilizer (G), which is supposed to convert Gypsum to Fertilizer, is converting Gypsum to Chemicals.

The smaller processing unit, the tundra agriculture support module and the ranger crush-o-matic portable extractor are not affected.

**Comment by Wyzard256** [comment]
The fix for this has already been merged: #1178

**Comment by caipi-** [comment]
Just FYI: The fix may have been merged in the developer version, but it is not fixed in the live version yet:
https://github.com/BobPalmer/MKS/blob/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/MKS/Parts/MKS_Processor250.cfg#L484
https://github.com/BobPalmer/MKS/blob/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/MKS/Parts/MKS_Processor375.cfg#L498
