### ISSUE TITLE
Parts built with OSE workshop consume Material Kits on maintenance.

### ISSUE THREAD

**Issue by sh1pman** [BobPalmer/MKS#1204]
Even though the wear&tear mechanic has been disabled, many MKS parts still have ReplacementParts resource listed. Usually it's not a problem, but OSE Workshop builds these parts with 0 ReplacementParts. As a result, when an engineer performs maintenance, a lot of Material Kits get destroyed. For example, several thousand Material Kits disappeared when I used the maintenance function on a newly-printed Ranger Hab module.

**Comment by BobPalmer** [comment]
This is sorted in the next release
