### ISSUE TITLE
New MPU 2.5 and 3.75 Converter Fertalizer(G) outputs Chemicals

### ISSUE THREAD

**Issue by kkdredd** [BobPalmer/MKS#1208]
The MPU 2.5 and 3.75 converter outputs chemicals when in Fertalizer(G) setting.

I'd do a PR to change this, but it looks like the conversion ratio would be way off and I'm not sure what the ratio should be.

The MPU 1.25 looks like it is correct.

**Comment by Wyzard256** [comment]
This was fixed in v0.50.18.
