### ISSUE TITLE
Ranger Agricultural Module Won't Deploy

### ISSUE THREAD

**Issue by MadDoctor5813** [BobPalmer/MKS#1211]
I have a Ranger Agricultural Module up on my station, and it won't deploy, I have filled it full of Fertilizer and Machinery, but there is no deploy option visible when I right-click on it. The module seems to be working and producing supply, but I obviously can't transfer any crew into it. Oddly enough, it deploys fine in the VAB.

**Comment by BobPalmer** [comment]
EVA with Material Kits to deploy.
