### ISSUE TITLE
Add Support For ASET Props In IVAs [FR] [SR]

### ISSUE THREAD

**Issue by JohnLatour** [BobPalmer/MKS#1251]
[http://forum.kerbalspaceprogram.com/index.php?/topic/116430-aset-props-pack-v14-for-the-modders-who-create-iva/](url) 
Tags
**Feature Request**, **Support Request**

**Comment by BobPalmer** [comment]
To be honest, unless someone sends me a pull request, this will not happen.

**Comment by JohnLatour** [comment]
I'm going to try and edit some MKS IVAs, if that is okay with you? I would then send them to you in a pull request correct?
