### ISSUE TITLE
Add feature to Karry Kans

### ISSUE THREAD

**Issue by Jcap7** [BobPalmer/MKS#250]
Posted in the mks thread and some one said to post over here.  Just wondering if it's fits with your mod plans and you are willing, any chance you could make the Karry Kans able to hold some LS supplies of Food, Oxygen, or water. One at a time and then maybe just like 1 days worth in the single Kan and maybe 2 days in the double Kan or something like that? 

My original post is on page 409 of the Mks thread.  And the thought of this came about on my trying to find easy quick ways to top up the LS supplies of a manned rover that will be permanent on a planet or mun.  Thought these would be great for something like this.  So if you are willing and it fits with your plans I think it would be great.

**Comment by BobPalmer** [comment]
Closing - this can be satisfied with KAS-able LS containers.
