### ISSUE TITLE
OnFixedUpdate - Outside range

### ISSUE THREAD

**Issue by starkline** [BobPalmer/MKS#261]
From the forum post http://forum.kerbalspaceprogram.com/threads/79588-0-25-USI-Kolonization-Systems-%28MKS-OKS%29-%280-21-2%29-2014-10-07?p=1497942&viewfull=1#post1497942

My log is giving this (never ending) error:

[Log]:[MKS] - ERROR in OnFixedUpdate - Outside range [MinValue,MaxValue]

I've done some looking into it, and it seems that it's caused by the Kerbitat, but only if it is full of Machinery. If I transfer some Machinery out of it, the error stops. It also seems as if having Storage Tanks (MKS_Storage_Tank_01-06) plays a part in the error. If no storage tanks are present in the vessel, the error is not present.

You asked for a craft file. Apparently, I can't attach it here or in the KSP forum. How would you like me to send it to you?

**Comment by BobPalmer** [comment]
Closing this as everything switched over to Regolith on 0.90 and I have not heard of this bug since
