### ISSUE TITLE
Recovery cost on Inflatable Storage Modules

### ISSUE THREAD

**Issue by Viragos** [BobPalmer/MKS#268]
inflated OKS storage modules have a large -funds value during recovery. Somewhere in the region of -1,000,000 per module

**Comment by koshboo** [comment]
this is still happening if you recover a inflated module without it being full you take a masive hit to you wallet

**Comment by BobPalmer** [comment]
And if you deflate them?

Sorry, I just can't change how stock KSP works and it's wonky with resources.  So deflate before recovery.
