### ISSUE TITLE
OKS / MKS Module Titling

### ISSUE THREAD

**Issue by SyberSmoke** [BobPalmer/MKS#278]
The OKS / MKS Modules have little to differentiate them selves with in the research and construction menus.  The problem is that OKS modules do have a higher capacity then their MKS counterparts.  With the small Icons, a player in a specific mode on play (Paying Science and Credits for unlocks) may not be able to clearly define modules (it took me some).

Suggestion: Either label the parts differently (with an OKS or MKS specifically) or differentiate the two lines into separate trees of the tech tree.  That way parts are better defined and easier to unlock at harder difficulties.

**Comment by BobPalmer** [comment]
Fixed in a prior release
