### ISSUE TITLE
[Feature Request]: Multiple Efficiency Parts

### ISSUE THREAD

**Issue by Angel-125** [BobPalmer/MKS#284]
The MKSWorkshop uses an EfficiencyPart to enhance productivity of the KolonyConverters. It would be great if the MKSWorkshop could support multiple efficiency parts, any one of which will enhance productivity. That would make it easier for third party modders to create additional efficiency parts that can be supported by MKS/OKS.

**Comment by BobPalmer** [comment]
This feature is enabled for the next release
