### ISSUE TITLE
MKS_ScanOMatic.cfg

### ISSUE THREAD

**Issue by DenisVasiliev** [BobPalmer/MKS#289]
Seems like ScanOMatic still uses 
	MODULE
	{
		name = ORSX_ResourceScanner
		resourceName = Ore
		mapViewAvailable = false
	}

**Comment by kaa253** [comment]
I replaced the ORS code with the following code which seems to work and adds Karbonite detection (I expect the last line; MaxAbundanceAltitude = 500000     is incorrect and/or not required here?)...

MODULE
{
	name = REGO_ModuleResourceScanner
	ScannerType = 0
	ResourceName = Minerals
}
MODULE
{
	name = REGO_ModuleResourceScanner
	ScannerType = 0
	ResourceName = Ore
}
MODULE
{
	name = REGO_ModuleResourceScanner
	ScannerType = 0
	ResourceName = Substrate
}
MODULE
{
	name = REGO_ModuleResourceScanner
	ScannerType = 0
	ResourceName = Uraninite
}
MODULE
{
	name = REGO_ModuleResourceScanner
	ScannerType = 0
	ResourceName = Water
}	
MODULE
{
	name = REGO_ModuleResourceScanner
	ScannerType = 0
	ResourceName = Karbonite
	MaxAbundanceAltitude = 500000
}

**Comment by BobPalmer** [comment]
Thanks - given the survey camera replaces a lot of this, I have some alternate plans for this part.

**Comment by BobPalmer** [comment]
(Design notes:  Update Soil Sample module to also act as a biome scanner, MKS bits only)
