### ISSUE TITLE
OrbitalDock CTT integration

### ISSUE THREAD

**Issue by sopindm** [BobPalmer/MKS#291]
Hi,
I see that new orbital dock module isn't integrated into Commutiny Tech Tree - it still in Specialized Construction.

I think, following lines in CTT.cfg are required (already added to my installation):

@PART[MKS_EL_OrbitalDock]:NEEDS[CommunityTechTree,TechManager]
{
    @TechRequired = orbitalMegastructures
}

**Comment by BobPalmer** [comment]
Thanks!  Fixed for next release
