### ISSUE TITLE
Pioneer module costs

### ISSUE THREAD

**Issue by kaa253** [BobPalmer/MKS#297]
Similar to issue #292 for the storage tank cost. The 3 pioneer modules (when empty) appear to be about 10x more costly than would be expected when compared to, for example, TACLS storage containers.

**Comment by Ramarren** [comment]
This is cause by a bug KospY/KAS/issues/125 in KAS, every module which includes KASModuleContainer has doubled wet cost. If you delete that module the Pioneers cost basically zero when empty.

**Comment by BobPalmer** [comment]
Fixed by Ramarren
