### ISSUE TITLE
EVA Maintenance does not work

### ISSUE THREAD

**Issue by cmSaS** [BobPalmer/MKS#299]
Machinery and Spare parts not transferring between anything via Kerbal Engineer during EVA. Both in my modded build and a clean install. No transfers of any kind between MKS modules and their legs portions or from OKS and pioneer modules. Or MKS modules and pioneer modules for that matter. 

I've tried with both the MKS_0.22.3.zip and the current MKS-master.zip

**Comment by cmSaS** [comment]
Scenario 1 MKS
Vehicle - Colony Control Center + Integrated Module Base
C3 has spare parts set to 0, Module base Spare Parts set to full.
Location - Launch Pad
1. Engineer Exits Module
2. On ladder during EVA, right-click C3 module "Perform maintenance"
3. Reenter Module after Green text "You perform routine maintenance." 
No spare parts have moved into the C3
note: Same results if C3 is at different SpareParts quantities.
![1](https://cloud.githubusercontent.com/assets/2425386/5686676/4d280b5e-9802-11e4-87dc-7fd670173c10.png)


Scenario 2. OKS
C3 + Pioneer Module lifted into Orbit
OKS C3 has spare parts set to 0, Pioneer Module Spare Parts set to full.
1. Engineer Exits Module
2. On ladder during EVA, right-click C3 module "Perform maintenance"
![3](https://cloud.githubusercontent.com/assets/2425386/5686682/5b5395b8-9802-11e4-9e48-f58a7de0c5e4.png)
3. Reenter Module after Green text "You perform routine maintenance." 
Same results. No spare parts have moved into the C3
![4](https://cloud.githubusercontent.com/assets/2425386/5686686/65b515c2-9802-11e4-882c-646bef3685d0.png)

**Comment by cmSaS** [comment]
As a side note... I like the mechanic since it enables a use for the engineer but doesn't this mean that the player can never replenish storage containers of spare parts?

**Comment by BobPalmer** [comment]
They would be filled by manufacturing from a repair module.

**Comment by BobPalmer** [comment]
Sorted.  Will be fixed in next release.
