### ISSUE TITLE
MKS-III modules clipping through the ground

### ISSUE THREAD

**Issue by Eng1N33R** [BobPalmer/MKS#300]
After updating to 0.22.3 all of the new Mk III modules clip through the ground on my client.

![Bug](http://i.imgur.com/ZFs7mqs.png)
![Bug](http://i.imgur.com/LJJrmBe.png)
![Bug](http://i.imgur.com/NrRl6ok.png)

Placing the module on clamps and releasing it makes it disappear into the ground completely and explode.

![Bug](http://i.imgur.com/r2jErL9.png)
![Bug](http://i.imgur.com/SFzd2HK.png)
![Bug](http://i.imgur.com/2tbCciI.png)

**Comment by BobPalmer** [comment]
This was a collider issue.  This will be fixed in the next patch.
