### ISSUE TITLE
Dry weights not set on any parts using FSFuelSwitch

### ISSUE THREAD

**Issue by darloth** [BobPalmer/MKS#302]
FuelSwitch requires that you specify dry mass differently, with these two parameters:

// This is the dry mass of the part before any tanks at all, even empty ones, and should usually match the 'mass' basic parameter of the part.
basePartMass = 0.046  
// This is the additional dry mass of each tank config.
tankMass = 0;0.012;0.006

These don't seem to be specified for any part across the entire USI range, so all fuel-switch using parts have the default dry mass of 0.25, whether big or small, and it does not change depending on part type.

Two examples: The tiny spare parts/other crate, and the radial storage tank.
As far as I can tell B9 Aerospace uses these parameters extensively if you need another reference for how they work.

**Comment by BobPalmer** [comment]
Fixed
