### ISSUE TITLE
MKS current & Beehive compilation of issues

### ISSUE THREAD

**Issue by Prototype2001** [BobPalmer/MKS#303]
**MKS Current**

**Dampeners**
Engaging dampeners causes downwards of 1 fps to all nearby crafts of the dampener due to error spam:
"[Error]: Actor::setAngularVelocity: Actor must be (non-kinematic) dynamic!"
Having more dampeners engaged magnifies this error spam.

**Kerbals inside modules**
Lower efficiency for the module kerbals are inside while boosting efficiency for the whole base. Ex: with 1 kerbal inside a C3 & fabrication module. C3 efficiency is at 75%, removing a kerbal puts it at 90% adding the removed kerbal to the fabrication module brings the effiency to 150%, c3 worked better while kerbal was outside.

**Drills** 
Deploying drills in orbit causes error spam, significantly lower fps.  27->9 
Activating upwards of 128 drills while landed lowers fps significantly. 16->10 & 10->4 two cases.
 
**Vanishing resources?**
http://i.imgur.com/tI5yzRg.jpg
These 3 resources were at 0 when when i loaded up this base, halting some production, deploying drills instantly filled them up(drills were off due to above entry) thats a quarter of a million of vanished ore, substrate, & minerals. Might have something to do w. punch-cards as i had those at 0 w. c3 off.

**PDU module**
This module is completely inferior to the honey badger nuclear reactor due to efficiency hit from PDU activation, not sure where you want to draw the line as they are two different mods.

**MKS BEEHIVE**
-----------------------------------------------------------------------------------
**Invisible Parts**
MKS/OKS & FTT parts are not displayed in VAB & SPH while loading saved crafts is possible, attempting to launch them presents an "Unavailable experimental parts" error. With that said I was still able to load bases containing these parts to do some tests.

**Dampeners**
Same error under same circumstance, turning off dampeners fixes it. 
Don't remember if linear velocity was part of the error log in released, will check later.
[Error]: Actor::setLinearVelocity: Actor must be (non-kinematic) dynamic!
[Error]: Actor::setAngularVelocity: Actor must be (non-kinematic) dynamic!

**Kerbals inside modules**
Kerbals inside modules don't lower the efficiency for the module they are in anymore, although they aren't helping it either, tested with 0 star kerbals.

**PDU module**  While empty, an active PDU module now works at 0% capacity further making this inferior to the honey badger nuclear reactor.

**Comment by BobPalmer** [comment]
Let me know the beehive results since the dampener issue is one I would like to see tested.

**Comment by BobPalmer** [comment]
PDU issue is Probably due to the level zero Kerbals.  Let me toy with some dampener ideas.

**Comment by BobPalmer** [comment]
With quality kerbals the PDUs are superior (not in the module but in the vessel).  With bad kerbals the HB reactor is superior.  Also HB reactor is heavier, with a level load of 2K EC/Sec.  The PDUs can, when crewed correctly, easily hit double that.  

Also new dampener code.  Also did a cleanout of beehive and paved it over, dropped in a new updates set of files - let me know if pathing issues still exist.  Note this has to go on a clean install.
