### ISSUE TITLE
Entering depleted ship from EVA instantly kills Kerbal

### ISSUE THREAD

**Issue by dphrag** [BobPalmer/MKS#304]
I had an aeroponics module where everyone died of asphyxiation as I couldn't attach, and no Oxygen remained.

Took a kerbal from nearby base onto EVA, and entered the depleted ship and he died instantly, even though his EVA suit had oxygen stores. Was unexpected, and sad. :(

**Comment by BobPalmer** [comment]
Closing as this is a TAC-LS issue.

**Comment by dphrag** [comment]
Oh gawd, sorry, I was in the wrong git. :\

**Comment by BobPalmer** [comment]
No worries :)

**Comment by dphrag** [comment]
If anyone ends up here by accident like I did, here is the proper bug in the proper repo: https://github.com/taraniselsu/TacLifeSupport/issues/19
