### ISSUE TITLE
Save is corrupted when uninstalling mod

### ISSUE THREAD

**Issue by Legomany3448** [BobPalmer/MKS#307]
I'm trying to uninstall this mod (the amount of resources and parts and whatnot is overwhelming me a little) but even though I haven't used any of the part from the mod in either saved or launched crafts, if I remove the mod normally I am unable to access the VAB or SPH once I load my save. I can still access the R&D facility, but cannot exit it. I even went through my persistent.sfs file and removed all traces I could find of MKS (just the R&D unlocked tech stuff), but my game still does not work. If I reinstall the mod, everything works perfectly again. I also tried making a new save after uninstalling the mod, and that worked perfectly normally too. Please either package an uninstall utility with the mod, don't mess with save files any more than necessary (R&D, parts in crafts, etc.), or have something on the wiki about how to fix this issue. Thank you!

**Comment by sopindm** [comment]
Had same issues with RealChute and MKS - it's missing agency. Try to remove all contracts with USI agency or just leave agency data in game.

**Comment by BobPalmer** [comment]
I do not 'mess with save files'.   Closing this as it is a user issue not a mod issue.

**Comment by Legomany3448** [comment]
Wow! Thank you for the quick response. It's true that there was one contract I had completed from USI that I didn't catch. After removing that, it is all fixed. :+1:
