### ISSUE TITLE
Inflatable storage modules reverting to original capacities

### ISSUE THREAD

**Issue by watson895** [BobPalmer/MKS#312]
![2015-01-12_00001](https://cloud.githubusercontent.com/assets/10500917/5705262/5e6838e6-9a4e-11e4-826f-8a19cc49471f.jpg)
If I transfer away from the base after inflating the modules, I come back to find the modules capacities restored to the original size. Retracting it and reinflating it causes any extra to be deleted.

**Comment by asmodesu** [comment]
I've also encountered this issue. The only "legitimate" workaround I've been able to figure out is to retract them, return to ksc or transfer to another vessel and then come back to redeploy. After that they work as intended... until you transfer again.
