### ISSUE TITLE
Activating Drop Anchor Changes Vessel State to "Not Landed"

### ISSUE THREAD

**Issue by basedrifter** [BobPalmer/MKS#313]
Steps to reproduce:

1. Construct a vessel with MKS module base, any vessel on top, and a DTS-M1 (to check vessel state)
2. Launch vessel on launchpad
3. Activate drop anchor function in landing base

After activating the anchor the vessel state will be permanently set to "not landed." Easy to check vessel state using the DTS-M1. Raising the anchor will not revert the vessel state. Having the vessel state as not landed prevents revert, going back to space center, or switching vessels.

**Comment by BobPalmer** [comment]
Should already be fixed

**Comment by basedrifter** [comment]
Indeed it is!
