### ISSUE TITLE
Different Button Position for Various Expand-o-tubes

### ISSUE THREAD

**Issue by basedrifter** [BobPalmer/MKS#314]
The Kerbitrail Expand-o-tube XL and Mini have the button order as Lights followed by Arm/disarm, the regular Expand-o-tube has the button order reversed with the arm/disarm button on top and lights below it.

(I may actually have them reversed, but in any case, the regular expand-o-tube has the buttons reversed from what they are on the XL and mini.)

**Comment by BobPalmer** [comment]
Should be fixed :)
