### ISSUE TITLE
Unable to activate part generators

### ISSUE THREAD

**Issue by Eng1N33R** [BobPalmer/MKS#315]
I am unable to activate module generators (e.g. the Habitat generator in the Kerbitat module) even though the setup is correct.

As an example, this rig was created by following the wiki tutorial to the letter:

![OKS barebone rig](http://i.imgur.com/IBGROsh.jpg)

This contains an equipment and agriculture Storage Tank, a Pioneer Module for life support and a large Life Support Container for good measure, an Aeroponics Module, a Colony Control Centre, a Kerbitat, a Power Distribution Unit, a Habitation Ring, an Agricultural Module and an Inflatable Workshop. The efficiencies on all modules are unknown and only get a value after turning on the Governor (they seem to revert back to unknown after switching to another craft). There are no buttons present to activate any of the generators, e.g. the Habitat in the Kerbitat module or the power generator in the PDU. All modules are stocked up on the Machinery, SpareParts and PunchCards resources.

The same problem appears on an orbital station of a similar design and characteristics:

![Station](http://i.imgur.com/YxDvcnL.jpg)

**Comment by BobPalmer** [comment]
Insufficient info - i.e. which MKS version?  Did you grab Regolith from GitHub? etc.

**Comment by Eng1N33R** [comment]
Sorry, it was, indeed, a problem with Regolith - updating to the latest version solved it.
