### ISSUE TITLE
Remove governor from Kerbitat/Aeroponics modules

### ISSUE THREAD

**Issue by basedrifter** [BobPalmer/MKS#316]
This was an idea that had come up in the MKS thread a couple weeks ago. New users unfamiliar with MKS/OKS sometimes turn on the governors for these modules leading to life support sufficiency problems. It's hard to imagine a time when the governors should actually be turned on for these modules, so removing them could help improve the learning curve and playability for new users.

Example: http://forum.kerbalspaceprogram.com/threads/79588-0-90-USI-Kolonization-Systems-%28MKS-OKS%29-%280-22-3%29-2014-12-27?p=1670557&viewfull=1#post1670557

**Comment by BobPalmer** [comment]
Removing the governor entirely, given the frequency at which it causes questions and given Regolith can trickle-charge

**Comment by basedrifter** [comment]
Right on!
