### ISSUE TITLE
Tweakscaled radial supply tanks do not retain correct capacity

### ISSUE THREAD

**Issue by wisq** [BobPalmer/MKS#321]
There are a number of events that will reset the capacity of a radial supply tank to the default quantity:

1. Applying symmetry
2. Cloning the part
3. Saving/loading (including launching)

Whan this means is, if you have a tank that (say) holds 1200 of a resource, and you resize it from 1.25m to 2.5m, it now holds 9600 of that resource.  But when you grab it for symmetry, it will revert to only holding 1200 of that resource, despite the increased size.

If, instead of grabbing it, you just launch the ship, you'll find that you now have 9600 out of 1200 in that tank, i.e. it's over capacity.

So while radial supply tanks + tweakscale are okay for getting quantities of a resource into orbit, it won't work for long term storage (e.g. on an OKS space station), because they'll always have the 1.25m capacity no matter what size they are.

Demonstration video: https://www.youtube.com/watch?v=akaeg7-gu9Y

Running Kolonization 0.22.3, Tweakscale 1.50, both from CKAN.  I'm also running *a ton* of other mods, so if it turns out this is some weird interaction and isn't reproducible on your end, please let me know and I'll dig deeper.  Right now I'm assuming it's just a simple oversight.

**Comment by Ramarren** [comment]
This is some combination of bugs in FSfuelSwitch and Tweakscale. I have implemented a fix for Firespitter Ramarren/Firespitter/commit/c74f48014f7632da2ab63bb907146067d45c1677 , but it also probably requires a change in TWEAKSCALEEXPONENTS definition for FSfuelSwitch to remove the relative scaling exclamation marks.

**Comment by pellinor0** [comment]
It looks like this is fixed and can be closed. Please contact me if there is anything left to do from the TweakScale side.
