### ISSUE TITLE
Identically named texture breaks compatibility with Active Texture Management

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/MKS#324]
Currently MKS has two assets named Decal_375_00 (with different file extensions: mbm and png), which causes KSP to hang upon loading with Active Texture Management. Deleting one of the files (only tested with mbm) fixes issue.

**Comment by BobPalmer** [comment]
Missing glow is fine, that's just part of the config generation.  Also removed one of the decal files, fixed in next patch
