### ISSUE TITLE
( request) (not a bug)unblanking optional config for EPL.

### ISSUE THREAD

**Issue by Joshwoo69** [BobPalmer/MKS#325]
I still want my old EPL and not the mks replaced version. Can you have a optional file to remove the offending replacements?

**Comment by enceos** [comment]
You can tweak the EL_CONFIG.cfg for the EPL parts you want back, or you can delete this file completely, in this case all the EPL will come back with smelters an refineries unless you deleted them manually.

**Comment by Joshwoo69** [comment]
Thnaks closing the issue
