### ISSUE TITLE
Module interactions not available

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/MKS#328]
After the recent update to .22.4, module interactions are missing. Instead of buttons to e.g. make LFO at the Fuel Refinery, the right-click menu displays lines saying "status: Inactive." 

![image](https://cloud.githubusercontent.com/assets/9939641/5939779/a070803a-a6d4-11e4-9cdb-3688c6ee7a5c.png)

Originally posted on the [forum] (http://forum.kerbalspaceprogram.com/threads/79588-0-90-USI-Kolonization-Systems-%28MKS-OKS%29-%280-22-4%29-2015-01-27?p=1699170&viewfull=1#post1699170), but I think that it was lost in the churn while awaiting moderator approval.

**Comment by enceos** [comment]
Try to reinstall the mod completely, I had partially this issue, then I reinstalled the mod and all the buttons came back:
!http://i.imgur.com/6MZ7Si7.png

**Comment by LouisB3** [comment]
Is there anything in particular you did differently when you reinstalled? I did try reinstalling but had no change, either in existing or new savegames.

**Comment by enceos** [comment]
In you shoes I would make a separate clean copy of KSP with MKS and module manager installed and see if it works fine there. If it does, then there's probably a conflict between it and other addons. If it doesn't then its an MKS issue.

**Comment by BobPalmer** [comment]
Fixed, bundling in next release
