### ISSUE TITLE
Missing Decal_375_00_GLOW

### ISSUE THREAD

**Issue by enceos** [BobPalmer/MKS#329]
![Imgur](http://i.imgur.com/774XVxF.png)

**Comment by LouisB3** [comment]
possibly related to issue #324, which also involves decal_375_00

**Comment by enceos** [comment]
There we had a duplicate, here we are missing the glowing texture completely.

**Comment by LouisB3** [comment]
Perhaps the duplicate texture is meant to be the glowing texture but misnamed? Since #324 has been tagged next-version I figure it would be useful to bring the possible connection to @BobPalmer's attention.

**Comment by BobPalmer** [comment]
nah, the dup is a smaller PNG for space savings - this is just an artifact of the code generation that makes all of these modules
