### ISSUE TITLE
Generators not activating/not producing outputs with 0.22.4

### ISSUE THREAD

**Issue by Angel-125** [BobPalmer/MKS#330]
Unfortunately I'm unable to activate the converters with 0.22.4. There's no activation button in the context menu, and while the Station Manager will activate the converter, it always remains Inactive.

Logs: http://www.spellflight.com/KSP/KSPLogs.zip

Steps to reproduce
1. Make a copy of KSP and remove everything from the GameData directory except for Squad and NASAMission.
2. Download MKS/OKS 0.22.4 and install the contents to the GameData directory.
3. Start KSP, and create or load a sandbox game.
4. In the VAB, start with a 1.25m probe core.
5. From the Utilities tab, add a Colony Command Center just below the core.
6. From the Utilities tab, add an RTG.
7. Right-click on the Colony Command Center, and lower the amount of PunchCards to 0.
8. In the Crew tab, select two Engineers for the C3's crew.
9. Press Save to save the untitled spacecraft.
10. Launch the vehicle.
11. On the pad, right-click the C3 module.
Expected Result: context menu should show a button to activate the Command converter.
Actual Result: no button appears to activate the converter.
12. Click on the Station Manager, select Parts, and Activate the Command converter.
Expected Result: converter activates and is operational
Actual Result: converter does not appear to be activated.
13. Press Escape to pause the game, and Revert flight to launch.
14. After regaining control, right-click the context menu on the C3 part.
Note: At this time, the context menu shows the Activate Command button, and when pressed, the converter begins producing PunchCards.

Screenshots in sequence
![screenshot10](https://cloud.githubusercontent.com/assets/9408067/5940961/ebceb2c0-a6c2-11e4-8f92-732a8fb1442b.png)
![screenshot9](https://cloud.githubusercontent.com/assets/9408067/5940972/fd4bcc0e-a6c2-11e4-92e7-c4ccb08c3747.png)
![screenshot11](https://cloud.githubusercontent.com/assets/9408067/5940987/0860cc5c-a6c3-11e4-801e-35daaf44537e.png)
![screenshot12](https://cloud.githubusercontent.com/assets/9408067/5940991/0fd44ffe-a6c3-11e4-8acc-7c13e88a451a.png)
![screenshot13](https://cloud.githubusercontent.com/assets/9408067/5940993/144de93c-a6c3-11e4-924e-ee39af81b069.png)

**Comment by LouisB3** [comment]
I noted something similar in issue #328, though I did not know about the station manager workaround

**Comment by BobPalmer** [comment]
Fixed in next release
