### ISSUE TITLE
Loading stuck MK_3 fabricator

### ISSUE THREAD

**Issue by Pieterrr** [BobPalmer/MKS#331]
Just installed the new version 0,22,4 and while loading the game it gets stuck on the MK_3 fabricator

**Comment by enceos** [comment]
Same here, see if you updated Regolith.dll as well as everything else. Had the same issue playing with Regolith.dll versions, but the latest version works fine.

**Comment by Pieterrr** [comment]
The latest version that was included in MKS? Because I copied everything including the dll file but I get stuck.

**Comment by BobPalmer** [comment]
A new release is coming out tonight, though I did not see this specific issue see if it gets sorted.  If not post on the forum thread.
