### ISSUE TITLE
Kolonization SCANsat.cfg (Uraninite Fix)

### ISSUE THREAD

**Issue by Tebryn** [BobPalmer/MKS#334]
updated [SCANsat.cfg](https://github.com/BobPalmer/MKS/blob/master/GameData/UmbraSpaceIndustries/Kolonization/SCANSat.cfg) to include uraninite as defined by [SCANresources.cfg](https://github.com/S-C-A-N/SCANsat/blob/dev/SCANassets/Resources/SCANresource.cfg#L26) in SCANsat 10.0
```
@PART[MKS_Antenna]:FOR[KolonyTools]:NEEDS[SCANsat]
{
	MODULE
	{
		name = SCANsat
		sensorType = 107648
		fov = 4
		min_alt = 5000
		max_alt = 750000
		best_alt = 100000
		scanName = Resource Scan
		power = 0.5
	} 
}
```

**Comment by Olympic1** [comment]
Uraninite already has a number, so it must be ``sensorType = 1024``

**Comment by Tebryn** [comment]
you add all the resource numbers together when setting up your SCANsat scanners. in this case, for the planetary camera...
Ore = 128
Uraninite = 1024
Water = 8192
Minerals = 32768
Substrate = 65536
Total for sensorType since it scans for all the above = 107648

**Comment by Olympic1** [comment]
Oh ok, good to know that also works

**Comment by BobPalmer** [comment]
Less of 'Also works' and 'Doesn't break a multi-resource scanner'...

**Comment by BobPalmer** [comment]
Fixed in next patch.
