### ISSUE TITLE
Add a KAS option for MKS Storage Tank

### ISSUE THREAD

**Issue by spaceparrot** [BobPalmer/MKS#337]
I've posted something similar about the Kontainers in FTT, but it occurred to me the Storage Tank in MKS would work well as KAS storage, could it be added as an option? Kontainers are huge, storage tanks w/KAS would make a nice midpoint between the KAS boxes and Kontainers for transport.

**Comment by pectus-solentis** [comment]
Agree. With MRS (Mobile Repair Shop) being able to fabricate KAS Gadgets, it will much be splendid.
