### ISSUE TITLE
Add a KAS-only storage module

### ISSUE THREAD

**Issue by spaceparrot** [BobPalmer/MKS#338]
It seems to me a well-developed Kolony would store spares and other equipment safely and neatly in a purpose-built storage module. Could a KAS storage module (or two, one the size of a lab/C3 module and one the size of the workspace module) be added to MKS? I don't know how much modeling that will take, if I had to pick I'd rather have the larger part as the smaller would (I think) be the same size as the base and thus a bit redundant. An OKS version would be really nice as well!

**Comment by enceos** [comment]
The Integrated Module Base has a very big container of 240 units.
![imgur](http://i.imgur.com/eBHhcBC.png)


Same with orbital pioneer modules, but they have only 80 units of storage space.

![Imgur](http://i.imgur.com/hjKdkk0.png)

**Comment by enceos** [comment]
You can create one for yourself from the Pioneer cfg file. Removing all the resources storage and increasing KAS storage.

**Comment by spaceparrot** [comment]
I thought about adding a KAS pioneer module via cfg editing, but I don't think it would have enough KAS storage for my purposes without breaking consistency of size vs storage. I know about the storage in the base, but 240 KAS units only lets me store the parts for a rover without crates or instruments. A full size storage module should have 480 units, which allows for a rover and a pile of instruments, crates, and so forth. Or two rovers, with instruments in the base.
