### ISSUE TITLE
MKS Workspace modules can permanently trap crew

### ISSUE THREAD

**Issue by Entropy2016** [BobPalmer/MKS#339]
If you use the stock crew-transfer function to move a Kerbal into an MKS Workspace Module, that Kerbal is basically trapped forever (unless you're on Kerbin and can recover the entire craft).

I think this stems from the fact that the MKS Workspace Module doesn't actually have a hatch that works.  So while the Workspace Module is a valid destination for crew transfers, it's not a valid source for crew transfers (since that requires a functioning, clickable hatch).

**Comment by enceos** [comment]
Rover was reluctant to adding crew spaces in these modules, cause issues you describe will arise. Bob needs some time to add hatches to these modules.

**Comment by Kerbas-ad-astra** [comment]
If you need to get a trapped Kerbal out in a hurry, [Ship Manifest](http://forum.kerbalspaceprogram.com/threads/62270) will let you browse and transfer any of your crew, whether they're in a module with a hatch or not.

**Comment by BobPalmer** [comment]
Fixed
