### ISSUE TITLE
MKS issue compilation.

### ISSUE THREAD

**Issue by Prototype2001** [BobPalmer/MKS#340]
On the ones that aren't obvious i'll try to provide info on how to replicate them. Right now I'm just writing down everything I came across.

Gathered from clean install.

***Drills***

Karbonite & MKS drills stop working when loading to a vessel or exiting time warp, message on drills display "Must land first", have to manually re-activate each time to resume harvesting.

***Production***

Most production modules instantly produce their product. If you load to a vessel and hit produce rocket parts, metal, machinery, chemicals etc etc etc... It will instantly be produced to the maximum amount, however if the process was active before hand, the production will be gradual.

Two craft files, connect them together via KAS pipe or however, put 3x 3 star engineers into any parts of the vessel, have a lot of raw resources ready on standby, and activate any process in mobile refinery, any process in machinery plant, any process in aero module, any process in fabrication plant. All raw resources will be instantly converted.
https://www.dropbox.com/s/gbwlpeb432dgcmy/2.rar?dl=0
https://mega.co.nz/#!H4xFVBSI!stP30s9p3h_Xi6SyTPE0CZ8ZuuPmAq3SfncJjDHVTTI
Aeroponics instantly depletes all carbon dioxide for no oxygen yield if no Kerbal is inside the module or no inflatable agriculture module is present on the vessel

Looks like this issue persists to drills. Have all drills offline, time warp for a few days, then hit start drill, the raw resources tanks will fill instantly, but not necessarily full.

Crafted a 12,000 rocket part price tag vessel with 400 rocket parts, used up the first 400 rocket parts & had none left, activated a production chain of raw resources -> rocket parts and hit resume build on the craft, but for some reason the C3 module decided not to charge me the other 11.6 thousand. EL/Firespitter problem?

<del> Efficiency seems to be locked at  250% doesn't take into consideration of active modules on a vessel. (Tested this with 3x 3star engineers ~12 active processes, all at 250%.) </del>
After deflating all hab domes, efficiency went under 250%.

***Misc***

Occasionally unable to transfer resources from containers within a single vessel, no "in" "out" UI, reloading the vessel resolves the issue.

Kerbals on Eve trying to carry inflatible modules have 101% chance of exploding immediately and or falling through the ground.

2-5-15
------------------------------------------------
All 3 pioneering tanks act as probe cores, ILM, and storage tanks have probe core remote control functionality.

Error spam [Exception]: NullReferenceException: Object reference not set to an instance of an object
Causes or happens after crash landing a rover, can't switch vessels or exit to space center, alt-f4 only workaround.

**Comment by BobPalmer** [comment]
Closing as these are either fixed, stock'd, or on what is now a very old version of MKS
