### ISSUE TITLE
Drill Action Groups & Game Log Errors

### ISSUE THREAD

**Issue by Getsome2030** [BobPalmer/MKS#344]
A minor bug with the new version of MKS 0.22.6 and Karbonite 0.5.5 Drills? While configuring the action groups for the drills the dropdown list dis plays: e.g. "start Converter" "stop Converter" for all the minerals whereas in version MKS 0.22.3 and Karbonite 0.5.1 the dropdown list would show e.g. "start Minerals Drill" "stop Minerals Drill" and so on for all minerals.

Texture Errors - Example from MK3 Modules XML entry "texture = Decal_375_00_GLOW , UmbraSpaceIndustries/Kolonization/Assets/Decal_375_10_GLOW" The "Decal_375_00_GLOW" or the "Decal_375_10_GLOW" files do not exist in the Assets folder.

Here is an example of a common Error in the KSP Game Log:
LOG 23:24:58.837] PartLoader: Compiling Part 'UmbraSpaceIndustries/Kolonization/Parts/OKS_Workspace/OKS_Workspace'
[LOG 23:24:58.843] ERROR IN MKSModuleOnLoad - Object reference not set to an instance of an object
[ERR 23:24:58.844] Cannot find a PartModule of typename 'ModuleConnectedLivingSpace'

The 'ModuleConnectedLivingSpace' I do not have the Connected living Space mod installed and don't believe its necessary? I try to keep mods and parts to essential ones only as the more there are loading the more lag I experience in game. In saying that I feel that MKS and Karbonite parts should limit unnecessary module entries in there xml files so that we can enjoy your mods without having to get other mods. "Extraplanetary Launchpads" is an exception because it gives colonisation an extra purpose and expands on what you guys have achieved.

The 'MKSModuleOnLoad' Error I have no idea about?

Beyond that; I am really enjoying your mods thank you.

**Comment by Getsome2030** [comment]
I have been going through the log file eliminating some errors and discovered that the culprit for the 'MKSModuleOnLoad' Error is caused by the line "hasGenerators = false" by cancelling that line the error is gone. Example below from part MKS_HabDome 
MODULE 
{
	name = MKSModule
	workSpace = 2
	livingSpace = 0
	hasGenerators = false
}

**Comment by Famous-Shoes** [comment]
I'm also seeing the "ERROR in MKSModuleOnLoad".

Given what Getsome2030 wrote, it would seem either (or both) Fields["efficiency"] or Events["ToggleGovernor"] may be null; since Fields["Efficiency"] is capitalized elsewhere, that would get my vote to look at first. Also, those two values are checked for null before use elsewhere, so maybe should be checked here as well.

**Comment by RealKolago** [comment]
I am seeing this error in Kerbal initial load:

PartLoader: Compiling Part 'UmbraSpaceIndustries/Kolonization/Parts/MKS_HabDome/MKS_HabDome'
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

ERROR IN MKSModuleOnLoad - Object reference not set to an instance of an object

**Comment by BobPalmer** [comment]
Closing - different was already fixed, and converters/drills are stock
