### ISSUE TITLE
Akademy training issue

### ISSUE THREAD

**Issue by atrius129** [BobPalmer/MKS#346]
The Akademy doesn't seem to be working as advertised. I was taking it on a trip to Minmus to train a batch of new Kerbonaughts, a mixture of scientists engineers and pilots. Jeb, Bill, and Bob were all level 4s with all others level 1 or below. On the pad I hit the "train" button (don't remember the exact text), and everybody at level 0 went up to 1. This seems normal. However, upon taking off from Kerbin, at an altitude of about 10km , I hit the train button again and all of my scientists and engineers were promoted to level 4 and pilots to level 3. Jeb was in the cockpit at the time, separate from the Akademy. I still carried out the mission, landing on Minmus. Once there I had Jeb hop out and train the other pilots up to level 4 (even though he probably shouldn't have been able to get them that high). All other features of MKS/OKS are working perfectly for me.

**Comment by BobPalmer** [comment]
Fixed
