### ISSUE TITLE
OKS_Cap.cfg with support for FSfuelSwitch

### ISSUE THREAD

**Issue by msholly** [BobPalmer/MKS#349]
The "tank" on the OKS Cap is perfectly sized to have a RCS tank in there. The mesh already nicely fits quad RCS blocks, so I made a small change to my .cfg file to support FSfuelSwitch module. 

MODULE
    {
        name = FSfuelSwitch
        resourceNames = Structural;MonoPropellant
        resourceAmounts = 0;250
        basePartMass = 0.15
        tankMass = 0;0.038
        tankCost = 0;745
        displayCurrentTankCost = true
    }

Add it below the other MODULE in the .cfg file for anyone wondering where it goes. 

Not sure if the tank mass makes sense yet, feel free to change it. It would require you to support another mod as a dependency, but maybe someone here would like to add this to their game. 

Thanks for your hard work on all your mods!

**Comment by enceos** [comment]
Nice one! Finally these caps can have a purpose other than aesthetics.

**Comment by BobPalmer** [comment]
Done!
