### ISSUE TITLE
Feature request; Akademy function to change a kerbal's job

### ISSUE THREAD

**Issue by errolkokbas** [BobPalmer/MKS#352]
Ability to switch roles (and loose experience permanently) for a cost if an instructor is present in the new field.

**Comment by Kerbas-ad-astra** [comment]
Unfortunately, a Kerbal's job is linked to his name.  That said, Papa_Joe and the folks at Ship Manifest are tinkering with ways of adding non-displayed characters to a Kerbal's name to eventually get it to be the right job.
