### ISSUE TITLE
PDU-based Xenon generation

### ISSUE THREAD

**Issue by Cairan** [BobPalmer/MKS#355]
I've been re-reading on nuclear reactor operations, and I've got a suggestion to make concerning off-world xenon production.

Xe135 is a fission product, and during steady state operation, it almost always capture neutrons to turn into stable Xe136. It would be nice if the lab modules could extract xenon from an operating PDU, with yield dependent on the load factor of the reactor.

Quoting the Xenon-135 Wikipedia article:

The ultimate yield of xenon-135 from fission is 6.3%.

[...]

Iodine-135 is a fission product of uranium with a yield of about 6% (counting also the iodine-135 produced almost immediately from decay of fission-produced tellurium-135).[3] This 135I decays with a 6.57 hour half-life to 135Xe. Thus, in an operating nuclear reactor, 135Xe is being continuously produced. 135Xe has a very large neutron absorption cross-section, so in the high neutron flux environment of a nuclear reactor core, the 135Xe soon absorbs a neutron and becomes stable 136Xe. Thus, in about 50 hours, the 135Xe concentration reaches equilibrium where its creation by 135I decay is balanced with its destruction by neutron absorption.

[...]

Estimates of the proportion of 135Xe during steady-state reactor operation that captures a neutron include 90%,[6] 39%–91%[7] and "essentially all".[8] For instance, in a (somehow high) neutron flux of 1x10^14 n.cm-2.s-1, the xenon cross-section of σ=2.65x10-18 cm2 would lead to a capture probability of 2.65x10-4 s-1, which corresponds to a half-life of about one hour. Compared to the 9.17 half-life of 135Xe, this nearly ten-to-one ratio means that under such conditions, essentially all 135Xe would capture a neutron before decay. But if the neutron flux is lowered to one-tenth of this value, like in candu reactors, odds would be even, and half the 135Xe would be converted into 135Cs before capture.

**Comment by Cairan** [comment]
After a quick test and looking around various config files, I've made a Module Manager config which results in the Xenon production behaviour. It should only be a matter of changing the MKS_PDU and OKS_PDU RecipeOutputs  with the one I used in this MM Xe136.cfg:

@PART[MKS_PDU|OKS_PDU]
{
    @MODULE[KolonyConverter]{
        // Density of XenonGas is 50 times less than DU, and the Xe136 yield is set at 6.67%.
        //Thus, Xe = (EU - DU) * 50. It is painfully slow but accurate. If you want to break physics, use XenonGas value of 1.
        @RecipeOutputs = DepletedUranium, 0.0000070, True, XenonGas, 0.000025, True, ElectricCharge, 1500, False
    }
}

**Comment by BobPalmer** [comment]
Added
