### ISSUE TITLE
Feature request: Ground-based Logistics Hub

### ISSUE THREAD

**Issue by Falkvinge** [BobPalmer/MKS#357]
The Logistics Hub is a _wonderful_ invention, but that Logistics Hub in the VAB is obviously modelled for an orbital station. Would it be possible to add a ground-based model with those pretty supply drones, one that would fit better among the MKS Mk2/Mk3 buildings?

**Comment by Cairan** [comment]
It would also be nice to have the option of "ground shipping" at a ground speed of maybe 36 km/h (10 m/s) between two ground targets, with delivery time calculated on the great circle distance between the two points, when using a ground-based logistics hub.

**Comment by pectus-solentis** [comment]
http://imgur.com/GLhm0sZ
isn't it a nice adaption for Ground Logistic Hub?

**Comment by BobPalmer** [comment]
Ground shipping you already have - calculations are built in.  That one needs a model refresh anyway so I am not opposed to making the model a bit more generic.
