### ISSUE TITLE
Regolith conflict with KAS and Tweakscale

### ISSUE THREAD

**Issue by enceos** [BobPalmer/MKS#362]
I stumbled upon a gamebreaking bug which involves 3 mods: KAS, Regolith and TweakScale.

[Output_log.txt](https://www.dropbox.com/s/wkw1x38c4zcdqgt/output_log14.rar?dl=0)

When I take a scaleable part from a container TweakScale starts a log spam. The error is not present if I remove Regolith.dll from the install. Occurs in both this dev and 1.50 versions of Tweakscale.

[Youtube video](http://youtu.be/PWN_BI9m498)

If I let the error spam dwell long enough the game crashes.

**Comment by pellinor0** [comment]
This is out of date. The issue was fixed in TweakScale when Regolith was still a mod.
