### ISSUE TITLE
consumable RTGs

### ISSUE THREAD

**Issue by errolkokbas** [BobPalmer/MKS#366]
Could enriched uranium be added as a consumable resource to the RTGs when you get a chance?

**Comment by BFlatt85** [comment]
https://www.dropbox.com/s/9fv037aileyjx3i/DepleteableRTG.zip?dl=0

Link to ModuleManager config to make RTGs with Enriched Uranium.
Uses stock resource inputs so may be used with stock as long as you add the resource config in the zip.

**Comment by Cairan** [comment]
RTGs don't behave quite like this, their output goes down exponentially over time, but can't be refueled. What would be needed is a half-life module to reduce the electrical ouput (and consumption or radioisotopes?) based on the moment of launch/spawning and the current date. A lengthy discussion has taken place in the threads. For a recap and future discussion, a special thread was created. http://forum.kerbalspaceprogram.com/threads/111436-Eeloonium-A-glowing-extension-of-RoverDude-s-Kolonization-mod
