### ISSUE TITLE
PDU description does not match operational behaviour

### ISSUE THREAD

**Issue by Cairan** [BobPalmer/MKS#367]
The ingame description of MKS/OKS PDUs describes them as large RTGs. However, they consume EnrichedUranium proportionally to their load, and can be turned on and off. This is a fission nuclear reactor. Some users are confused with the operational difference of an RTG vs reactor. The ingame description should reflect that it is a small nuclear reactor instead of a large RTG.

**Comment by BobPalmer** [comment]
Wait... how out of date is your MKS version? ;)  Those descriptions have been gone for a while...

**Comment by Cairan** [comment]
Indeed, I was reporting other user's reports but upon examination of your ingame description, it does state "nuclear reactor" ... sorry.
