### ISSUE TITLE
Parts cost needs correcting for ILM #57 & ISM refining 2

### ISSUE THREAD

**Issue by AcidEric** [BobPalmer/MKS#368]
ILM no 57 (exotic minerals,rare metals, karbonite) is -1907 cost in SPH/VAB if emptied of resources
The same thing happens for the Inflatable storage module - Refining 2 (exotic minerals,rare metals, karbonite)

**Comment by tarheel1999** [comment]
Looking at the ILMs in the GitHub repo, it looks like all of the tank setups need the correct tank cost set (they are all set to 3500).

**Comment by BobPalmer** [comment]
Should be fixed in next release
