### ISSUE TITLE
Kerbal Akademy not providing stars

### ISSUE THREAD

**Issue by Nanderson423** [BobPalmer/MKS#369]
Using the akademy provides a message saying kerbals are being promoted, but the astronaut complex still shows them as having 0 stars.

**Comment by Joshwoo69** [comment]
NRE's? Or logs pls?

**Comment by tarheel1999** [comment]
This is consistent with my experience. Looking at the code, the Akademy updates the flight log but not the career log which is needed for the stars to register in the astronaut complex. This method might work fine for MKS (depending on which log MKS checks when calculating experience) but I believe it doesn't work with EPL.

**Comment by enceos** [comment]
Its true, I added the Kolonists extension which allows to "archive" the flight log into the career long an assign stars in situ.

**Comment by BobPalmer** [comment]
Sorted
