### ISSUE TITLE
Modules Popping Off of Base

### ISSUE THREAD

**Issue by rochieren** [BobPalmer/MKS#370]
Hi. I’m having an issue with the MKS Kolonization modules. I can get them built up like in the tutorial, however when I get them to a moon/planet I start running into problems.

For some reason, the modules will occasionally detach from the module base & pop off like a cork on a champagne bottle along with the rover wheels I’d attached for moving & lights I’d installed on the module base. I haven’t figured out what causes this issue and was hoping that you can give me some advice on how to fix it. If this keeps up I’ll be wasting time building & getting modules planet-side only to have modules uncouple and become useless once I get them there.

I've included a link to an uploaded screenshot showing my Aeroponics Module lying on its side after what was previously a successful landing, linking, and addition of four Inflatable Agriculture Modules.

https://www.dropbox.com/s/8gsqs3xg17wmkj3/screenshot14.png?dl=0

https://www.dropbox.com/s/dyb27z145qhiio1/screenshot15.png?dl=0

Thanks!

**Comment by BobPalmer** [comment]
Probably install or conflict issue as something is messing with the joints.  Not sure what to do with this one.

**Comment by rochieren** [comment]
I double checked the install instructions & followed them to the letter.  I'm going to try doing some experiments to see if something I'm doing while hooking up the connection tunnels might be forcing a glitch in the modules. I'll keep you advised.
