### ISSUE TITLE
Module Base has USI_ModuleFieldRepair instead of USI_ModuleResourceWarehouse

### ISSUE THREAD

**Issue by richardhendricks** [BobPalmer/MKS#373]
USI_ModuleFieldRepair allows for engineers to do a field repair, which isn't necessary as far as I can tell for the module bases (they don't consume any resources, only store them)
USI_ModuleResourceWarehouse is needed for storage locations that can provide spareparts for an engineer doing maintenance.  The Module Base can hold 5 SpareParts but can't distribute them.

**Comment by BobPalmer** [comment]
Fixed
