### ISSUE TITLE
MKS Storage Containers rocketparts not being drained by EPL 

### ISSUE THREAD

**Issue by richardhendricks** [BobPalmer/MKS#374]
When using EPL, it is not drawing down RocketParts from MKS storage containers.
![screenshot261](https://cloud.githubusercontent.com/assets/1214811/6385985/a194ff58-bd37-11e4-8542-dfe3655f0ee9.png)
![screenshot262](https://cloud.githubusercontent.com/assets/1214811/6385984/a192317e-bd37-11e4-80a8-d6ab37581a96.png)

**Comment by BobPalmer** [comment]
Too dark to see what's going on there.  Try with a radial tank attached directly to a workshop with no KAS tubes and see if the issue replicates.

**Comment by richardhendricks** [comment]
The thing to see is that the EPL counters have both decreased, but the RP stored in the drum has not.  I will retry in a sandbox tonight but this also matches my behavior when the drum is directly attached to an orbital spacedock.

**Comment by richardhendricks** [comment]
Test cases to try:
C3 with directly-attached radial tank
C3 with directly-attached Storage Tank
C3 with KAS-attached Storage Tank
C3 with KAS-attached Storage Tank with directly-attached radial tank

**Comment by richardhendricks** [comment]
Tested on 22.8 in a sandbox:
C3 with directly-attached radial tank - RP drains correctly.
C3 with directly-attached Storage Tank - RP drains correctly.
C3 with KAS-attached Storage Tank with directly-attached radial tank - RP drains correctly

Tested 22.8 in a career with previously-malfunctioning base:
Issue still exists.  During debug, interesting effect found.  Warping 1x to 50x did not change anything - parts did not drain from Storage Tank attached a couple of FlexOTubes away.  Warping to 100x and the parts started draining - parts continued to drain when warp went to 1x!  Switching to different vessel and back and parts continued to drain. Quitting to main menu and reloading, the base seems to continue draining rocketparts correctly.  Relaunching KSP from scratch, base seems to still correctly drain rocketparts, even with an older save(?).

**Comment by richardhendricks** [comment]
Mark this issue as cannot-reproduce.  Will keep an eye out if it pops up again.
