### ISSUE TITLE
Fuel Refinery not pushing to ILM on other side of Flexotubes

### ISSUE THREAD

**Issue by richardhendricks** [BobPalmer/MKS#380]
During buildout of my Kerbin base, noticed that my Fuel Refinery is not pushing out LFO or Monoprop (other outputs not tested), complaining about no space.  I did a test build in a sandbox game and verified the same issue is occurring.
I didn't see anything obvious in the source code/CFG files.

LFO ILM connected across flex-o-tubes:
![screenshot0](https://cloud.githubusercontent.com/assets/1214811/6429299/7c19403c-bf8e-11e4-80ed-05c565006926.png)

LFO ILM directly attached to Fuel Refinery, water ILM across flex-o-tubes:
![screenshot1](https://cloud.githubusercontent.com/assets/1214811/6429306/97bcf1ee-bf8e-11e4-9c8d-92b2c9e67ef7.png)

Other generators like metal/parts/machinery are properly outputting across flex-o-tubes.

**Comment by richardhendricks** [comment]
Save files provided on request

**Comment by BobPalmer** [comment]
This would be a KAS issue.
