### ISSUE TITLE
MKS Integrated Module Base does not have radial connection points?

### ISSUE THREAD

**Issue by WuphonsReach** [BobPalmer/MKS#381]
MKS_0.22.6.zip

When using the MKS Integrated Module Base in the VAB, there are only attachment nodes on the top/bottom.  The four radial 125cm plates around the sides do not have green attachment nodes.

**Comment by pectus-solentis** [comment]
Not of needs. You can attach docking ports or mks tubes despite of its having no attach points.

**Comment by BobPalmer** [comment]
That's correct - six way hubs are notoriously buggy.
