### ISSUE TITLE
How about making Mobile Repair Shop able to fabricate KAS gadgets?

### ISSUE THREAD

**Issue by pectus-solentis** [BobPalmer/MKS#382]
MRS being able to fabricate KAS Container contains ordered KAS gadgets using RocketParts or SpareParts or Recyclables (swichable on command) seems to very nice.

Before a couple of days I suggested it to EPL modder (to add tiny EPL which fabricates KAS gadgets) but it seems that KAS Fabricator is MUCH needed in MKS.

**Comment by smjjames** [comment]
Also, when KIS comes out, being able to manufacture the small gadgets there as well.

**Comment by pectus-solentis** [comment]
What stands for KIS?

**Comment by Kerbas-ad-astra** [comment]
Probably "Kerbal Inventory System" -- I've seen KospY mention it as an upcoming project now and then.

**Comment by enceos** [comment]
Guys, youre both missing out on a great mod called OSE Workshop: http://forum.kerbalspaceprogram.com/threads/108234-0-90-OSE-Workshop-KAS-Addon-%28v0-3-0-2015-02-20%29

You can just install the addon, delete the part and patch the desired MKS module with this:
  MODULE
  {
    name = OseModuleWorkshop
  }

**Comment by pectus-solentis** [comment]
That will be perfect if that get some amendment to be able to use SpareParts when ordered.

**Comment by smjjames** [comment]
THAT"S what I was trying to look for but just couldn't find. I knew I saw it before though.
