### ISSUE TITLE
Please update as he said.

### ISSUE THREAD

**Issue by pectus-solentis** [BobPalmer/MKS#383]
http://forum.kerbalspaceprogram.com/threads/79588-0-90-USI-Kolonization-Systems-%28MKS-OKS%29-%280-22-8%29-2015-02-27?p=1769889&viewfull=1#post1769889

I think his petition is fully reasonable.

**Comment by richardhendricks** [comment]
Pectus, for future reference this is not a great ticket submission.  Make sure the title clearly describes the issue.  Looking down a list of tickets nobody knows what this title means.
