### ISSUE TITLE
Consider switching drills to Mineral/Ore and Water/Substrate

### ISSUE THREAD

**Issue by tarheel1999** [BobPalmer/MKS#384]
In my admittedly limited play time with drilling operations it seems like you are most likely to see water and substrate in the same location and likewise for minerals and ore (in decent quantities at least). Consequently switching the drills in the save-breaking update for 1.0 might be a good idea. Also my OCD side feels like the  Water/Substrate and Minerals/Ore combos are more natural.

**Comment by BobPalmer** [comment]
Actually it's completely random for both :)  You may have just had an interesting seed in your game

**Comment by pectus-solentis** [comment]
I oppose your opinion. Mineral is hydro-soluble so Mineral's being excavated with water seems to be natural. And Ore, Substrate, Uraninite all of this 3 are non-soluble lithoids so these threes being excavated on same drill seems to be natural.
