### ISSUE TITLE
Uraninite can only be stored in Radial Tank

### ISSUE THREAD

**Issue by MarkSRobinson** [BobPalmer/MKS#396]
I was trying to find out how to extract uraninite and noticed I couldn't stored it anywhere.

It turns out that only the radial supply tank can store uraninite.

Objects that can't, but probably should be able to store tanks:
- Storage Tank
- Nuclear Fuel Bottle
- Inflatable Logistics Module
- Science Lab
- Inflatable Storage module

**Comment by WuphonsReach** [comment]
I agree, Uraninite is one of those things which the Storage Tank and Inflatable Storage Module should both be capable of holding.

**Comment by BobPalmer** [comment]
A consideration.  You need almost none of this stuff.  The ILM holds more than you would ever use, hence why it is in smaller tanks.

Date: Sun, 22 Mar 2015 10:06:18 -0700
