### ISSUE TITLE
Increase Storage Tank / Inflatable Storage Module FuelSwitch types

### ISSUE THREAD

**Issue by WuphonsReach** [BobPalmer/MKS#398]
Right now we have (for the STs and ISMs):

52 - Oxygen / Water / Food
53 - Waste / WasteWater / CarbonDioxide / Recyclables
54 - Compost / BioMass
55 - Water / Minerals / Ore / Substrate
56 - Metal / Chemicals / Polymers
57 - RareMetals / ExoticMinerals / Karbonite
58 - StructuralParts / ElectronicParts / MechanicalParts
59 - SpareParts / Machinery / RocketParts

Tank 55 should really be split into two separate tank numbers because the resources come from two different drill parts.  One for the MEU-500 outputs (40% Ore / 40% Substrate / 20% Uraninite) and one for the MEU-750 outputs (20% Water / 80% Minerals).  With the number balance adjusted to match the average recovery rate for the various resource types.

Tank 57 holding Karbonite in addition to RareMetals / ExoticMinerals is a really strange choice.  There should be another version of Tank 55 which holds just Karbonite by itself.

Tank 59 should be split into three tanks.  One for SpareParts, one for Machinery and one for RocketParts.  SpareParts are not transferable with pipes (only with EVA) so you typically ship up a load of SpareParts, dock it or land it and then it gets used up over a long period of time.  Machinery, OTOH, is something that you use a lot of right up front (if you launched the modules empty), then you use up slowly.  And RocketParts are in a world of their own.

You may also want to re-number the tanks:

41 - Water / Minerals
42 - Ore / Substrate / Uraninite
43 - Karbonite

52 - Oxygen / Water / Food
53 - Waste / WasteWater / CarbonDioxide / Recyclables
54 - Compost / BioMass

61 - Metal / Chemicals / Polymers
63 - RareMetals / ExoticMinerals
65 - StructuralParts / ElectronicParts / MechanicalParts
66 - RocketParts

71 - SpareParts
72 - Machinery

**Comment by pectus-solentis** [comment]
Agree. But ore/mineral is highly expendable while uraninite is rarely expandable. I think that uraninite should have its own tank that store uraninite/EU/DU.

**Comment by BobPalmer** [comment]
Closing due to the tank overhaul of 1.0
