### ISSUE TITLE
Add a 1/3 sized Storage Tank option

### ISSUE THREAD

**Issue by WuphonsReach** [BobPalmer/MKS#399]
Sometimes the 1.25m dry mass of the 250cm Storage Tank is just too much.  For smaller bases/stations, I often want something smaller that is just 1/3 the capacity and 1/3 the dry mass.

**Comment by pectus-solentis** [comment]
Isn't there already Radial Supply Tank

**Comment by WuphonsReach** [comment]
Yes, but often ship design makes me desire an inline 250cm version instead of radials.

**Comment by BobPalmer** [comment]
There are now a few options.  Inline 1.25m and 2.5m kontainers/tanks as well as radial supply paks in the next release.
