### ISSUE TITLE
Request Inflatable Logistics Modules ignore ILMs in current vessel

### ISSUE THREAD

**Issue by richardhendricks** [BobPalmer/MKS#402]
When pulling resources into an ILM from remote ILMs, code should not scan ILMs attached to the current vessel.  This causes problems because empty local ILMs will draw down the one you are filling instead of pulling from the remote ILMs.  This doesn't always happen, but I see it most often when there are three ILMs on the base, with 1 remote ILM.  In this case, I have

Harvesting ILM, Harvesting ILM, Life Support ILM - Local Vessel

Harvesting ILM - Remote Vessel

right-click all three local ILMS, and redirect water to various ones.  You will see sometimes it pulls water from the remote, sometimes the destination ILM gets water stolen from it to feed the empty ones.

**Comment by richardhendricks** [comment]
Possible solution is to have ILMs honor the "stop flow" flag in the GUI.

**Comment by BobPalmer** [comment]
Closing as unclear, given ILMs will never self-transfer
