### ISSUE TITLE
Recyclables in Orbit not appearing in vessel storage 

### ISSUE THREAD

**Issue by K-re** [BobPalmer/MKS#403]
Scrap Parts is working properly, message, animation, &c.
Recyclables are not appearing in vessel Recyclables storage.
Scraped Parts are on the same "segment" of an assembled space station.

Scrap Parts to Recyclables do work correctly when on a planetery surface.
I have not tested when connect to an asteroid

**Comment by kaa253** [comment]
I have no idea if Langabi was correct but in

http://forum.kerbalspaceprogram.com/threads/79588-0-90-USI-Kolonization-Systems-%28MKS-OKS%29-%280-22-8%29-2015-02-27?p=1777049&viewfull=1#post1777049 

he mentions,

Line 272 of MKS/Source/KolonyTools/KolonyTools/ProxyLogistics.cs is "&& x.Landed", which I THINK restricts vessels available for transfers to those that are, well, landed.

Personally, I would like scrapping to work on orbit but I guess it might be considered as a feature that it doesn't.
