### ISSUE TITLE
Nuclear Fuel Bottle cannot transfer eU or dU

### ISSUE THREAD

**Issue by richardhendricks** [BobPalmer/MKS#410]
Nuclear Fuel Bottle is not marked as a USI_ModuleResourceWarehouse, so you cannot pull/push U/dU to it with maintenance on the PDU.

Also, because maintenance cannot be done on the NFB, dU cannot be pulled out of it into a Science Lab.

**Comment by BobPalmer** [comment]
Will be deprecated with NFE integration
