### ISSUE TITLE
Have separate tank for SpareParts (from Machinery and RocketParts)

### ISSUE THREAD

**Issue by richardhendricks** [BobPalmer/MKS#412]
Since SpareParts is not flowable, when I put 4 kerbals into the MRS, it transfers all the spare parts to the first container that can accept them. Since I have a bunch of Storage Tanks attached to store Rocketparts and Machinery, this means those need to be full before I get any SpareParts into the Pioneers on a new station built with EL. Just something to noodle over, for now I built the new station C3/etc with full parts, and one of the pioneers on the station I loaded with SpareParts in the VAB, but I want to fill all the pioneers with spareparts before departing.

**Comment by BobPalmer** [comment]
Spare parts are deprecated
