### ISSUE TITLE
No activation buttons on modules

### ISSUE THREAD

**Issue by emfleck** [BobPalmer/MKS#415]
Seen this issue before with other users on older versions.  Took a break from the game and came back and updated the MKS module from a previous version.  Tried 22.8 and 22.9 and the OKS and MKS modules (with kerbals and proper machinery) doesn't show the activate button.  It says it is operational but it's not actually doing anything (from PDU no  power is being generated).

![screenshot1](https://cloud.githubusercontent.com/assets/12010951/7216853/a0a3ad02-e5db-11e4-86e0-cc303c5d7aa2.png)

**Comment by emfleck** [comment]
Have an update, in the VAB the submenus do not show the converters in the extra content.

![screenshot2](https://cloud.githubusercontent.com/assets/12010951/7220073/23add418-e689-11e4-99a8-03357c24466b.png)

**Comment by futrtrubl** [comment]
Make sure you have the latest regolith and have installed everything in the correct locations.

**Comment by emfleck** [comment]
I wiped everything out and did a fresh install of all the components in the zip folder.  No change.

**Comment by futrtrubl** [comment]
If KSP is installed inside of program files folder move it outside and try again. Also really check that you have the latest regolith, don't just re-install what you had before.

**Comment by emfleck** [comment]
I downloaded the separate regolith zip and used that to put into the gamedata folder.  Seems to be up and running again now!  Thanks.
