### ISSUE TITLE
Idea for new module using Extra Planetary Launchpads plugin offworld plane hanger

### ISSUE THREAD

**Issue by stevenj61** [BobPalmer/MKS#418]
Roverdude,

Have you considered making a off world space plane hanger using EPL for making space planes? I know the launchpad can build planes but the issue is that it sits really high off the ground so it's hard to wheel craft off the mobile launch pad without first making a large rover that acts as a platform vehicle or some sort of large extension using large structural plates on the side of it.

Regards,

stevenJ

**Comment by futrtrubl** [comment]
Use the survey stakes.

**Comment by stevenj61** [comment]
I'll look for that part thanks
