### ISSUE TITLE
MKS parts not showing up in VAB/SPH

### ISSUE THREAD

**Issue by Kootrasman** [BobPalmer/MKS#419]
So I downloaded MKS and the parts aren't showing up in my VAB/SPH when I launch KSP I see it load the MKS mod up but the parts don't show... I have tried a few things to fix it such as re-installing it, re-downloading it. and It still won't solve the problem. I have the most recent version of KSP and MKS. 
If you need any other info just say and I will do my best to supply it! Thanks!

~Koot

**Comment by futrtrubl** [comment]
Make sure you installed EXACTLY how it is laid out in the zip, do not move things. Also if KSP is installed in program files move it somewhere else, but that usually has the parts but they don't work.

**Comment by Kootrasman** [comment]
Well I have my KSP downloaded Via steam so it. Basically has to be in program files, also I don't drag things into Gamedata because I have multiple mods, MKS, Freight transport, karbonite, and people said that if I just drag the game data thing into my gamedata it glitches out.

**Comment by Kootrasman** [comment]
I'm not very good with computers,

**Comment by forsaken1111** [comment]
That's not true at all. You can tell steam where to install games, and you can move the KSP folder manually and it will work fine.

**Comment by Kootrasman** [comment]
Where do I put the mod folder? Do I drag the folder itself or just the stuff inside if it? Do I replace "gamedata"? Or do I move it to the mods folder?

**Comment by BobPalmer** [comment]
Hit up the forum thread for these so more folks can help you
