### ISSUE TITLE
Orbital Shipyard breaks RemoteTech

### ISSUE THREAD

**Issue by geoffromer** [BobPalmer/MKS#421]
To reproduce: with MKS and RemoteTech installed, build a ship consisting of an Orbital Shipyard with a probe core on the bottom and an active antenna, and remove all crew. Launch it, open the RT flight computer, select ">>", and note the "Status: Out of Power" in the lower center. Right click on the Shipyard and try selecting "Lights On" (or interacting with the ship in pretty much any other way), and "No connection to send command on" appears in the upper left.

According to a [discussion](http://forum.kerbalspaceprogram.com/threads/83305-0-90-0-RemoteTech-v1-6-3-2015-02-06?p=1581096&viewfull=1#post1581096) in the forums, RT chooses the first part it can find that has `ModuleSPU` to be the "master" SPU for the ship. If that part isn't able to control the ship (e.g. it has no crew, but `minimumCrew` > 0 like the Shipyard), RT can't control the ship.

I've verified that setting `minimumCrew = 0` in `MKS_EL_OrbDock.cfg` fixes the problem. I assume updating `MKS_OKS_RT2.cfg` to avoid adding `ModuleSPU` to the Shipyard would also work, but dropping the crew requirement seems more consistent with the rest of MKS.

**Comment by BobPalmer** [comment]
Should be fixed - removed command capability
