### ISSUE TITLE
Have you considered making a new category for your parts?

### ISSUE THREAD

**Issue by zanderzhng** [BobPalmer/MKS#423]
![screen shot 2015-04-28 at 13 50 18](https://cloud.githubusercontent.com/assets/867749/7362988/8a2af358-edad-11e4-8f9b-9a0c4276a7b8.png)
A new category like this the Infernal Robotics did. It's very convenient.

**Comment by BobPalmer** [comment]
If someone tosses a pull request I will happily include it :)

**Comment by calebmennen** [comment]
I would definitely suggest this, as I thought I had installed it wrong at first, because I had trouble finding the parts

**Comment by ToxicFrog** [comment]
Wait, this is possible? I just assumed it wasn't because so many mods that could really benefit from it don't do it.

Can it be done via MM, or does it require C#?

**Comment by futrtrubl** [comment]
It requires C#. To be honest I am surprised no one has created a mod to expose it via configs.

**Comment by Kerbas-ad-astra** [comment]
["A mod to expose it via configs"](http://forum.kerbalspaceprogram.com/threads/104231-1-0-x-Filter-Extensions-2-1-1-%28May-6%29-Numeric-Comparison), eh?

(When I get some time, I'm happy to put together a config and icon that sets one up, unless someone else beats me to the punch.)

**Comment by futrtrubl** [comment]
Oh I didn't know Filter Extentions allowed you to add new categories like KIS and IR and RealChutes. I only thought it, you know, extended filters ;']

**Comment by zanderzhng** [comment]
https://github.com/MagicSmokeIndustries/InfernalRobotics/blob/develop/InfernalRobotics/InfernalRobotics/Gui/EditorCategory.cs
this might help?

**Comment by Kerbas-ad-astra** [comment]
Now that I've been working more with USI stuff and Filter Extensions, I see that Filter Extensions actually makes a USI category already.  It's a real "category", though, not a subcategory of Filter by Function like Infernal Robotics makes.
![usi category by filter extension](https://cloud.githubusercontent.com/assets/9631860/7696773/86a3884a-fdce-11e4-8b0f-5b98f14eb266.png)

**Comment by zanderzhng** [comment]
That's actually better, since u can make subcategory according to part's functions and types.

**Comment by mhoram-kerbin** [comment]
In 0.31.6 the UKS-parts are in separate categories, so I believe this issue can be closed.
