### ISSUE TITLE
Things wont deflate and weird placing issues

### ISSUE THREAD

**Issue by WaviestMetal** [BobPalmer/MKS#427]
I tried to make a basic orbital colony to start a ship but when creating it in 1.0 (worked in 0.90) the placement of inflatable orbital habitat and orbital greenhouse was really finicky and wouldnt place on some parts, also when i put it on in the vab it automatically inflates and i cant get it to deflate to put ferrings around it to be able to fly it. when i launch it i also cannot deflate it. Is this a bug or did i install the mod wrong (i just dragged the whole umbra space industries folder into my game data)

**Comment by WaviestMetal** [comment]
i must mention i only have the mks mod and tacls currently, is there other necesary ones to get it to work

**Comment by Joshwoo69** [comment]
You mighr be mossig something like.. 000_usitools

**Comment by WaviestMetal** [comment]
EDIT: i figured out the problem i didnt have the whole mod installed
