### ISSUE TITLE
Typo in MKS_LogisticsHub.cfg

### ISSUE THREAD

**Issue by RealKolago** [BobPalmer/MKS#429]
(MKS_0.30.0) (Kerbal 1.0.2)

PartLoader: Compiling Part 'UmbraSpaceIndustries/Kolonization/Parts/MKS_LogisticsHub/MKS_LogisticsHub'
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

PartLoader Warning: Variable crewCapacity not found in Part

Entry crewCapacity = 0 shut be CrewCapacity = 2

**Comment by BobPalmer** [comment]
Fixed in next release
