### ISSUE TITLE
hasGenerators = false results in "ERROR IN MKSModuleOnLoad"

### ISSUE THREAD

**Issue by RealKolago** [BobPalmer/MKS#431]
This error is in the log for MKS_HabDome, MKS_Workspace, OKS_HabRing and OKS_Workspace:

PartLoader: Compiling Part 'UmbraSpaceIndustries/Kolonization/Parts/MKS_Workspace/MKS_Workspace'
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

ERROR IN MKSModuleOnLoad - Object reference not set to an instance of an object

**Comment by BobPalmer** [comment]
Fixed in next patch
