### ISSUE TITLE
Inflatable modules do not fit in the MKS KIS inventories. Inflated volume is being used?

### ISSUE THREAD

**Issue by sondreutheim** [BobPalmer/MKS#435]
The UKS module base has a 50L capacity, while each Kerbitat seat, Pioneer seat etc.. has a 300L capacity. Neither have enough space to hold:
UKS Ag module ( 52 023L )
UKS Hab module ( 110 192L )
FlexoTube ( 1912L )

A part that has about the same proportions as for example the Ag Module is the 1.25m service bay, which ticks in at 1155.33L, so it seems the inflated volume is being used for the modules, but is this a problem with KIS or with MKS?

**Comment by futrtrubl** [comment]
See pull request https://github.com/BobPalmer/MKS/pull/434 which should fix this.

**Comment by BobPalmer** [comment]
Fixed in next release
