### ISSUE TITLE
KSP-AVC complains about bundled USI Tools

### ISSUE THREAD

**Issue by geoffromer** [BobPalmer/MKS#440]
With USI Tools 0.4.0 (which is bundled with MKS 0.30.1) and KSP 1.0.2, KSP-AVC is complaining that "the currently installed version of USI Tools was built to run on KSP 1.0", presumably because USI.version specifies a max KSP version of 1.0.0. According to the forum, there's no real compatibility issue, but the notification is annoying.

**Comment by geoffromer** [comment]
"...presumably because USI.version specifies a max KSP version of 1.0.0."

I take that part back, because I manually fixed USI.version and I'm still getting the alert. I guess I'll leave the diagnosis to someone who knows what they're talking about.

**Comment by Neouni** [comment]
If you check your log, AVC is smarter then that:
"Identical remote version found: Using remote version information only"
might work if you increase the patch number by 1

**Comment by BobPalmer** [comment]
Fixed in next release
