### ISSUE TITLE
Pioneer greenhouse seems underpowered

### ISSUE THREAD

**Issue by robert-cassidy** [BobPalmer/MKS#443]
Pioneer greenhouse consumes 0.0002 mulch/s and produces 0.0001 supplies/s. Assuming 2 kerbals working the module, they will consume 0.001 supplies/s and produce 0.001 mulch. 

The module would need to work at 500% efficiency just to consume as much mulch as the two workers produce (let alone anyone else on the station) and would need to work at 1000% efficiency to produce as much supplies as those two workers need. 

The greenhouse in USI-LS, which converts 0.0005 mulch/s and produces 0.00025 supplies, will remove 1 kerbals worth or mulch but does so without dedicating a worker. There's literally no point to running the Pioneer greenhouse at this ratio. Plus the fact it consumes 6EU/s vs 3EU/s in the greenhouse, plus it consumes machinery. 

Assuming a 250% efficiency, a Pioneer might be better balanced if it consumed 0.006 mulch and produced 0.003 supplies. That would be  0.0024 mulch/0.0012 supplies baseline. At 250%, those two kerbals would not only process their own mulch, but that of 10 other kerbals, which sounds more reasonable. EC could scale up somewhat, though that would be 72EU/s which seems excessive. 

At that scale, the Pioneer would process 12 kerbals in 3.75t, plus the cost of EU production and the cost of supplying machinery vs needing 18t of greenhouses, plus the cost of EU production, but no need for kerbals to man them. That would make it attractive to convert from greenhouses to pioneers somewhere above 4 kerbals. Above 12 kerbals, an aero/kerbitat should be the preferred solution. When building a large station, pioneer would be a suitable boostrap, which is what I believe it's intending to be.

**Comment by robert-cassidy** [comment]
Followup:

I built a station sitting at the launchpad with 2 hab rings, 2 workshops, 2 ag, 1 aero, 1 kerbitat, 1 PDU, 1 pioneer, with some storage for mulch. Everything inflated. This is in 0.30.2.

1) There's no mulch storage in the pioneer. That seems like an oversight. 
2) With 2 level 5 engineers in each of the kerbitat and aero, and PDU, ag greenhouse and habitat running, it still couldn't keep up with the mulch produced by 4 kerbals. That was at 1250% efficiency, with the greenhouse running at 125% load and the habitat at 56% load. 
3) The resource panel doesn't account for the kerbals, so it shows that supplies is increasing, even though the kerbals are consuming more than the station is producing. Not sure if that's an oversight, but it should probably be clarified with a gross/net kind of display. 
4) When I turn those off and move the engineers to the pioneer and turn on that greenhouse, mulch also continues to increase. The panel says it's consuming 10.8 per day, which should be more than double what 4 kerbals produce (4.32 per day) but mulch keeps going up. It's showing 250% efficiency, 25% load. So, at the very least it's not functioning as I would expect it to.

**Comment by robert-cassidy** [comment]
Running the same base but with full machine parts on all modules. 4 kerbals should produce 4.32 mulch per day, but the resource display says that 13.5 are being consumed (3125% more). I can't even square that with the 1250% efficiency. The aeroponics says it's at 400% load, which makes sense:

Consumes mulch at -0.00005/s = -1.08/day at 100% efficiency, so it's consuming at 400% of baseline load and the 1250% efficiency means it could go to 1250% if enough mulch was provided. So far so good in terms of what's actually happening. It's turning out 3.888 organics/ day. What's displaying on the resource panel is bananapants, though.

The Kerbitat can consume 0.0001 organics/s or 2.16/day at baseline. It's constrained at 3.888 because that's all the aero puts out, which is 180% load, but it could go to 1250%. It's putting out 3.888 supplies/day, and the conversion is therefore 90% efficient. (Here's where the documentation gets difficult because we have two efficiencies - one is _economic efficiency_ of the conversion, and the other is the _workload efficiency_ of the converter itself. I'll try and make that abundantly clear on the wiki.)

My resource panel is showing on the balance screen:
* -13.5 mulch per day
* 27 supplies per day
* -14.85 organics per day

Not being entirely sure what you're trying to illustrate, what's actually happening on the ship:
* 0 mulch per day (aero is consuming it all)
* 0 organics per day (kerbitat is consuming it all)
* -0.44 supplies per day (net from the economy)

I think what's happening is that you're showing how much mulch the aero _could_ consume at it's 1250% efficiency. The kerbitat _could_ produce 27 supplies, and if those were both running at max, there'd be a deficiency of 14.85 organics between the two - I'd need 1.22 more aeros running at this rate to balance out the kerbitat. Problem is that the theoretical numbers are of limited utility and don't really tell you what's actually happening. Let me think about what would be clearer.

**Comment by robert-cassidy** [comment]
So, in terms of balance, I'm feeling good about the aeroponics/kerbitat setup mainly due to the overwhelming effect of the ag modules.

The Pioneer can clear 4 kerbals worth of mulch at 100%, or 10 worth at 250% (max theoretical). The problem is that it unlocks at tier 5, but the hab is tier 7/8 and the workshop is tier 7, and the pioneer is fighting the efficiency the whole way with a happiness stuck at 0.5, and you'll really have to spam modules (which you don't really have because they don't unlock until much later) to get enough workspaces going. At tier 5 you only have the Pioneer, so you can only run a station with two kerbals per Pioneer launched and have the greenhouse be useful. (workshop/crew = 0.5 * 1.125 for a level 3 engineer because happiness is stock at 0.5 - enough to cover two kerbals). You get the PDU at tier 6, which doubles that, provided the PDU isn't operating. Once you turn into, you're in even worse shape until you hit tier 7 and can bring up workshops and/or habs.

I think what the Pioneer needs is a small bootstrap inflatable which provides maybe 2 hab (hotbunk!) and 1 workspace and gives an efficiencyPart of 1 (or even 0.5) only to the Pioneer and have it unlock at tier 5. Then you'd have something...

**Comment by BobPalmer** [comment]
Sorted with the Mk-V modules in the next release.
