### ISSUE TITLE
Can't seem to set containers to hold mulch and\or supplies

### ISSUE THREAD

**Issue by Neouni** [BobPalmer/MKS#445]
Log shows
[WRN] Could not create PartResource of type 'Supplies
[WRN] Could not create PartResource of type 'Mulch

took a quick glance, couldn't find anything odd with the part.cfg

tested,
radialtank
oks ilm
mks ilm
octolander

**Comment by BobPalmer** [comment]
You probably need an updated CRP version.

**Comment by Neouni** [comment]
mulch and supplies aren't referenced anywhere in the current CRP build of 0.3.3 or the dev build of 0.4.2

**Comment by futrtrubl** [comment]
Mulch and supplies aren't part of CRP. They are defined in USI-LS.

**Comment by BobPalmer** [comment]
That too :)  Closing this as it's a support issue
