### ISSUE TITLE
Texture switching broken on OKS ILM, radial tank, and octo lander

### ISSUE THREAD

**Issue by ToxicFrog** [BobPalmer/MKS#448]
Specifically, the next/previous cargo buttons work and properly switch what resources it can contain, but the texture doesn't change. For the ILM, the "current texture" field is empty; for the other two, it displays the correct string but the actual texture on the model doesn't change.

The MKS ILM (which has linked cargo and texture switching) and OKS agricultural module (which only has texture switching) both work fine.

Repro: install KSP 1.0.2, install UKS through CKAN, go to the VAB, install the parts listed and switch their cargo.

**Comment by BobPalmer** [comment]
Fixed next release
