### ISSUE TITLE
30.2 release file contains 30.1 part files and version file update

### ISSUE THREAD

**Issue by Tebryn** [BobPalmer/MKS#453]
30.2 release zip https://github.com/BobPalmer/MKS/releases/download/0.30.2/MKS_0.30.2.zip
 UmbraSpaceIndustries\Kolanization\parts folder contains old 30.1 files without any 30.2 updates. 

Other folders don't seem to be affected. 

30.2 release Source Zip and tar.gz files contain correct files for this release.

And MKS.version file got missed in the update to 30.2
https://github.com/BobPalmer/MKS/blob/master/GameData/UmbraSpaceIndustries/Kolonization/MKS.version#L13

**Comment by BobPalmer** [comment]
Fixed in next release
