### ISSUE TITLE
New Kontainers dry mass is unreasonably heavy.

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/MKS#466]
I wonder if maybe you forgot a decimal because seriously, 52 tons dry mass??

Forum post: http://forum.kerbalspaceprogram.com/threads/79588-1-0-2-USI-Kolonization-Systems-%28MKS-OKS%29-%280-30-3%29-2015-05-22?p=1962924&viewfull=1#post1962924

**Comment by skbernard** [comment]
Roverdude confirmed mass should be set to the following for tanks 0.4/3.2/10.4

http://forum.kerbalspaceprogram.com/threads/79588-1-0-2-USI-Kolonization-Systems-%28MKS-OKS%29-%280-30-3%29-2015-05-22?p=1963032&viewfull=1#post1963032
