### ISSUE TITLE
Request: Add liquidfuel only and oxidizer only (to keep it consistent with liquidfuel only) options to the wet tanks?

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/MKS#469]
SInce the nuke engines from stock and other mods use liquidfuel only now, I thought it would be good to have that option available to use.

I also thought maybe add monoprop, but changed my mind since it would be quite a lot of monoprop in the two larger tanks. The smallest size tank, maybe.

**Comment by Deadpan110** [comment]
I think Monoprop would be a good option for all sizes as well as single LiquidFuel and Oxidizer setups.
I often create stations that craft dock with and always end up forgetting to send up more Monoprop so as to refuel the worker crafts.
No big deal for my Mun and Minmus operations - but would be handy to keep a large amount in stock while trying to colonize the Jool system before I have facilities to replenish resources,

**Comment by BobPalmer** [comment]
LiquidFuel has been added - MonoProp makes sense.  Not sure how I feel about an Oxidizer-only tank.

**Comment by smjjames** [comment]
I was iffy on the oxidizer only myself. Interstellar fuel switch makes oxidizer only an option for some tanks anyway.

**Comment by BobPalmer** [comment]
Added LF and Mono tanks
