### ISSUE TITLE
TAC-LS configuration MM settings file has incorrect values

### ISSUE THREAD

**Issue by Marcafk** [BobPalmer/MKS#475]
With USI LS the pioneer take in the waste of 4 kerbals, and makes enough supplies for 2, with TAC it takes in the waste of 4 and produces enough for 1.
 With USI LS the Kerbitat takes in organics and makes equal amounts of supplies, enough for 2 kerbals. With TAC the Kerbitat takes in the same amount of organics, but only produces enough food, oxygen and water for 1 Kerbal.
 Effectively using TAC halves your life support at the moment, the 90% from Aeroponics becomes 45% efficiency and the pioneer gives you 25%. 
Correct values should be the following for both Pioneer and Kerbitat output:
		OUTPUT_RESOURCE
		{
			ResourceName = Food
			Ratio =  0.000033854166666
			DumpExcess = False
		}
		OUTPUT_RESOURCE
		{
			ResourceName = Water
			Ratio =	0.000022376157408
			DumpExcess = False
		}
		OUTPUT_RESOURCE
		{
			ResourceName = Oxygen
			Ratio = 0.00342707512477
			DumpExcess = False
		}

**Comment by OakTree42** [comment]
Current version lacks any data for the new parts, meaning they still store supplies and not any of the TAC items.

**Comment by BobPalmer** [comment]
Fixed in next patch
