### ISSUE TITLE
Bug - Kolony tools GUI generates errors in log

### ISSUE THREAD

**Issue by kaa253** [BobPalmer/MKS#480]
Almost any time I open the Kolony tools GUI I get a few errors in the log. These seem to be mostly harmless. 
If I include a Nom-O-Matic 5000 on my craft and click on the Kolony tools button I get error log spam. If I click on the "parts" button I get a GUI window crash/lockup.

HowTo reproduce? Attach a Nom-O-Matic to any command pod and launch. Open Kolony tools GUI and click on the parts button. I have lots of mods. If you cannot reproduce I may be able to find time to investigate if it is a cross-mod interaction.

I think, http://forum.kerbalspaceprogram.com/threads/79588-1-0-2-USI-Kolonization-Systems-%28MKS-OKS%29-%280-30-3%29-2015-05-22?p=1937469&viewfull=1#post1937469 is the same issue.

**Comment by BobPalmer** [comment]
Corrected in next release
