### ISSUE TITLE
Empty Kontainer Cost

### ISSUE THREAD

**Issue by Donziboy2** [BobPalmer/MKS#482]
Was playing with the Kontainer and noticed the Rocketpart Version was very expensive, empty it costs about 4.45M,  I think that is a little expensive for an empty box.......

MODULE
{
  name = FSfuelSwitch
  resourceNames = MetallicOre;Water;Substrate;Minerals;Karbonite;LiquidFuel,Oxidizer;RocketParts;Metals;Chemicals;Polymers
  resourceAmounts =        67500;67500;67500;67500;67500;6075,7425;13500;67500;67500;67500
  initialResourceAmounts = 0;0;0;0;0;0,0;0;0;0;0
  tankCost = 47250;54;20250;54000;21600;6200;67500;945000;1080000;540000
  basePartMass = 0.75
  tankMass = 0;0;0;0;0;0;0;0;0;0
  hasGUI = false
}

}

**Comment by Donziboy2** [comment]
Opps, its FTT and looks like more then 1 resource is broken.....

**Comment by BobPalmer** [comment]
FTT parts are being deprecated so closing this
