### ISSUE TITLE
UKS Fuel Refinery cost wrong

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#486]
Currently the UKS Fuel Refinery base cost is listed as 3,160, but when put in the VAB it actually costs -890,280. Now the first cost strikes me as a wee bit low but the second one seems to be a bug?

Also the UKS Fabrication module lists cost at 65k and in VAB shows as 22,560.

**Comment by BobPalmer** [comment]
Fixed for next patch
