### ISSUE TITLE
Stock junk retrieval contract giga-spams the log

### ISSUE THREAD

**Issue by AlonzoTG** [BobPalmer/MKS#490]
When Gene Kerman issues a junk retreival contract, he spawns a completely random part. When that part is a MKS/OKS part with a kolony konverter, the part is not initiated correctly and spams the log as hard as the CPU capacity allows as soon as the salvage ship is within range, up to 6,000 times a second on my machine. 

It was difficult to grab the output because it was scrolling so fast, I had to put the game on pause to slow it down enough to grab anything... 

Can't provide a screenshot of exactly what it is because the framerate drops to 0 and the game crashes as I approach it. =\

'
[WRN 23:29:19.181] Part already contains resource 'ElectricCharge'
[EXC 23:29:19.196] FieldAccessException: Cannot set a constant field
        System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture)
        System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value)
        ProtoPartSnapshot.Load (.Vessel vesselRef, Boolean loadAsRootPart)
        ProtoVessel.LoadObjects ()
        Vessel.Load ()
        Vessel.Update ()
[EXC 23:29:19.198] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[EXC 23:29:19.198] NullReferenceException: Object reference not set to an instance of an object
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.SetupICrossSectionAdjusters ()
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.Start ()
[EXC 23:29:19.198] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[WRN 23:29:19.589] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:29:19.597] Part already contains resource 'Machinery'
[WRN 23:29:19.597] Part already contains resource 'Recyclables'
[WRN 23:29:19.597] Part already contains resource 'ElectricCharge'
[EXC 23:29:19.611] FieldAccessException: Cannot set a constant field
        System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture)
        System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value)
        ProtoPartSnapshot.Load (.Vessel vesselRef, Boolean loadAsRootPart)
        ProtoVessel.LoadObjects ()
        Vessel.Load ()
        Vessel.Update ()
[EXC 23:29:19.614] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[EXC 23:29:19.614] NullReferenceException: Object reference not set to an instance of an object
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.SetupICrossSectionAdjusters ()
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.Start ()
[EXC 23:29:19.614] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[WRN 23:29:20.260] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:29:20.268] Part already contains resource 'Machinery'
[WRN 23:29:20.268] Part already contains resource 'Recyclables'
[WRN 23:29:20.268] Part already contains resource 'ElectricCharge'
[EXC 23:29:20.283] FieldAccessException: Cannot set a constant field
        System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture)
        System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value)
        ProtoPartSnapshot.Load (.Vessel vesselRef, Boolean loadAsRootPart)
        ProtoVessel.LoadObjects ()
        Vessel.Load ()
        Vessel.Update ()
[EXC 23:29:20.286] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[EXC 23:29:20.286] NullReferenceException: Object reference not set to an instance of an object
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.SetupICrossSectionAdjusters ()
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.Start ()
[EXC 23:29:20.286] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[WRN 23:29:20.677] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:29:20.686] Part already contains resource 'Machinery'
[WRN 23:29:20.686] Part already contains resource 'Recyclables'
[WRN 23:29:20.686] Part already contains resource 'ElectricCharge'
[EXC 23:29:20.703] FieldAccessException: Cannot set a constant field
        System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture)
        System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value)
        ProtoPartSnapshot.Load (.Vessel vesselRef, Boolean loadAsRootPart)
        ProtoVessel.LoadObjects ()
        Vessel.Load ()
        Vessel.Update ()
[EXC 23:29:20.706] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[EXC 23:29:20.706] NullReferenceException: Object reference not set to an instance of an object
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.SetupICrossSectionAdjusters ()
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.Start ()
[EXC 23:29:20.706] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[WRN 23:29:21.098] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:29:21.106] Part already contains resource 'Machinery'
[WRN 23:29:21.106] Part already contains resource 'Recyclables'
[WRN 23:29:21.106] Part already contains resource 'ElectricCharge'
[EXC 23:29:21.121] FieldAccessException: Cannot set a constant field
        System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture)
        System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value)
        ProtoPartSnapshot.Load (.Vessel vesselRef, Boolean loadAsRootPart)
        ProtoVessel.LoadObjects ()
        Vessel.Load ()
        Vessel.Update ()
[EXC 23:29:21.123] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[EXC 23:29:21.124] NullReferenceException: Object reference not set to an instance of an object
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.SetupICrossSectionAdjusters ()
        FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.Start ()
[EXC 23:29:21.124] NullReferenceException: Object reference not set to an instance of an object
        Part.ModulesOnStart ()
        Part+.MoveNext ()
[WRN 23:29:21.508] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 23:29:21.516] Part already contains resource 'Machinery'

**Comment by BobPalmer** [comment]
Your MKS version is out of date.  Use 0.30.4
