### ISSUE TITLE
UKS Fuel Refinery says LFO is full

### ISSUE THREAD

**Issue by chrissnave** [BobPalmer/MKS#491]
I'm sure I'm doing something wrong but this doesn't seem right to me. I recently added a UKS Fuel Refinery to my Mun base, made sure I had some water then tried to make some LFO. The refinery module is reporting "LFO: LiquidFuel full" even though I have an empty LiquidFuel/Oxidizer/Karbonite Inflatable Logistics Module connected. I've even tried attaching an empty LFO fuel tank to the refinery with the same result. Please advise.

KSP 1.0.2
UKS 0.3.04
Karbonite 0.6.2
K+ 0.4.1
FTT 0.4.1
Exploration Pack 0.4.1
Regolith 0.1.7
KIS 1.1.4
KAS 0.5.1
![screenshot590](https://cloud.githubusercontent.com/assets/12790092/8027275/b0ee4a4c-0d62-11e5-86a9-cbaa7898effc.png)

**Comment by chrissnave** [comment]
This Mun base is practice for Duna where I'd really like to be somewhat self sufficient & use a MKS base to fuel my missions there. Any idea why the refinery isn't seeing my fuel storage? Here's my gamedata folder if that helps...
![gamedata folder](https://cloud.githubusercontent.com/assets/12790092/8097348/1d58e432-0faf-11e5-979f-91870d500c62.jpg)

**Comment by futrtrubl** [comment]
Likely a fuel flow issue. Make sure everything has crossfeed enabled and your fuel pipes are going the correct way (from tanks to the converter).

**Comment by chrissnave** [comment]
THANK YOU!
Okay I took a look at my flex-o-tube settings, changed those all to "pump here". Now my refinery is finally happily making LFO & sending it to my storage.

I knew about the "pump here" options but always assumed that was for transferring stuff around manually. I have TAC fuel balancer so always used that instead. It didn't occur to me that setting is actually a shut-off valve of sorts (cross feed). Perhaps the default for flex-o-tubes should be valve open instead of closed? Anyway this is great, now I can get on with my Duna preparations. Much obliged.

![screenshot599](https://cloud.githubusercontent.com/assets/12790092/8098897/c59cb2b8-0fc3-11e5-9d62-f4bdb1c4b7cf.png)
