### ISSUE TITLE
Kontainers missing Machinery [v0.3.04]

### ISSUE THREAD

**Issue by Deadpan110** [BobPalmer/MKS#493]
As spotted in the [USI Kolonization Systems (MKS-OKS) KSP forum](http://forum.kerbalspaceprogram.com/threads/79588-1-0-2-USI-Kolonization-Systems-%28MKS-OKS%29-%280-30-3%29-2015-05-22?p=2004300&viewfull=1#post2004300), Kontainers are missing Machinery which makes it difficult to ship an initial supply to modules launched empty or built in-situ.

Related to:
#468 (Missing Recyclables)
#469 (extra selections for single Liquid Fuel, Oxidizer and Monoprop)

**Comment by BobPalmer** [comment]
Fixed in next release.
