### ISSUE TITLE
Quicksave load of an Engineer EVA'd with screwdriver leads to out of control spin

### ISSUE THREAD

**Issue by glennfu** [BobPalmer/MKS#499]
I've had this happen to me twice using the 0.30.4 release where I loaded a save where an engineer was standing still on the surface. This last time, I EVA'd my engineer, hopped to the ground, then took 1 flexo tube and a screwdriver from the inventory of the pod and transferred it to the inventory of my engineer. Then I hopped close to the module I planned on using it for, then quicksaved.

After that, I did a couple things, messed stuff up, and held F9 to load my last quicksave. Instantly, my engineer is spinning and bouncing out of control, and there's a 5'ish meter long V shaped pole sticking out of her spinning out of control with her. After a few moments, she disappears and my focus is switched to a nearby module. I go to the Space Center, and see something like "Sieselle Kerman could not be recovered... unknownPart".

What does this mean, and what do I do? If I go back to the module, Sieselle Kerman has been placed back into the original module, but now her inventory is empty so the screwdriver is gone.

**Comment by BobPalmer** [comment]
This sounds like a KIS issue, please take it up in that thread
