### ISSUE TITLE
Noms-o-Matic bugs the MKS info panel (Parts tab)

### ISSUE THREAD

**Issue by ForsakenOne** [BobPalmer/MKS#505]
Found an issue that i pinpointed to the noms-o-matic after quite a bit of testing: When having it installed on a vessel, opening the panel for the "Parts / Production / Consumption / Balance / Ressources", clicking on the "Part" tab this happens:
 ![2015-06-18_00005](https://cloud.githubusercontent.com/assets/12958474/8243669/2e1da260-15e7-11e5-943b-936290a5907e.jpg)

Log gets spammed with the same messages.

I set up the vessel with a decoupler, and when i do the same process with the noms-o-matic decoupled, all is fine. 

If you need any more info (pics/logs) i can provide. 

And thanks a lot for all the efforts you put into this :)

**Comment by BobPalmer** [comment]
Which MKS version?

**Comment by ForsakenOne** [comment]
Last public one, 30.3

**Comment by ForsakenOne** [comment]
Just tested with 0.31.1, and bug is not present. However, the production / consumption panel don't show the noms-o-matic resource flow.

**Comment by BobPalmer** [comment]
Nom-O-Matics are not MKS parts
