### ISSUE TITLE
MKV_Workshop Machinery Ratio

### ISSUE THREAD

**Issue by robert-cassidy** [BobPalmer/MKS#510]
Consumes 0.025 Metals, Chemicals, Polymers, SpecializedParts -> 1.0 Machinery. 

This seems a mismatch - with 0.1 mass going in and 1.0 mass coming out. Also doesn't seem to match your document:

Requires SpecializedParts (50% of the recipe)
Result is a 50% mass loss in shipping RocketParts/Machinery to a colony

**Comment by rabidninjawombat** [comment]
Can confirm, seems to just be an issue with an extra 0 in the forumla,   (Same deal for the RocketParts Conversion. )

The same formula on the Mk.3 Fab module, uses .25 Chem, Poly, Metals, SpecParts instead of .025

**Comment by BobPalmer** [comment]
Fixed in next release
