### ISSUE TITLE
MKV_ILM vs MKV_SupPak balance.

### ISSUE THREAD

**Issue by robert-cassidy** [BobPalmer/MKS#511]
ILM holds up to 17.5 metal vs Readi-Pak which holds 2500. Same for all resources. That seems reversed.

**Comment by SirSmurfalot** [comment]
Are you looking at the deflated stats on the ILM?  When you inflate it, the numbers go up.

**Comment by BobPalmer** [comment]
See above.  Quantity increases once inflated
