### ISSUE TITLE
TAC LS CFG not working quite right?

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#513]
Tried the modules, and first they still hold supplies and not any of the Tac elements (and mulch) and organics (Which I understand is the intermediate step between waste/organics/good) 

But more over supplies are still showing, and even with level five engineers and everything you could possibly need I'm finding the production rates to be very very low, as in with max time warp (and warping very long times) I think I made 1 total food. It was going up slower than xeon gas production. So... suspect either  I am doing something wrong or the values in the tac cfg need to still be tweaked upwards some. I understand in a closed system it will have loss but the issue seems to be tied to the production rate from organics back into water/food/o2 which means no matter how much water/substrate I add to get organics I still hit that conversion wall?

Edit: I have added massive substrate, water and fertalizer and tried a bunch of combinations of other things and no matter what I do, even with level 5 engineers the best I can manage on the system is an over-abundance of organics and just /barely/ a net positive on life support, meaning I time accelerated a year and got something like a couple of food at best. I understand it is supposed to be hard to grow 'excess' but with everything at max and with max engineers scientists etc it leads me to believe that outside of sandbox these numbers may lead to not just a hard time reaching balance but nearly impossible? There was a thread with some updated Tac LS numbers for balancing that was closed. From what I can see the updated Tac CFG did not incorporate the new numbers? Unsure but that appears to be the initial check I got. So while the new CFG does at least make the system work some what with TAC it has the same issues that were reported in: https://github.com/BobPalmer/MKS/issues/475

Hope this testing helps! I really want to be able to use the MKS/OKS with Tac if possible.

**Comment by OakTree42** [comment]
New News - Also discovered a few things, for one the MK-V Agricultural agroponics needs mulch but I have no way to make mulch in Tac at the moment. 

Additionally the Aeroponics MKS has 2 separate greenhouse buttons that seem to have separate math on them now.

**Comment by BobPalmer** [comment]
Fixed in next patch... maybe.  Let me know if it's still broke.

The extra resources will not be changing any time soon.
