### ISSUE TITLE
MK-V Supply redi-pak no fertilizer

### ISSUE THREAD

**Issue by asgkatz** [BobPalmer/MKS#515]
I noticed in part.cfg  that one instance of "fertilizer" was spelled "fertizer". I corrected it but it did not seem to fix the issue.

**Comment by asgkatz** [comment]
Changing spelling and adding another instance of "UmbraSpaceIndustries/Kolonization/Assets/MKV_Tex_04" fixed the issue.

**Comment by BobPalmer** [comment]
Fixed in next release
