### ISSUE TITLE
Mk-V Hab Module animation collides with MKII modules

### ISSUE THREAD

**Issue by headaix** [BobPalmer/MKS#518]
During the deploy/retract animation the mk-v hab will push against MK-II modules when node attached to mk-II integrated module base or integrated mobile base.   This causes vessel to hop on low gravity bodies. 

To reproduce:
1. Launch simple 3 part vessel with MK-II pioneer, MK-II integrated module base, and mk-v habitation module in typical configuration.
2. Use gravity hack to make the effect easier to see, but testing on minmus works fine as well. 
3. Expand the hab module.

Other mk-v inflatable animations do not seem to have this collision.

Tested against MKS 0.31.1 with all MKII modules and both MKII "base" modules.

**Comment by BobPalmer** [comment]
Updated in next patch
