### ISSUE TITLE
OKS Agricultural modules have negative cost when empty

### ISSUE THREAD

**Issue by christianvdstap** [BobPalmer/MKS#519]
Version: UKS_0.31.1

OKS Agricultural modules have negative cost when empty, see attached screenshot.

![screenshot91](https://cloud.githubusercontent.com/assets/8134651/8268512/b41aa33e-1788-11e5-9ff0-7a6e174ff95c.png)

**Comment by christianvdstap** [comment]
Also goes for the MK-V Habitation modules

![screenshot92](https://cloud.githubusercontent.com/assets/8134651/8268527/4cf6a2d8-1789-11e5-8b28-4eae44347de1.png)

**Comment by BobPalmer** [comment]
Resolved in next release
