### ISSUE TITLE
Parts with no resources in them cost negative funds

### ISSUE THREAD

**Issue by Lach01298** [BobPalmer/MKS#523]
Parts with no resources in them cost negative funds
![2015-06-21_00001](https://cloud.githubusercontent.com/assets/8176057/8269934/89a3b7f8-1805-11e5-80e4-011630cc8a23.jpg)

mark 3 cockpit cost 10,000

![2015-06-21_00002](https://cloud.githubusercontent.com/assets/8176057/8269935/c028d380-1805-11e5-9141-3799ea8c27d3.jpg)

with inflatable MK-V Agricultural module (with the default resouces) costs 11,560

![2015-06-21_00003](https://cloud.githubusercontent.com/assets/8176057/8269946/20a6a214-1806-11e5-9821-9e2d133c09a4.jpg)

with no resources it costs 8400

10,000 + cost of MK-V Agricultural module = 8400
thus the cost of the MK-V Agricultural module is  -1600  !!

this is not the only part that cost negative funds most things with expensive resources cost negative money.

**Comment by BobPalmer** [comment]
Fixed in next release
