### ISSUE TITLE
Some of the new MkV parts have incorrect bulkheadProfiles.

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [BobPalmer/MKS#525]
For example, many of the mini-modules are node-attach only, so they shouldn't be included in the srf category.  (I'll file a patch when I get the time in the next few days, assuming it isn't fixed by then, but I want to leave a note here for my own recollection.)

**Comment by BobPalmer** [comment]
Thanks - would love a pull request

**Comment by Kerbas-ad-astra** [comment]
Now that you've accepted my commpak PR, I think this is cleared completely.
