### ISSUE TITLE
Mk5 Agroponics Module has Converter Requireing Mulch (when using TAC-LS)

### ISSUE THREAD

**Issue by rabidninjawombat** [BobPalmer/MKS#528]
Looks like an USI converter wasnt removed in the TAC-LS config with the Mk5 Ag module. 

Needs to have GreenHouse /Agroponics.

**Comment by OakTree42** [comment]
Addendum: The MK-V does have it labeled as Agroponics, just need to flop Mulch + Fertalizer into Waste/WasteWater/CO2 + Fertalizer.

UKS/MKS Aeroponics pods need to have second 'function' button renamed from greenhouse to Agroponics (The one that takes fertalizer.) Right now both are labeled as greenhouse.
