### ISSUE TITLE
3.75 Kontainer price error

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#531]
The 3.75 new kontainers have a price error when empty:
Recyclables - negative 401 thousand
Specialized parts - negative 1.8 million

Issue does not seem so 'severe' on 1.25 or 2.5 (No negatives there at all). Still a lot of flux in empty costs between materials but this might be planned? Unsure on that.

**Comment by BobPalmer** [comment]
Fixed, and the little variances are there because I get lazy ;)
