### ISSUE TITLE
Update data on Refinery/fab/kerbitate/aero modules

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#532]
Need to update these parts to reflect the need for efficiency parts. Current Kerbitat and agro mk2 pods refer to the depreciated parts. No reference to need of the MK-V parts currently for refinery/Fabrication parts. (Is anything needed for the fuel refinery?)

**Comment by OakTree42** [comment]
Additional question related... do you still need one hab/greenhouse for every 2 kerbals? Any idea on that?

**Comment by BobPalmer** [comment]
Fixed, and yes
