### ISSUE TITLE
OKS cultivation inferior to MKS cultivation

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#535]
Note: May not be a bug as noted by RoverDude but thought it should be noted here. Currently the efficiency of the cultivator on the MKS is higher than the efficiency of the OKS pod. Logically may make sense, but wanted to note it here in case it should be standardized.

**Comment by Joshwoo69** [comment]
I think he will keep it as is. Logically

**Comment by OakTree42** [comment]
Very possible, when he was watching the stream he called it a possibly 'lucky bug' but at the same time I thought I should at least make a github post about it. I think actually he wanted me to. Although the values here actually seem like they don't need changing they were different in mks and oks which apparently was not the original intention from what he said. Either way, just keeping a record of the things we found.

**Comment by BobPalmer** [comment]
Turns out the MKS one was WAY too efficient.  It has now been downgraded to OKS levels.

**Comment by BobPalmer** [comment]
(As a concession to the benefits of having gravity for plants, I slightly beefed up the MKS rates - but they were still too high originally)
