### ISSUE TITLE
Feature Part Request Mk-V OKS parts

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#538]
Not sure how hard this would be but it is clear the MK-V parts are intended for ground bases. Are we going to get (and how hard would it be to do) OKS variants of the MK-V inflatables? In particular I am thinking of the inflatable workshop now that the inflatable workshop is needed to make the fabrication module work (and I oddly sometimes put those in a space station, crazy me!!) 

Anyway, obviously not a bug or even that high a priority but was playing around with some of the new systems and realized there were no MK-V variants for Orbit as far as I could tell. The little packs work fine of course, just the inflatable ones would be needed to be altered?

Again having a lot of fun poking things! :D

**Comment by BobPalmer** [comment]
OKS Workspace is now an efficiency part for the MK-III Fabricator and Refinery.
