### ISSUE TITLE
Modules which require Machinery can't operate without storage for Recyclables.

### ISSUE THREAD

**Issue by Corbald** [BobPalmer/MKS#549]
Modules which require Machinery can't operate without storage for Recyclables, but no storage is provided on the MK V versions..

I know this is the case with the Radial Greenhouse part for the MK V's, but might want to check them all, just in case.

**Comment by BobPalmer** [comment]
Insufficient specificity (i.e. is this with TAC or USILS)

**Comment by Corbald** [comment]
Doesn't seem to matter if it's TAC or USILS. Using either, any module which requires Machinery, such as the aforementioned MK V radial, can not operate if it has no storage for recyclables, despite said radial having no *built in* storage. This is both unintuitive and contrary to the nature of other modules which DO supply recyclable storage. As you explained to me on the forum, this module SHOULD NOT require recyclable storage. I do not know how to be more specific.

Reproduction: 
MK V pod and hub. 
+ Agriculture radial module. <-- Will not run without recyclable storage elsewhere on the craft.
