### ISSUE TITLE
MkV Greenhouse/Habitat not generating Food/Water on Kerbin

### ISSUE THREAD

**Issue by tobimai** [BobPalmer/MKS#558]
Could someone help me with USI Kolonization and TAC Life support? I have a craft made of 2 MK-V Habitation Modules, 1 Mk-V agricultural Module, Mk-V Koala Colony Hub and a Mk-V Scout Command pod. The problem is, that my habitats are only runnig at 10% load, so they arent producing enough food and water for my 2 Kerbals, I know it istnt possible to create a full closed-loop station but food and water are going down like the same speed than normal. I hope someone can help me.

**Comment by BobPalmer** [comment]
Best to ask on the forums.
