### ISSUE TITLE
Request for new module - Utilizer

### ISSUE THREAD

**Issue by Rsa97** [BobPalmer/MKS#56]
Would it be possible to add a new module for utilizing parts of ships (e.g. landing engines) and convert them to Construction Parts?
![screenshot136](https://cloud.githubusercontent.com/assets/7816436/3359909/7de1de08-faed-11e3-811f-e6c9b0957191.png)

**Comment by BobPalmer** [comment]
Closing this out as this can be satisfied with the EL recycler.
