### ISSUE TITLE
OKS Inflatable Storage Module - No Fertilizer Capacity

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/MKS#567]
OKS_Storage_ILM.cfg includes Fertilizer in the Supplies texture, but no quantity is given, so the ISM has zero fertilizer capacity. 

Reproducible: in the VAB, the supplies ISM can hold 17.5 each of supplies/mulch/organics, but fertilizer does not appear in the right-click menu.

**Comment by kholmar** [comment]
find the two lines that look SIMILAR to this and cut these over them.
there are a couple of typos I fixed

resourceAmounts = 17.5,17.5,17.5,17.5;23,23,23;23,23,4.6;4.6,4.6,23;4.6,4.6,17.5;17.5,17.5,17.5,17.5
initialResourceAmounts = 0,0,0,0;0,0,0;0,0,0;0,0,0;0,0,0;0,0,0,0
