### ISSUE TITLE
Proxy Logistics: Weight Limit on Rover is Restrictive

### ISSUE THREAD

**Issue by lstanden** [BobPalmer/MKS#570]
Ran into an issue where the Logistics Rover wasn't transferring resources.  It turns out, after investigating the code, there's a 3.0 Ton weight limit on the Rover before it no longer functions for proxy logistics.

I had built a rover using 4 small tracks from the Kerbal Foundries add-on, which resulted in my rover being ~ 4 Tons.  Once I destroyed the 4 tracks using my Engineer, it started to transfer resources.  This resulted in my Kerbal's water being stolen as described in #569

**Comment by lstanden** [comment]
Code in question
https://github.com/BobPalmer/MKS/blob/master/Source/KolonyTools/KolonyTools/MKSModule.cs#L482

**Comment by BobPalmer** [comment]
This restriction is by design.
