### ISSUE TITLE
OKS Station module efficiency never above 25% when in orbit

### ISSUE THREAD

**Issue by number-2** [BobPalmer/MKS#571]
Using TAC-LS
To reproduce:
1. Build a simple OKS station mine was: 
    * 1 Pioneer
    * 1 PDU
    * 1 Aeroponics
    * 1 Kerbitat
    * 2 Agriculture module
    * 1 hab ring
    * 2 workspaces
    * 1 TAC-LS Life support supplies container, Large
    * 1 TAC-LS Life support waste container, Large
2. Man with 5 level 5 engineers (2 each in kerbitat and aeroponics, 1 in PDU)
3. Get it into orbit (I HyperEdited mine up)
4. Inspect efficiency on any module - 25% on every module
![screenshot261](https://cloud.githubusercontent.com/assets/9613698/8792466/911f5ff4-2f35-11e5-9afe-7dadb3b5e7a1.png)
5. Repeat experiment, but leave station on the ground at the launchpad
6. Inspect efficiency on any manned module - starts at 250% and seems normal.
![screenshot262](https://cloud.githubusercontent.com/assets/9613698/8792526/505eaa64-2f36-11e5-9358-170e61e53804.png)

**Comment by number-2** [comment]
A quick glance at debug output reveals that GetCrewHappiness() is returning 0.
![screenshot268](https://cloud.githubusercontent.com/assets/9613698/8800756/623c3eb6-2f83-11e5-9be9-2c1d8d79df72.png)

**Comment by BobPalmer** [comment]
This has been corrected in the latest version.
