### ISSUE TITLE
USI Tools not updated for 1.0.4

### ISSUE THREAD

**Issue by geoffromer** [BobPalmer/MKS#578]
On startup, KSP-AVC complains that the version of USI Tools bundled with MKS was built to run on KSP 1.0.2.

**Comment by BobPalmer** [comment]
Updated in next patch

**Comment by geoffromer** [comment]
The issue is still present in MKS 0.31.6

**Comment by ArnePeirs** [comment]
This is because the "KSP_VERSION_MAX" in the version file is still set to 1.0.2

https://github.com/BobPalmer/MKS/blob/master/GameData/000_USITools/USI.version#L26-L29
