### ISSUE TITLE
Drills/Rover missing from parts list

### ISSUE THREAD

**Issue by AccidentalDisassembly** [BobPalmer/MKS#587]
MKS_Drill_01 and 02 as well as MKS_EL_Launchpad aren't visible in the editor. Unsure why - Hevak/TarHeel1999 suggested it was due to different manufacturers, but the launchpad has the same manufacturer as other parts (I think).

**Comment by ArnePeirs** [comment]
Do you have the parts and models in GameData?
Are they loading in KSP?
Did you researched and bought them?

**Comment by AccidentalDisassembly** [comment]
Yes, yes, and yes. Changing to category = Utility and subcategory = 0 makes them visible.

**Comment by ArnePeirs** [comment]
Did you look in the custom caterogies for UKS?

**Comment by BobPalmer** [comment]
Closing this - drills as noted were miscategorized.
