### ISSUE TITLE
MKV-ILM and Proxy Logistics

### ISSUE THREAD

**Issue by mhoram-kerbin** [BobPalmer/MKS#597]
The "MK-V Inflatable Logistics Module" does not contain a ProxyLogistics MODULE entry like the "UKS Inflatable Logistics Module (ILM)" does.

So basically the MKV ILM is not able to transfer resources via proxy logistcs.
I would have expected that a module named ILM is able to utilize proxy logistics.
Is this intentional?

```
	MODULE
	{
		name = ProxyLogistics
		LogisticsRange = 2000
		IsLogisticsDistributor = True
	}
```

**Comment by ArnePeirs** [comment]
I think that ProxyLogistics is only available for Mk-II (and Mk-III ?)
For Mk-V modules you'll have to use a Logistics Rover

**Comment by mhoram-kerbin** [comment]
Found this:
http://forum.kerbalspaceprogram.com/threads/79588?p=2074903#post2074903

Closing this issue as "works as intended".
