### ISSUE TITLE
Fuel Refinery can't make LiquidFuel if Oxidizer is full

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/MKS#602]
The Fuel Refinery won't convert Water to LiquidFuel unless there is space to store Oxidizer as well. This is an issue when using MKS to fuel LF-only ships (nuclear thermal rockets and jet engines). 

There are at least a couple of ways to resolve this:

1) Add converter to produce LF only, like stock ISRU
2) Set DumpExcess=True for Oxidizer in the LFO converter

**Comment by fmatosqg** [comment]
Hmm. I hope that whatever solves this issue can also be applied on https://github.com/BobPalmer/MKS/issues/550

**Comment by LouisB3** [comment]
On a related note, only 2/3 of the water by mass is converted to LFO. (And less than 5% of the water's mass is converted if you select LH2.)

**Comment by LouisB3** [comment]
Obviated by deprecation of fuel refinery.
