### ISSUE TITLE
MkV ILM dry mass is inconsistent

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/MKS#610]
The dry mass of the radial ILM is 1.25 in the VAB right-click menu, but it should be 0.75 according to the VAB part list. I am guessing the higher mass is a holdover from the MkII ILM, similar to #540.

**Comment by mhoram-kerbin** [comment]
Please close. This is resolved by #622 in v0.31.7

**Comment by mhoram-kerbin** [comment]
Also directly implemented in v0.31.9
