### ISSUE TITLE
Add electric charge to MK III modules

### ISSUE THREAD

**Issue by Luskhen** [BobPalmer/MKS#619]
Could it be possible to add power storage to MK III modules ? (the same way it works for MK II)

It would be nice (regarding parts count) to not have to strap batteries to modules.

**Comment by LouisB3** [comment]
Don't they already have the 10k EC per module?

**Comment by Luskhen** [comment]
Indeed I just checked the code and they do have electric charge. I don't know why I did not see it in game.
Thank you for correcting me.
