### ISSUE TITLE
Drill Position for calculating ore is wrong.

### ISSUE THREAD

**Issue by hobnob11** [BobPalmer/MKS#627]
From what i can tell, the metal / substrate drill uses the center of mass of the vechical to determin where it is (to know if there is a deposit of ore under it), so if you set up a large base that in one corner has a deposit of substrate and in the other a deposit of metal, the drills in the substrate section say "no resources found". 

when i disconnect the drilling rig from the base, without moving them just redeploying the drills they start mining resources.

![Image](http://i.imgur.com/hCb2zJy.jpg)
as you can see in the picture and in the scansat map, the drilling rig at the top of the picture is over a substrate deposit, but when its connected to the base it shows as no resources found.

**Comment by BobPalmer** [comment]
Correct, this is how stock resources work.  Closing this as it is related to stock, not part of this mod.
