### ISSUE TITLE
Supply Tank is too massive

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/MKS#647]
Related to #540. The liquid supply tank weighs .4 tons while the solid supply pack (same stats) weighs .15 tons. For comparison, a 1.25m Kontainer weighs .4 tons and has twice the capacity and three times the impact tolerance.

It looks like this was introduced in pull request #622, prior to which the mass definitions were inconsistent at .15 and .4 tons - but I believe the fix should have made it consistent at .15 tons rather than .4

**Comment by BobPalmer** [comment]
Fixed in next release
