### ISSUE TITLE
UKS Power Distribution Unit says "Mobile Aeroponics Module" on top.

### ISSUE THREAD

**Issue by billkerbinsky** [BobPalmer/MKS#654]
The PDU part has "07  MOBILE AEROPONICS MODULE" graphics on its top surface.

Also, its top attachment node appears to be placed a little too high - if I place a fuel tank on top of it for a skycrane-type delivery, I see a gap between the tank and the PDU..

**Comment by BobPalmer** [comment]
Corrected in the next release
