### ISSUE TITLE
Kontainer 4 - negative cost on Nuclear Fuels

### ISSUE THREAD

**Issue by M3tal-Warrior** [BobPalmer/MKS#659]
An empty Kontainer 4 switched to nuclear fuels costs -7,882,200 funds, which is quite an invitation to cheat ;)

**Comment by mhoram-kerbin** [comment]
Thanks for reporting! But duplicate of #598.

**Comment by M3tal-Warrior** [comment]
Oha, I didn't check that old stuff - normally RD is quite fast with fixing such stuff ;)
