### ISSUE TITLE
"Perform maintenance" change

### ISSUE THREAD

**Issue by M3tal-Warrior** [BobPalmer/MKS#660]
Performing maintenance on a Fuel Refinery via engineer EVA moves all Enriched Uranium from containers to the Refinery, but leaves Depleted Uranium untouched. I think it should actually be the other way round if not dragging in DU and dragging out EU. 

Also it would be cool to be able to move EU/DU around a vessel, either via normal resource transfer (although I see why one is not allowed to do so), or via engineer, since I don't want to waste DU as well as not adding a Fuel Refinery to all my PDU powered vessels/bases. I've thought about something like four switches for an engineer on every module/kontainer that stores DU or EU:
- Move enriched uranium: [Out] [In]
- Move depleted uranium: [Out] [In]

**Comment by BobPalmer** [comment]
Should be fixed in next release
