### ISSUE TITLE
OSE Workshop config doesn't affect MPL

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/MKS#661]
The OSE Workshop config modifies the parts from that mod to use UKS supply-chain resources, and in particular it replaces MaterialKits with RocketParts. The stock science lab, however, is unaffected (OSE added a small workshop and MaterialKits storage to it). 

Personally, I didn't want OSE messing with my stock MPL, so I just reverted the changes entirely:

@PART[Large_Crewed_Lab]:AFTER[Workshop]
{
    -MODULE[OseModuleWorkshop]{}
    -RESOURCE[MaterialKits]{}
}

**Comment by jd284** [comment]
I would also add the following to also change the OSE recyclers to produce RocketParts and remove MaterialKits entirely:

```
@PART[*]:HAS[@MODULE[OseModuleRecycler]]:FINAL
{
  @MODULE[OseModuleRecycler] {
    @OutputResource = RocketParts
  }
}
@PART[*]:HAS[@RESOURCE[MaterialKits]]:AFTER[Workshop]
{
  -RESOURCE[MaterialKits] { }
}
-RESOURCE_DEFINITION[MaterialKits] { }
```

**Comment by BobPalmer** [comment]
Switching full on to MaterialKits next release, so we can close this
