### ISSUE TITLE
Option to disable proxy logistics of an UKS ILM

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#662]
It's impossible to transfer all resources from an UKS ILM to some other module on the same vessel, it keeps taking them back faster than they can be moved out. So un-deploying or repainting it causes a great loss of all the resources it contains.

It would be nice to have an option to turn off its proxy logistics function so that it can be emptied and repurposed, especially now that repainting is enabled.

**Comment by BobPalmer** [comment]
Should no longer be an issue given the new update to logistics in the next release
