### ISSUE TITLE
The top node of the Duna series modules needs to be shifted down slightly

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/MKS#664]
It's a cosmetic issue, but anyway, the node on the top of the model is shifted up a little, so anything on top of it sort of floats above it.

Edit: A touch of the offset tool while in angle mode does fix it though, so, I don't know if it's intentional to account for that or something.

![kolonial sci_screenshot_2015-09-28--10-27-25](https://cloud.githubusercontent.com/assets/11197436/10143249/0284ee9e-65cc-11e5-8e34-5605c54686fc.png)

**Comment by BobPalmer** [comment]
Corrected in the next release
