### ISSUE TITLE
Multiple parts have negative cost

### ISSUE THREAD

**Issue by SciMan314** [BobPalmer/MKS#665]
Many parts are coming up with a negative cost in the VAB unless all resources are full. Launching a vessel with a negative cost ends up giving the player money, and recovering it gives the money back.

The root cause of this is that the cost of a part should be set as if it has full tanks for all defined resources.
This is true even if the part starts with some resources empty. The game will discount the part's cost based on whatever resources are missing.
If the part's cost is simply "base part cost" without resources, this will cause the part's cost to go negative if the value of the resources is greater than the value of the part.

For the MKS PDU, cost in the config is currently set to 55000. I assume this is the base cost of the part, with "empty tanks". 
Cost breakdown:
Base part cost: 55000
Machinery cost: 2000 units, cost 15.8 per unit: 2000*15.8 = 31600
Recyclables cost: 2000 units, cost 7 per unit: 2000*7 = 14000
ElectricCharge cost: 15000 units, cost 0 per unit: 15000*0 = 0
EnrichedUranium cost: 500, cost 865 per unit: 500*865 = 432500

Total cost for this part = 533100

Other parts have the same problem, notably the Duna series of modules. However it would be a good idea to check over all the parts that hold resources just to make sure.
I have provided the method I used to calculate the cost of the MKS PDU as an example.

**Comment by qm3ster** [comment]
Should be joined with #659, #598.

**Comment by fmatosqg** [comment]
Tested with 0.31.10 the new PDU default value for EnrichedUranium is 0, maybe it should be something like 200?

**Comment by fmatosqg** [comment]
MK-V redi pack has the same problem when switched to EnrichedUranium + DepletedFuel.

**Comment by PhaethonH** [comment]
Seems like 55000 Funds frequently comes up as a placeholder value.  Not sure what metrics are supposed to be used to determine final part cost for SupPak and Kontainer_04 (e.g. cost of empty EnrichedUranium 5m-Kontainer compared to empty Ore 5m-Kontainer or empty EnrichedUranium 2.5m-Kontainer?).  Changes I used to avoid negative costs for PDU, Redi-Pak, 5m Kontainer (v0.31.11.2):
```
diff -ur USI_Kolonization-0.31.11.2,pristine/GameData/UmbraSpaceIndustries/Kolonization/Parts/MKS_PDU.cfg USI_Kolonization-0.31.11.2/GameData/UmbraSpaceIndustries/Kolonization/Parts/MKS_PDU.cfg
--- USI_Kolonization-0.31.11.2,pristine/GameData/UmbraSpaceIndustries/Kolonization/Parts/MKS_PDU.cfg	2015-10-17 04:13:56.000000000 -0700
+++ USI_Kolonization-0.31.11.2/GameData/UmbraSpaceIndustries/Kolonization/Parts/MKS_PDU.cfg	2015-10-21 16:03:52.142769914 -0700
@@ -27,7 +27,9 @@
 	node_stack_bottom = 0.0, 2.032, 0.0, 0.0, 1.0, 0.0,2
 	TechRequired = specializedConstruction
 	entryCost = 8000
-	cost = 55000
+	//cost = 55000
+	cost = 529940  // invoiceCost +55000 w/ 200 Machinery.
+	//cost = 533100  // invoiceCost +55000 completely dry.
 	category = none
 	subcategory = -1
 	title = UKS Power Distribution Unit
diff -ur USI_Kolonization-0.31.11.2,pristine/GameData/UmbraSpaceIndustries/Kolonization/Parts/MKV_SupPak.cfg USI_Kolonization-0.31.11.2/GameData/UmbraSpaceIndustries/Kolonization/Parts/MKV_SupPak.cfg
--- USI_Kolonization-0.31.11.2,pristine/GameData/UmbraSpaceIndustries/Kolonization/Parts/MKV_SupPak.cfg	2015-10-17 04:13:56.000000000 -0700
+++ USI_Kolonization-0.31.11.2/GameData/UmbraSpaceIndustries/Kolonization/Parts/MKV_SupPak.cfg	2015-10-21 14:48:14.174608234 -0700
@@ -80,7 +80,7 @@
 		resourceNames =MetallicOre;Uraninite;Substrate;Minerals;Karbonite;ExoticMinerals,RareMetals;RocketParts;Metals;EnrichedUranium,DepletedFuel;Polymers;Supplies;Ore;Machinery;Recyclables;SpecializedParts;Fertilizer
 		resourceAmounts = 1250;1250;1250;1250;1250;625,625;250;1250;625,625;1250;1250;250;1250;1250;1250;1250
 		initialResourceAmounts = 0;0;0;0;0;0,0;0;0;0,0;0;0;0;0;0;0;0
-		tankCost = 3500;2500;2000;2500;2000;178000;2500;19000;55000;11000;19500;500;25000;12500;50000;7000
+		tankCost = 3500;2500;2000;2500;2000;178000;2500;19000;542500;11000;19500;500;25000;12500;50000;7000
 		basePartMass = 0.15
 		tankMass = 0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0
 		hasGUI = false
diff -ur USI_Kolonization-0.31.11.2,pristine/GameData/UmbraSpaceIndustries/Kontainers/Kontainer_04.cfg USI_Kolonization-0.31.11.2/GameData/UmbraSpaceIndustries/Kontainers/Kontainer_04.cfg
--- USI_Kolonization-0.31.11.2,pristine/GameData/UmbraSpaceIndustries/Kontainers/Kontainer_04.cfg	2015-10-17 04:13:54.000000000 -0700
+++ USI_Kolonization-0.31.11.2/GameData/UmbraSpaceIndustries/Kontainers/Kontainer_04.cfg	2015-10-21 16:24:09.730813294 -0700
@@ -68,7 +68,7 @@
 		resourceNames =MetallicOre;Uraninite;Substrate;Minerals;Karbonite;ExoticMinerals,RareMetals;RocketParts;Metals;EnrichedUranium,DepletedFuel;Polymers;Supplies;Ore;Machinery;Recyclables;SpecializedParts;Fertilizer
 		resourceAmounts = 160000;160000;160000;160000;160000;80000,80000;32000;160000;80000,80000;160000;160000;32000;160000;160000;160000;160000
 		initialResourceAmounts = 0;0;0;0;0;0,0;0;0;0,0;0;0;0;0;0;0;0
-		tankCost = 336000;152000;120000;184000;103000;24052000;105000;2328000;61314000;1432000;2457000;55000;2582000;1170000;5170000;855000
+		tankCost = 336000;152000;120000;184000;103000;24052000;105000;2328000;69302000;1432000;2457000;55000;2582000;1170000;5170000;855000
 		basePartMass = 25
 		tankMass = 0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0
 		hasGUI = false
```

**Comment by BobPalmer** [comment]
This should be sorted.
