### ISSUE TITLE
Perform maintenance for heat shield ablator and/or configurable resources

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#671]
Please extend the "perform maintenance" functionality to the heat shield ablator, or even better make it configurable for each part which resource is replenished by maintenance. Basically make it work like the EnrichedUranium, not possible to manually pump it but can be installed by engineer maintenance.

Right now for my ore ships from Minmus I have to scrap the old heat shield, fabricate a new one and then install it. This is fairly annoying because they need multiple kerbals to move and don't quite look right when installed with KIS.

If appears that the USI_ModuleFieldRepair is hardcoded to only look for machinery and uranium. It would be nifty if it were possible to specify the resource to "repair"/replenish in the cfg file, or modded as an MM patch. Adding a converter to fabricate the ablator and defining some containers is easy enough after that (although adding it to the standard Kontainer set would be nice!). If it's configurable like this it could also be used to refurbish solid fuel boosters even. Not sure how useful that would be though...

**Comment by BobPalmer** [comment]
Configurable in next release
