### ISSUE TITLE
Proxy logistics (UKS ILM) resources sometimes not being transfered

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#672]
(Recap from [this forum post](http://forum.kerbalspaceprogram.com/threads/79588-1-0-4-USI-Kolonization-Systems-(MKS-OKS)-(0-31-9)-2015-09-21?p=2226932&viewfull=1#post2226932))
In my savegame, the "raw materials" ILM at the main base only transfers resources from the two far drilling stations (about 1.5 km away), one each for MetallicOre and Water. From the closer drilling station (733 m), which produces Substrate and Minerals, neither resource is transferred to the main base by proxy logistics. I have to put a pilot in a rover to transfer them via rover logistics [which is annoying because of TAC-LS, I have to keep focusing the rover every two days so it can pull in its life support resources which it only does for 2 days worth despite space for 19d].

Screenshots at [forum post 1](http://forum.kerbalspaceprogram.com/threads/79588-1-0-4-USI-Kolonization-Systems-(MKS-OKS)-(0-31-9)-2015-09-21?p=2227062&viewfull=1#post2227062) and [post 2](http://forum.kerbalspaceprogram.com/threads/79588-1-0-4-USI-Kolonization-Systems-(MKS-OKS)-(0-31-9)-2015-09-21?p=2227086&viewfull=1#post2227086), savegame [here](http://ttdpatch.net/~jdrexler/quicksave%20for%20RoverDude.zip) (besides USI MKS it requires KIS, KAS, Mechjeb2, TAC-LS and Tweakscale to load).

**Comment by BobPalmer** [comment]
This has been completely redone in the next release, closing
