### ISSUE TITLE
Description of drills

### ISSUE THREAD

**Issue by mhoram-kerbin** [BobPalmer/MKS#673]
The MEU-500 is called "MEU-590 pulse drill" in its description.

The MEU-750 is called "MEU-270 Pulse drill" in its description.

Looks like the numbers are wrong.

**Comment by fmatosqg** [comment]
Submitting PR https://github.com/BobPalmer/MKS/pull/678

**Comment by fmatosqg** [comment]
new PR from DEVELOPER branch https://github.com/BobPalmer/MKS/pull/682
