### ISSUE TITLE
Duna modules rotated 90º

### ISSUE THREAD

**Issue by jberkman** [BobPalmer/MKS#676]
When I start a new vessel in the VAB with a Duna module, the hatch faces East (90º).

If i rotate it to face 180º like normal parts, and put it in orbit (OK, using Hyperedit to test), the pitch and yaw controls are swapped:

Pitching causes it to rotate along the axis going through the hatch, while yawing causes the hatch to pitch up and down.

Placing a probe core above the module in the correct orientation and doing "control from here" makes pitch and yaw work as expected.

Is this a side-effect of being designed to mount inside the karibou?

**Comment by BobPalmer** [comment]
This is intended behavior - the hatch is now a side mount.
