### ISSUE TITLE
Core parts are not moved in the tech tree when both CTT and NearFuture are both installed

### ISSUE THREAD

**Issue by kaa253** [BobPalmer/MKS#684]
I have both CTT and Near Future Electrical installed and I find the reactors in the default node of the tech tree not in large (improved) Nuclear power. Is there an "AFTER" required in the module manager cfg?

As always this will need some investigation to confirm. Sorry if this turns out to be only on my mod spaghetti KSP install because I have done/got something wrong.

**Comment by sopindm** [comment]
I think real reason is that reactor parts are named like 'USI_Nuke_626' and it CTT path they are named like 'USI_NUKE_625'. If you change name to 'USI_Nuke_625' - everything works

**Comment by kaa253** [comment]
Sounds about right, I will check it out. Well spotted, thanks

**Comment by BobPalmer** [comment]
Fixed in next core version
