### ISSUE TITLE
Duplicate OKS PDU (legacy) cfg files in package

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#688]
There are two OKS PDU (legacy) files in the UKS_0.31.11.2.zip package: OKS_PDU.cfg and OKS_PDU_LEGACY.cfg, both define the same part (OKS_PDU). The OKS_PDU_LEGACY.cfg should probably be deleted, since it contains DepletedUranium instead of DepletedFuel.

**Comment by BobPalmer** [comment]
These have been deprecated.
