### ISSUE TITLE
UKS PDU and FuelRefinery produce EnrichedUranium but it cannot be used for "perform maintenance"

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#689]
The UKS PDU lacks the USI_ModuleResourceWarehouse module that allows its EnrichedUranium to be transferred to nukes or other parts by "perform maintenance".

**Comment by jd284** [comment]
The Fuel Refinery has the same problem.

**Comment by BobPalmer** [comment]
Fixed in next release.
