### ISSUE TITLE
KolonyTools.dll same version mismatch - faultly by OP

### ISSUE THREAD

**Issue by khr15714n** [BobPalmer/MKS#696]
releases >> USI Kolonization Systems v0.31.11.2 dates 18.10.15 20:33:54, 113.664 Bytes
CKAN >> USI Kolonization Systems 1:0.31.11.2 dates 17.10.15 04:13:56, 114.668 Bytes

"same" release but different content, at least the KolonyTools.dll is different.
Using version for the dll would also help.

**Comment by fat-lobyte** [comment]
Please do not create Issues with the word "CKAN" in it. RoverDude will hit you. Consider it a swear word from now on ;)

On a more serious note, I think you should create a CKAN issue, because RoverDude has nothing to do with them and considers his own releases to be definitive.

**Comment by khr15714n** [comment]
@ CKAN vs RoverDude - thanks, didn't know they love each other so much ;)

Tripplechecked it again and it seems it's my fault: CKAN has the same official release version.
I was comparing the newer one within the FOR_RELEASE folder.
