### ISSUE TITLE
Change (defined) resources the way you want

### ISSUE THREAD

**Issue by khr15714n** [BobPalmer/MKS#699]
//Duplicate from CRP - Overriding to new EL value

Just did a test and the outcome was as expected: the first RESOURCE_DEFINITION is used by KSP.

That means whatever you define after the first RESOURCE_DEFINITION has no effect on KSP.
Using Module Managers ":FIRST", ":BEFORE", "%" aso would not help, results are curious at best.
Editing (@) the first index (,0) works but there has to be at least this first index.

Solution:
// define RocketParts at least once, doesn't matter whether another mod has defined it before or not
RESOURCE_DEFINITION
{
    name = RocketParts
    density = 0.0025
    unitCost = 1.5
    flowMode = ALL_VESSEL 
    transfer = PUMP
    isTweakable = true
}
// set values of RocketParts
@RESOURCE_DEFINITION[RocketParts],0
{
    @density = 0.0025
    @unitCost = 1.5
    @flowMode = ALL_VESSEL 
    @transfer = PUMP
    @isTweakable = true
}
and you end up with all(!) indices changed, not only the first (0) one. (Until MM adds proper support for RESOURCE_DEFINITION)
You still end up with warnings about multiple defined resources in logs but in ModuleManager.ConfigCache and KSP the values are correct(ed).

Edit: Forgot to mention that deleting (!) a possibly existing RESOURCE_DEFINITION hasn't worked, either.

**Comment by jd284** [comment]
That's why Roverdude said in the forum thread that he's moving from RocketParts to the OSE Workshop MaterialKits which can be added to the CRP.

**Comment by BobPalmer** [comment]
Sorry, I just don't understand what you're trying to do here.

**Comment by khr15714n** [comment]
Adding a new set of values for an existing resource doesn't "override" the values used in game.
There has to be an existing, predefined resource to allow changing values because MM doesn't support change or create (%) for RESOURCE_DEFINITION at the moment.

If you wanna test it by your own just copy a resource form Squad/ to R/ and T/ and change f.i. unitCost. You'll end up with values defined in R/. Overriding CRP's definitions by copying and changing values in an alphabetically later mod doesn't work.

**Comment by BobPalmer** [comment]
Sure, understand that, but we don't do any resource overrides - we use CRP which by it's very definition should never be overwritten.

**Comment by khr15714n** [comment]
Good to know.

Maybe I've misinterpreted your comment about "overriding" in UmbraSpaceIndustries/Kolonization/MKS_Resources.cfg 
"//Duplicate from CRP - Overriding to new EL value"
If that's the case I'm sorry.

**Comment by BobPalmer** [comment]
No worries, thanks
