### ISSUE TITLE
The file "KolonizationTweakScale.cfg" looks obsolete

### ISSUE THREAD

**Issue by pellinor0** [BobPalmer/MKS#700]
Two things:
* The parts "MKS_RadialTank" and "MKS_Storage_Tank" seem no longer to exist, so probably these patches do nothing. 
* TweakScale no longer messes up the TankCost of FSFuelSwitch modules, so the field should no longer be erased when TweakScale is present.

**Comment by BobPalmer** [comment]
Deprecating native Tweakscale support as a lot of these bits are long gone.
