### ISSUE TITLE
Unable to pull science experiments from Training akademy

### ISSUE THREAD

**Issue by GokouZWAR** [BobPalmer/MKS#703]
I have 10 science experiments loaded into a training akademy module in orbit. While hooked onto the crew hatch with a kerbal the option to "take data" is not available. Is there some special place I have to be in order to grab the data from there?

**Comment by KevinMilcz** [comment]
I think this is related to model used for the asset. I tried making the cfg file mostly match the one with the stock science lab and still no proper context menu.

I don't get any different context menus for right clicking the door vs the rest of the part. Is it possible that the part (MKS_Module_III) is missing the actual hatch types? I don't have the tools to edit the model so can't fix/confirm.

As a workaround, the ship manifest mod allows you to move experiments around.

**Comment by BobPalmer** [comment]
Fixed in next release
