### ISSUE TITLE
Parts efficiency doesn't updated if you add or remove kerbals

### ISSUE THREAD

**Issue by sopindm** [BobPalmer/MKS#704]
I have some troubles with my base's efficiency not being updated if I add or remove some kerbals to base (i'm trying to balance crew count/efficiency on my Mun base). In MKS source code I found following lines:
if (curConverters != _numConverters)
            {
                _numConverters = curConverters;
                EfficiencySetup();
            }

So it doesn't updated if you don't add or remove some crew. Looks like we need to care about crew count too.

**Comment by BobPalmer** [comment]
Fixed in next release
