### ISSUE TITLE
OKS Agro Tac LS - Not enabled

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#717]
The current OKS Agro module does not have Tac LS module enabled.

**Comment by jd284** [comment]
I added a pull request #720 for this. Hope I didn't mess up too badly, first time contributing via git...

**Comment by jd284** [comment]
I added a pull request #720 for this. Hope I didn't mess up too badly, first time contributing via git...

**Comment by BobPalmer** [comment]
Merged :)
