### ISSUE TITLE
Storage tweaks in .32

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/MKS#724]
Various issues/suggestions for storage tweaks given the recent mechanic changes:

1) Launchpad/orbital dock has storage for MaterialKits, but not SpecializedParts which they also require.
2) PDU in an earlier version had modest XenonGas storage to readily capture this useful byproduct; would be nice to have that again.
3) OKS Agriculture inflatable has storage for Substrate/Water though it can't use them.
4) Mk3 landing module Supplies configuration has no storage for Fertilizer.
5) Mk3 landing module and various ILMs have no storage for SpecializedParts, which are more important than ever in construction - I suggest adding this to the Equipment configuration.

**Comment by BobPalmer** [comment]
Updated next release - ping me if I missed any of these
