### ISSUE TITLE
MaterialKits converters using old ratio

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#726]
The MaterialKits converters in the MKS Fabricator and the MKV Workshop should have their output boosted by a factor of 5, the ratio between MaterialKits and RocketParts.

**Comment by OakTree42** [comment]
I'm not finding any converters that change rocket parts into material kits, is this a thing? Or am I mis-reading this? I also tried to use the UI with the new USI update with rocket part storage and could only get it to use material kits and specialized parts. Is there no longer any way to use rocket parts with this update then? I feel like I'm simply missing something here. I have a test base with a MKV workshop, UKS Fabrication Module, UKS Fuel Refinery, UKS Mobile refinery, and a pioneer module (Plus the MkV Coms and Sifter) and find no way to convert my rocket parts into anything useful.

**Comment by BobPalmer** [comment]
This should be sorted (it works by mass in this case)
