### ISSUE TITLE
OSE Workshop patch not taking FSFuelSwitch into account

### ISSUE THREAD

**Issue by pjwerneck** [BobPalmer/MKS#730]
The cfg in UKS/OSE.cfg changes the OSE Containers tanks to Metals/Chemicals/Polymers storage in place of the MaterialKits, but the OSE tanks are using FSFuelSwitch and we end up with both after launch, even though only the FSFuelSwitch choice is shown in the VAB.

Also, it looks like RareMetals and ExoticMinerals were removed from the MKS loop entirely, but the Workbench and Recycler still outputs and requires those for some parts, requiring an extra container for each one. The lack of visibility from OSE makes it even more problematic, as the recycling process simply freezes when there's no storage left and there's no way to abort it. It would be better to include some RareMetals and ExoticMinerals storage, or remove RareMetals and ExoticMinerals entirely, relying only on Metals/Chemicals/Polymers.

**Comment by BobPalmer** [comment]
Fixed next release
