### ISSUE TITLE
Install broken when using CKAN

### ISSUE THREAD

**Issue by spirritus** [BobPalmer/MKS#731]
Hello,

this is an awesome mod! Unfortunately the latest Version (0.32.2.0) is missing the UKS and Kolonization folders when installing via CKAN.

Cheers Jens
![mks-ckan](https://cloud.githubusercontent.com/assets/1154316/12537468/5145c58e-c2c0-11e5-94fd-bfddfb58584c.PNG)

**Comment by societalpillage** [comment]
Unless we're both missing something I'm having the same problem with 0.32.0 on ckan. The UmbraSpaceIndustries folder under gamedata is only 11 MB vs 81.8 MB under v0.31.12.0.

**Comment by Almagnus1** [comment]
I'm experiencing the same issue as well.

Did the mod file structure change significantly in recent patches?

**Comment by Almagnus1** [comment]
Actually, after looking in this, this one is on CKAN, not UKS.

Here's how you fix this:

1. Back up your KSP install.
2. In CKAN, File => Export Installed Mods, save it at a backup location.
3. Backup your KSP command line settings (Settings => KSP Command LIne)
4. Uninstall all your mods, then close CKAN
5. Delete the CKAN Directory from KSP
6. Reopen CKAN
7. File => Import from .ckan (use the file you created in step 2)
    NOTE: This can take several attempts, because you will be rapidly pulling files from a handful of servers and can hit forced timeouts.  If you get a failure, close CKAN, and try again in about five minutes.  Once everything is downloaded, deployment should be easy.
8. Restore your command line settings, and everything should work again.

I'm also working through the above, but I'm stuck on step 7 at the moment

**Comment by Almagnus1** [comment]
And the above workaround works.

**Comment by foonix** [comment]
The CKAN team has now fixed this in their NetKAN repo.  https://github.com/KSP-CKAN/NetKAN/pull/2939
