### ISSUE TITLE
MK-V power pak stops generating power if near PDU and unmanned

### ISSUE THREAD

**Issue by jrobnett** [BobPalmer/MKS#739]
A PDU with a power pak and an engineer in proximity to an Ag module with a power pak and crew.  The Ag module power pak reported normal efficiency.  Once the crew was removed the Ag module would pull power from the PDU but stopped generating power on it's own and reported an efficiency of zero.

Save is at: http://www.filedropper.com/testoks
Image of test is at: http://i.imgur.com/qsSEv7c.png

**Comment by BobPalmer** [comment]
The power pack requires an engineer in the vessel to generate power, since it also acts as a power distributor.
