### ISSUE TITLE
MMIVA.cfg needs to go

### ISSUE THREAD

**Issue by Goldenpsp** [BobPalmer/MKS#741]
I posted this on the forums but figured I would paste here for easier access.
BTW @Roverdude, the MMIVA.cfg I created a long time ago can be removed.  I had made an issue which you closed but you moved MMIVA.cfg to UKS instead of deleting it.  It was an MM patch to add seat inventory to modules without an IVA, but kospy since fixed that in KIS so the file is no longer necessary.  I never could figure out how to do a pull request that simply deletes a file.

**Comment by BobPalmer** [comment]
Done
