### ISSUE TITLE
Scrap parts recycling functionality.

### ISSUE THREAD

**Issue by Baladain** [BobPalmer/MKS#742]
It seems the Recycle function is limited to a very small number of parts.  Those being kontainers and supply packs.  Suggest this should be included in most parts that have "recyclabes" as standard inventory, and perhaps the octagonal landers as well.

**Comment by BobPalmer** [comment]
The rub is that you would stuff things in parts that are not meant to do anything with the recyclers (and fill up the space they would use themselves to do their own recycling).  Octo did get set up next patch tho.  Closing for now to keep the tracker clear, if you have other specific modules (other than the octo) you would like to see this on let me know :)
