### ISSUE TITLE
Portable Light issues

### ISSUE THREAD

**Issue by Goldenpsp** [BobPalmer/MKS#743]
I was testing on Kerbin.  I KIS anchored one to the ground with an engineer.  It was night time but it seemed to pull electricity properly from the MK-V power pack.  However I had no option to turn on the light.

Also, every time I would go back to the KSC and then back to the vessel the anchored light was gone.

**Comment by smjjames** [comment]
I found another problem. When I put it on top of the karibou cab (with some batteries behind it), the globe does light up, but doesn't actually emit light.

**Comment by smjjames** [comment]
As of version 0.33.1, the light globe still doesn't actually emit light. Haven't looked at the other issues though.

**Comment by BobPalmer** [comment]
emit is fixed next release
