### ISSUE TITLE
Extra MKSModule entry

### ISSUE THREAD

**Issue by mcortez** [BobPalmer/MKS#747]
Just noticed that GameData/UmbraSpaceIndustries/UKS/Parts/MKV_AgModule.cfg has two entries for the MKSModule

Around line: 126
    MODULE
    	{
    		name = MKSModule
    		workSpace = 0
    		livingSpace = 0
    		CrewBonus = .5
    		MaxEfficiency = 1
    	}

Then again around line 209:
    MODULE
    	{
    		name = MKSModule
    		workSpace = 1
    		livingSpace = 0
    		MaxEfficiency = 1
    		PrimarySkill = Scientist
    		SecondarySkill = Engineer		
    	}

**Comment by BobPalmer** [comment]
Fixed in a prior release :)
