### ISSUE TITLE
Remove Specialized parts need for EL.

### ISSUE THREAD

**Issue by aihaw** [BobPalmer/MKS#749]
Hi! As for now, it seems that there is no way to produce specialized parts from extra planetary resources. So, i wondered if there was a way to only require material kits for ship production. Maybe it is a wanted feature about self-sustainment being impossible. It's just too bad for players like me that dream about expanding bases really far away without sending new modules from kerbin every launch window... Please, is there a way i could change this in the config files?

**Comment by ToBoldlyGo** [comment]
Supposedly those aren't meant to be manufactured, but rather reclaimed via salvaging parts of ships you no longer need in your colony. You could change it messing around with a chosen module in  GameData\UmbraSpaceIndustries\UKS\Parts to add to it SP production capacity to your liking.

**Comment by BobPalmer** [comment]
Closing, as specialized parts manufacture is included in the next release.
