### ISSUE TITLE
Drill loads are now reduced to 0.00%

### ISSUE THREAD

**Issue by danfarnsy** [BobPalmer/MKS#754]
I have a Karibou Rover base with Mk-V modules and MKS resource drills. Since applying update 0.33.1, my drills have all reduced to 0% load. Though it says, e.g. "Water rate: 0.059/sec," there is no increase in stored water (with plenty of capacity to spare).

http://imgur.com/8UIMUo2

**Comment by danfarnsy** [comment]
A new vessel on the runway doesn't appear to have the issue.

**Comment by BobPalmer** [comment]
Closing due to non-repro on a new craft

**Comment by danfarnsy** [comment]
I was able to reproduce it: http://imgur.com/a/SEMVD

On the landing-way, drills operate at full capacity. With an identical craft on the Mun, they're stuck at 0% load.

Can we re-open this issue and categorize it "investigating," even if it's low on your priority list? This one is bizarre enough I think I'll need to make a clean KSP install with USI mods and hyper edit to narrow it down. I'm scratching my head at what mod conflicts may be at root, but the fact that it was working in UKS 0.32 and then stopped with the update suggests there's still something USI-ish.

Because nothing changed with the drills, the only thing off the top of my head is engineer proficiency modifiers.
