### ISSUE TITLE
Remove research lab function from Pioneer module

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#757]
The research lab function should be removed from the Pioneer. Since a pioneer module is all but required for life support (only module with 75% recycling), but you can't have more than one per vessel because the research lab function is broken when there's more than one. 

With the MKV Comm Lab, there's a convenient small alternative available for storing duplicate science records, and the Akademy as a bigger module for doing serious research. I don't really see the need for the pioneer to be a research lab as well. 

That would shorten the pioneer info menu by a lot as well, removing multiple info lines and several buttons, and also remove problems with multiple labs per vessel.

Ideally the MKV Comm Lab would be upgraded a bit to compensate (at least change the multiplier, see post http://forum.kerbalspaceprogram.com/index.php?/topic/72032-105-usi-kolonization-systems-mksoks-0331-planetary-logistics-and-kolony-rewards/&do=findComment&comment=2391450 )

**Comment by BobPalmer** [comment]
This is in the next release along with a comm lab buff
