### ISSUE TITLE
Demolition Charge description

### ISSUE THREAD

**Issue by SnakyLeVrai** [BobPalmer/MKS#759]
"This _shaped_ charge..."

Actually, a _shaped_ charge is destined to puncture a tiny hole of a very precise shape, like round, or linear (if you want to cut something). It's a perfect way to penetrate heavy armor on a battle tank. If you want to blow stuff up randomly, to destroy it, **the _shaped_ charge is the worst option**, as you'll only punch a hole through it without destroying it _at all_, or split it in two _very cleanly_.

**You want to destroy it in a million pieces?** "This _demolition_ charge...", or even better, **"This _high-explosive_ charge..."** :D 
(as high-explosives burn in a supersonic way, producing a brutal shockwave that will Kerbal the heck out of anything).

Just my 2 cents :D

**Comment by BobPalmer** [comment]
Changed for next release ;)
