### ISSUE TITLE
MKV Smelter/Sifter

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#760]
I mentioned this while you were watching and you asked me to submit a github issue but the current setup of the MKV parts is a tad off and the suggestion was perhaps convert them to both pure dirt (as this is now a catch all in a lot of ways for the planet/moon) 

Was thinking about this and I just hope you don't switch the conversion rate from 1 to 20 to 1 to 200, that would be too much, although since the main sifter does 1:20 I could see perhaps 1:40 or something, or just have it be slower in the conversion speed but keep it at 1:20. Either way, seems to make more sense than how they currently work.

**Comment by BobPalmer** [comment]
It will have a slightly lower yield, but more importantly, will have an abundance threshold (so it gets the most common stuff).

**Comment by BobPalmer** [comment]
Closing as this is now in the next release (along with a babby fertilizer maker)
