### ISSUE TITLE
OKS Kerbitat Water Purifier still uses ridiculous amounts of water

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#763]
For UKS the amount was reduced to 0.005 water per second, for OKS it's still 20 water per second for the same load.
(Although since orbital bases generally don't have access to a source of water, maybe this function should be removed entirely?)

**Comment by BobPalmer** [comment]
Actually they can get lots of water via asteroids :)

Thanks will fix this

**Comment by BobPalmer** [comment]
fixed in next USI-LS version
