### ISSUE TITLE
Crash tolerance or break torque?

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#766]
Breaking Force and Breaking Torque are set incredibly low for all the parts now.
The Mk3 parts have 280

I am unsure of the cause but these parts are breaking apart under very little pressure, especially things connected to the regolith sifter which was what I was testing. I know the science lab has 200 (stock) but some how it seems to better hold on to parts than this does now? Is it due to vessel type or some other bug somewhere? Not sure what to suggest but it does need some attention as right now even landing at a fairly low speed is costing me parts, even with kerbal joing reenforcement?

**Comment by BobPalmer** [comment]
Fixed in next release
