### ISSUE TITLE
SpecializedParts need tuning

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#768]
To make MaterialKits (in the workshops), we still need 25% SpecializedParts, and then to use the MaterialKits in the EPL dock, we need another 10% SpecializedParts.

The 25% spec parts made sense when the workshops were just downscaled versions of the Fabricator, but since they took over that job completely this makes ship construction overly dependent on spec parts. I know those can also be produced now, but the inputs are pretty uncommon. 

So the workshops should be changed to not require SpecializedParts for MaterialKits any longer. Alternatively, remove the SpecializedParts requirement from the EPL recipe. For Machinery, it's probably fine to leave it as is though, or perhaps reduce it to 10% as well.

**Comment by BobPalmer** [comment]
Normalized at 10% for machinery and rockets, 0% for MaterialKits in next release
