### ISSUE TITLE
Add lights to OKS modules

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#771]
It'd be nice if the OKS modules had some light so that a station isn't completely dark for half an orbit.

**Comment by bendavieshe3** [comment]
Obviously you can add your own lights. In fact I use a mod with lights specifically for vessel self-illumination. 

Where this gets interesting is that adding a lot of lights ups the part count significantly. I'm not sure whether physics-less parts are really an issue for performance or not. But if so, this change might be worthwhile.

**Comment by BobPalmer** [comment]
Lights (the rendering, not the parts) add lag.  It's best to use a small number of light parts.

**Comment by BobPalmer** [comment]
Closing due to reasons notes above.
