### ISSUE TITLE
Missing Part: Sandbox vs Career

### ISSUE THREAD

**Issue by gamerscircle** [BobPalmer/MKS#774]
I was in Das' chat and was asking you about the large cage for holding MKS items not showing up in career mode vs sandbox.

-GamersCircle

**Comment by MynarMoonshadow** [comment]
Confirmed with both Science and Career mode.  UKS Module Delivery System does not show up in the Kolonization tab.  Does show up in Sandbox.

**Comment by BobPalmer** [comment]
Next release
