### ISSUE TITLE
Automatic maintenance should only take resources from storage

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#775]
Currently, the automatic maintenance performed when there's an engineer in the MK-V Workshop (to increase its efficiency) causes all the machinery from the workshop to be distributed to other parts, so every day I have to move the machinery back to continue the MaterialKits production.
This automatic maintenance should not remove resources from active parts and only transfer resources out of storage.

**Comment by BobPalmer** [comment]
Double edged sword.  If I turn this off, the stuff the module produces cannot be automatically distributed.

**Comment by jd284** [comment]
Well presumably the vessel will have machinery storage in some other part, so the surplus machinery will end up there and be used for maintenance.
At least the workshop shouldn't have more than say 50% of its machinery removed by maintenance, so that it can keep producing more.

**Comment by BobPalmer** [comment]
sorted
