### ISSUE TITLE
MKV Sifter - Not Working + Possible Typo in Code (ver: 33.6)

### ISSUE THREAD

**Issue by gandi3k** [BobPalmer/MKS#783]
hey roverdude, is it possible you have a typo in your MKV_Sifter.cfg

    MODULE
        {
            name = MKSModule
            workSpace = 0
            livingSpace = 0
            CrewBonus = .5
            MaxEfficiency = 1
            eyond                                       <----here
        }

also this sifter seems not to work correctly, inputed all needed stuff, but nothing comes out of it

 

Setup:

version 33.6

Pioneer Modul (one Scientist/one Engeneer)
Sifter
PowerPack
Storage (Full dirt and Space for Substarte, Minerals and Metalic Ore)
Kontainer with Machinery

**Comment by henrybauer** [comment]
I'm seeing the same thing. When the sifter is activated it just spams:

```
[EXC 14:14:42.787] NullReferenceException: Object reference not set to an instance of an object
	ResourceConverter.ProcessRecipe (Double deltaTime, .ConversionRecipe recipe, .Part resPart, .PartModule resModule, Single efficiencyBonus)
	BaseConverter.FixedUpdate ()
[EXC 14:14:42.792] NullReferenceException: Object reference not set to an instance of an object
	ResourceConverter.ProcessRecipe (Double deltaTime, .ConversionRecipe recipe, .Part resPart, .PartModule resModule, Single efficiencyBonus)
	BaseConverter.FixedUpdate ()
```
The MK3 sifter is fine.

**Comment by BobPalmer** [comment]
Fixed
