### ISSUE TITLE
Scan-O-Matic resource modules configured wrong

### ISSUE THREAD

**Issue by DMagic1** [BobPalmer/MKS#784]
It looks like you got your Module name and resource name fields a little mixed up here for the [Scan-O-Matic](https://github.com/BobPalmer/MKS/blob/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/UKS/Parts/ScanOMatic.cfg#L94-L121).

Also, do you intend to add these resource scanners to the MKS_Antenna as well? I'm trying to get a SCANsat update in order and don't want to add resource scanners to parts that they aren't intended for.

**Comment by OakTree42** [comment]
I was able to add the modules for the MKS_Antenna CFG file for the new resources and that looked okay. And it then integrated fine with the ScanSat so only needs four copy/paste modules with the names updated for Gypsum etc...(don't forget rare metals and exotic minerals!)

**Comment by BobPalmer** [comment]
Fixed - and yep I will toss them over
