### ISSUE TITLE
The planetary survey camera animation broke in 0.33.8

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/MKS#800]
It broke as in theres no option to toggle camera. It's still able to do it's scanning though. With SCANsat at least, I haven't looked if it's a problem when using stock only.

**Comment by frango9000** [comment]
https://github.com/BobPalmer/MKS/issues/797 Duplicate fixed by https://github.com/BobPalmer/MKS/pull/796

**Comment by bendavieshe3** [comment]
@smjjames can you confirm this issue is now fixed? (works for me)
