### ISSUE TITLE
UKS Nuclear Fuel Processor maintenance glitch

### ISSUE THREAD

**Issue by sh1pman** [BobPalmer/MKS#801]
A UKS Nuclear Fuel Processor has two "perform maitenance" buttons. The bottom one makes all sorts of bad things happen: enriched uranium disappears from nearby inventories, including its own; the processor's inventory can even show negative amount of uranium.
This is especially frustrating if one has an engineer in an inflatable workshop, as there is no way to stop the engineer from repeatedly performing this "bad" maintenance.

**Comment by LouisB3** [comment]
Confirmed - I tried performing maintenance on a fuel processor and I ended up with negative EnrichedUranium.

**Comment by sh1pman** [comment]
Also, the MkIII Fabricator module has the same issue.

**Comment by taleteller** [comment]
This is a real game breaker, since its not fixable tweaking cfg's. For me it not only kills the uranium on the reprocessor but its machinery as well. The uranium in my PDU goes zero, the urianium on a also attached .625 reactor stays.  

Would be nice someone could hotfix this for the 1.0.5 branch

**Comment by sh1pman** [comment]
Has this been fixed in 1.1 release?

2016-04-25 11:35 GMT+03:00 taleteller <notifications@github.com>:

> This is a real game breaker, since its not fixable tweaking cfg's. For me
> it not only kills the uranium on the reprocessor but its machinery as well.
> The uranium in my PDU goes zero, the urianium on a also attached .625
> reactor stays.
>
> Would be nice someone could hotfix this for the 1.0.5 branch
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BobPalmer/MKS/issues/801#issuecomment-214207366>
>



-- 

*С уважением,Сергеев А.В.*

**Comment by BobPalmer** [comment]
Yes, this is sorted in the next release.  Unfortunately there will not be a 1.0.5 back-patch.

**Comment by taleteller** [comment]
Even without the nuclear processor visiting the inflatable workshop deletes the uranium from the PDU. Is there a CFG way of preventing the automatic maintenance? Or at least a way to renaming the action from "performing maintenance" to "performing sabotage"?

**Comment by sh1pman** [comment]
Try not putting an engineer into the inflatable workshop. Like, ever.

On Monday, 25 April 2016, taleteller <notifications@github.com> wrote:

> Even without the nuclear processor visiting the inflatable workshop
> deletes the uranium from the PDU. Is there a CFG way of preventing the
> automatic maintenance? Or at least a way to renaming the action from
> "performing maintenance" to "performing sabotage"?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BobPalmer/MKS/issues/801#issuecomment-214359217>
>


-- 

*С уважением,Сергеев А.В.*
