### ISSUE TITLE
Local Logistics - On/Off Switch

### ISSUE THREAD

**Issue by TheGroovyMule** [BobPalmer/MKS#805]
This is more so concerning the logistics with crafts within loading ranges of each other. As it currently stands, it seems that all crafts with USI parts will share resources across short distances. I was hoping we could get the option to turn that off entirely as it seems to try to balance supplies across all ships. This leads to my base drawing supplies from my lander, which still requires them for it's trip home. It will continue to draw supplies even as the craft takes off. An option to turn off local logistics would be greatly appreciated as I'm finding it difficult to manually control the flow of resources.

**Comment by BobPalmer** [comment]
This is now in place
