### ISSUE TITLE
Tac - H2O Logistics Issue

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#807]
Had a base with low H2O and logistics with ILM for water.

Kerbal would go on EVA, full on all TAC things, food, water, O2.

One tick of logistics timer later and suddenly he went from 0.24 water to 0.02 water and was 'running out'. 

So need to some how figure out how to not steal water from my eva'ing kerbals?

**Comment by BobPalmer** [comment]
This should be sorted with the newer opt-in mechanics
