### ISSUE TITLE
Efficiency part suggestions

### ISSUE THREAD

**Issue by sh1pman** [BobPalmer/MKS#808]
There are currently no efficiency parts for the Nuclear Plant and the Akademy. Maybe PDU and Mk-V Comm-Lab, respectively? The Comm-Lab had been an efficiency part for the fuel refinery before it was deprecated, if I remember correct. So it would have a nice synergy with the Akademy, in my opinion.

**Comment by jd284** [comment]
Personally I would prefer if something other than the Comm-Lab would be chosen as efficiency part, because having multiple science labs on one vessel causes various bugs.

**Comment by sh1pman** [comment]
Maybe Pioneer then? It used to have a science lab before, so it would kinda fit that role.

**Comment by BobPalmer** [comment]
No idea what an efficiency part for the akademy would do.  Nukes I am leaving as-is for now, since even one processor can quickly generate a lot of fuel (at a much faster rate than you could use it).
