### ISSUE TITLE
Planetary Logistics not capturing overflow from background ship once it's focused again

### ISSUE THREAD

**Issue by henrybauer** [BobPalmer/MKS#811]
Reproduction:

1. Build ship with lots of inflated ILM storage (at least 2 days)
2. Start mining, switch to another vessel out of physics range
3. Warp ahead 30 days
4. Focus mining ship again
5. Local storage is filled up, but anything produced beyond that is lost.
6. A few seconds later, half of local storage is sent to Planetary Warehouse

Background: http://forum.kerbalspaceprogram.com/index.php?/topic/72032-105-usi-kolonization-systems-mksoks-0331-planetary-logistics-and-kolony-rewards/&do=findComment&comment=2422341

Here's my testing (using Water): http://imgur.com/a/lJhZa

Pic 1: Water is drilling at 0.374631/sec, or about 32k per day.  I have 210k of (inflated!) ILM storage.

I start the drill, then switch to a sat in orbit and warp ahead 30 days, which should net me about 960k.

Pic 2: When I switch back to the miner, I can see it adding Water in chunks (presumably 6 hour's worth of production at a time).  The resource meter fills up after a few chunks and then is full (210k).  The Planetary Warehouse doesn't change (still empty).

Pic 3: A few seconds later, the "tick" happens and half my water goes into the Planetary Warehouse, leaving me with 99k in the warehouse and 105k in my local storage (total of 210k minus the transfer tax).

However the 750k overflow (960k - 210k) was lost.

Here's my wild guess at what's happening:

Ship loads, ModulePlanetaryLogistics() runs, but sees nothing to do yet, since warehouse is empty and local storage is empty.  *Then* the converters kick in, and fill up local storage in 6-hour chunks.  ModulePlanetaryLogistics() does nothing because it already ran once, and now it's waiting for the next 12 second "tick".  Local storage fills up completely.  On the next "tick", then it finally balances with the planetary warehouse - but the overflow is already lost at that point.

It seems like eliminating the 12-second tick and just running every FixedUpdate would get it to operate as intended (capturing overflow), but presumably the 12-second tick is in there for a reason - either performance or gameplay.  Maybe a hybrid - run on every FixedUpdate for the first few seconds after a ship loads (to capture the "catch-up"), then revert to running every 12 seconds?

**Comment by BobPalmer** [comment]
This should be sorted in the next update (1.1 pre-release version).
