### ISSUE TITLE
Fertiliser production requires no Hydrates

### ISSUE THREAD

**Issue by eucarya** [BobPalmer/MKS#813]
Fertiliser production takes no Hydrates - only Gypsum.

![uksbug1](https://cloud.githubusercontent.com/assets/17260269/13205024/8939094e-d8d5-11e5-99f4-580100d68a45.png)

Sample craft to reproduce: https://www.dropbox.com/s/teavklb2ilpns7f/UKSbug1.craft?dl=0

USI Kolonization Systems v0.33.8.0
USI Life Support v0.3.12.0

This may be as designed -- though I believe that the intention was to have Gypsum + Hydrates = Fertiliser.

**Comment by eucarya** [comment]
Possibly related -- Hydrates weigh nothing.  (pic has both Hydrates and Gypsum bins full):

![possiblyrelated-hydrates-weigh-nothing](https://cloud.githubusercontent.com/assets/17260269/13205331/e107c82e-d8dd-11e5-8569-3ecdf8fa9bd4.png)

**Comment by jd284** [comment]
Why do you think Fertilizer should require Hydrates? It's not supposed to. Gypsum is basically fertilizer already (and has been [used as such](https://en.wikipedia.org/wiki/Gypsum#Uses)) and just needs a bit refining.

**Comment by eucarya** [comment]
Ahhh -- apologies -- I'd assumed that fertiliser would take at least two ingredients ( gypsum is used as a composite of fertiliser -- but irl includes lots of other ingredients like phosphates, etc.) -- I'd assumed as they were introduced at the same time and go into the same inflatables that they were related.  (also, gypsum is actually a hydrate rock!)

**Comment by BobPalmer** [comment]
Closing as not an issue
