### ISSUE TITLE
Nuke Fuel Processor

### ISSUE THREAD

**Issue by OakTree42** [BobPalmer/MKS#815]
The Mk3 Nuke Fuel Processor seems stuck at low levels of productivity/efficiency even while the rest of my base enjoys on average 300 to 500% efficiency. I have 14 kerbals in a base that has room for 68. I have enough work spaces as far as I can tell. I have tried putting scientists and engineers inside and it is clear it should be a scientist but still... can't get it above (last check) 33.8%. So curious if I am missing something or if there is an issue with the part.

For the record the base does have the PDU /and/ a MK-V power thingy (although that part has no more plutonium and I can't add more).

**Comment by sh1pman** [comment]
Does it have 2000 machinery?

**Comment by jd284** [comment]
The NFP has no efficiency parts, that's why its efficiency is low. Then again, even the low efficiency should be sufficient to cover the EnrichedUranium needs of even the largest bases. So this is probably intended.

**Comment by OakTree42** [comment]
I admit it is producing enough to give me a net gain even while running a 8000 ec reactor. ;) So I guess it's fine. Just the numbers caught me off guard and I wondered if I was doing something wrong.

**Comment by BobPalmer** [comment]
You should still be able to get to your 100% even without efficiency parts.

**Comment by BobPalmer** [comment]
Just did this on the launchpad (well,, 99%) with just a workshop and a hab plus the nuke fuel processor.  Closing.
