### ISSUE TITLE
Hidden ReplacementParts is visible and editable when building ships at EPL

### ISSUE THREAD

**Issue by bennord** [BobPalmer/MKS#819]
If you build a ship using an EPL launchpad, you are able to transfer ReplacementParts resources between your main vessel and the new vessel.

I believe this resource value is intended to be hidden,and should start at 100% for the new vessel without removing any ReplacementParts from the main vessel.

**Comment by jd284** [comment]
ReplacementParts come with USI-LS so this issue should probably be moved there instead.
Maybe the resource can be set to be treated like the ablator/solidfuel.

**Comment by BobPalmer** [comment]
Fixed in next patch
