### ISSUE TITLE
EL_resource recipes not set up correctly (ablator, solid fuel)

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#822]
EL_USI.cfg uses an MM patch to delete all EL resource recipes, but adds new recipes as regular nodes (not a patch).
So these are added first by stock, then the MM patch will delete them again so that no recipes will be active, and as a result it's currently impossible to construct heat shields with ablator or boosters with solid fuel.
The recipes should either all be changed by an MM patch, or the new ones added by MM as well to make this work.

**Comment by BobPalmer** [comment]
Closing as this has been merged
