### ISSUE TITLE
The Mod doesn't work for me.

### ISSUE THREAD

**Issue by ZombieslayerOne** [BobPalmer/MKS#824]
Hello, I saw this mod up on github and thought it looked very interesting so i downloaded the first .zip (for 0.33.8). I extracted all files from the .zip folder into my KSP game data folder. When I launched the game the only items I had from the mod were three drills in a Kolonization folder. Please tell me if I did something wrong on the installation, because I am pretty new to mods and am not 100% certain I did it right.

**Comment by BobPalmer** [comment]
Very likely.  Best avenue for support is the official thread on the forums.

**Comment by ZombieslayerOne** [comment]
Thank you I checked it and I hadn't installed avc and once I did it said
that my download was out of date, I downloaded the newest version and now
it runs perfectly. Thanks for the help and kerbal on bro.
