### ISSUE TITLE
Gilly dirt mining glitch

### ISSUE THREAD

**Issue by sh1pman** [BobPalmer/MKS#828]
While on Gilly, I can't really mine any dirt, because it's being continuously jettisoned evey millisecond or so. Obviously, the miner vessel is landed and has adequate dirt storage availible.

**Comment by jd284** [comment]
The dirt jettison, if it's really needed at all, could probably be limited to cases where the periapsis is positive.

**Comment by BobPalmer** [comment]
Fixed, good suggestion
