### ISSUE TITLE
USI Reactor Tooltip Incomplete

### ISSUE THREAD

**Issue by JustaSimpleUser** [BobPalmer/MKS#829]
KSP v1.0.5, MKS v0.33.9, CTT v2.3

The 0.625m and 1.25m nuclear reactor tooltip descriptions in the tech tree (Nuclear Power node, w/CTT) do not list the EC output only Core Heat, Depleted Fuel and Enriched Uranium.
  
![reactor tooltip](https://cloud.githubusercontent.com/assets/13194658/13725054/07413da4-e84c-11e5-8c11-a0e0bf5d706d.png)

**Comment by BobPalmer** [comment]
Looks to be working in next patch
