### ISSUE TITLE
1.25m Kontainer not operating as a distribution warehouse

### ISSUE THREAD

**Issue by kuroikage10** [BobPalmer/MKS#832]
From how I understand warehouse logistics: All kontainers should act as a warehouse auto leveling between other warehouses (if this is not intended for 1.25m kontainers, please disregard this issue).  As of now, 1.25m kontainers do not do this.  An edit of the config file adding module name ModuleDistributedWarehouse fixed this. 

Thank you for your time in putting this entire mod together.

**Comment by BobPalmer** [comment]
This is incorrect.  Only 3.75 and 5m kontainers have this feature for balance reasons, the system is working as designed.  Use resource logistics or scavenging for smaller bases.
