### ISSUE TITLE
Habitation ring has crew capacity 0 instead of 10

### ISSUE THREAD

**Issue by napseis** [BobPalmer/MKS#833]
hello,
The OKS habitation ring has no crew support in the stats (so it doesn't count in contracts requesting at least x kerbals.)
However once inflated it can hold 10 kerbals. Is this intended or did i miss something ?
CrewCapacity = 0 in OKS_HabRing.cfg , is the 1 missing ?

Thanks

**Comment by jd284** [comment]
Like the other inflatables, it's intended to have no capacity while deflated. There's just no room for them.

**Comment by BobPalmer** [comment]
Yup, by design.

**Comment by napseis** [comment]
ok, I understand. It's a shame though that the game cannot distinguish between inflated/deflated for the station contracts. 
Thanks !

**Comment by jd284** [comment]
Works for me with contracts after inflating it. If you're talking about "have X crew capacity" contracts, anyway. They count the inflated capacity once you inflate it.

**Comment by napseis** [comment]
oh really, good to know, thanks you !
