### ISSUE TITLE
Possible AES Pod issue

### ISSUE THREAD

**Issue by eXric** [BobPalmer/MKS#836]
Love this AES pod by the way, but looks like it might have an issue, and do not know where to post it.

The AES pod in KSP 1.1 64 bit windows does not render the inside of the pod when in hanger.  On runway the in side of the pod falls out.  It look like the chair and inside walls from what would be seen from the inside.  looking at wall from the outside it looks  transparent. IVA shows no walls just instrument panel and switches.  other then that it works.

Hope that helps

**Comment by BobPalmer** [comment]
Fixed in next release
