### ISSUE TITLE
[1.1] Lack of habitation loops between "refuses to work" and "returned to duty"

### ISSUE THREAD

**Issue by OzoneGrif** [BobPalmer/MKS#849]
I had a lack of habitation on my ship, but the life support and home was fine.

USI starts to loop infinitely between "X refuses to work" and instantly "X returned to duty" for all the affected Kerbals. This spams the screen, creates GUI problems, and the Kerbals still continue working.

The is USI Life Support + USI Kolonization.

**Comment by Xrave** [comment]
same problem for me. Happens when I'm using an logistics rover with a NOMs module that barely underproduces the amount that kerbals need to live.

**Comment by BobPalmer** [comment]
Can either of you please attach a save file?
