### ISSUE TITLE
Resource Distributor function of the surface Pioneer module does not work for its own vessel

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#850]
(Still using KSP 1.0.5 and UKS 0.33.9)
I have a main base with a Pioneer module (crewed with a 3-star pilot) and a Fabricator, as well as a drilling rig 460 m away in a different biome that provides ExoticMinerals.

Since the pioneer module has ModuleResourceDistributor, I understood from the wiki that it should provide resource transfer within 2000 m. However, this doesn't work when the receiver (the Fab) is on the same vessel. But as soon as I detach the pioneer module (using KIS) and make it a separate vessel, the resource transfer from drilling station to fab starts working and the fab starts producing SpecializedParts as expected. However I would prefer to avoid this workaround since I run into other issues if the pioneer is a separate vessel.

I believe this may be a remnant of the code when ModuleResourceDistributor was limited to rovers, and the rover would not require resources of its own. However with the pioneer module, it would be a lot better if the resource transfer to its own vessel was allowed as well.

**Comment by BobPalmer** [comment]
Corrected in next release
