### ISSUE TITLE
Disassembling connected docking port leave the other permanently 'docked'

### ISSUE THREAD

**Issue by Wulfg4r** [BobPalmer/MKS#851]
As title say, if you try to disassemble with an engineer in EVA one of a pair of docking ports (docked between them), the one that remains is locked in a 'docked' state: it cannot dock again, and the GUI button 'Undock' won't work.
Behavior noted with Docking Port Sr. .

Tested on:
KSP 1.1.0.1203 on Windows 7 x64
latest USI mods
HyperEdit
Ship Manifest

**Comment by bendavieshe3** [comment]
Just because I happened to do something similar last night I would note that this not happening with me on KSP 1.1.2 using latest USI mods and normal Docking Port.
