### ISSUE TITLE
Bugs found while investigating some errors in the output log.

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/MKS#863]
After investigating some errors (just errors, not exceptions), thrown off by some of the parts, I've found some bugs. While the Orbital Dock and orbital greenhouse don't seem to have anything in particular wrong with them (other than no light toggle for greenhouse), the orbital versions of the surface modules seem to be missing some textures because they look rather washed out.

The extendotube also throws some NREs when I tried to deploy (button disappeared) and when I try to arm the part. 

![screenshot7](https://cloud.githubusercontent.com/assets/11197436/14764367/04eed798-096a-11e6-84ad-5607f454ef6f.png)
![screenshot8](https://cloud.githubusercontent.com/assets/11197436/14764368/07939bfa-096a-11e6-816c-1b35ce7e46d4.png)
![screenshot9](https://cloud.githubusercontent.com/assets/11197436/14764369/095a0fc8-096a-11e6-83f5-3722129c9ff5.png)

**Comment by BobPalmer** [comment]
These modules will eventually be deprecated, so things will be sorted then.
