### ISSUE TITLE
Nuclear Fuel Reprocessor is wildly overpriced.

### ISSUE THREAD

**Issue by Businfu** [BobPalmer/MKS#866]
We can't have a part be worth 18 million kerbal bucks.... especially when it's mass is 2.5 tons.  It just makes me want to sit at KSC and use EL to manufacture centrifuges to sell back to shady international organizations. The IAEA would be all over that and John Kerry would swoop in and ban all centrifuge manufacture and nuclear reprocessing!

But in all seriousness... the price should be in line with the other MKIII modules. 18 million funds is insane and probably a typo?

**Comment by EnDSchultz** [comment]
Indeed, probably a typo. The regular Fuel Processor is 1,825,040. The Nuclear Fuel Processor is 18,525,040. I suspect that extra 5 after the 8 isn't supposed to be there and the Nuke Processor is supposed to be the same price as the regular Fuel Processor. I don't think you'd be out of line just editing the config to put it in line with the price of the regular Fuel Processor.
