### ISSUE TITLE
KIS Inventory is lost when boarding MK-V Inflatable Habitation Module

### ISSUE THREAD

**Issue by WazWaz** [BobPalmer/MKS#873]
Reproduces reliably - board with something in Inventory and it is gone forever. If Equipped it floats inaccessibly outside the hatch.

Transferring also seems to have problems. Inflatable Workshop has same problem.

**Comment by taleteller** [comment]
I can confirm this issue as well.

**Comment by BobPalmer** [comment]
This is a KIS issue, check there please.  If they have any suggestions for a fix, let me know :)

**Comment by WazWaz** [comment]
Yes, I see: https://github.com/KospY/KIS/issues/98

**Comment by WazWaz** [comment]
Currently, the USIAnimation code handles the case of the Transfer Crew dialog being needed to be added with CrewCacity changes:

```
                    if (CrewCapacity > 0 & !part.Modules.Contains("TransferDialogSpawner"))
                        part.AddModule("TransferDialogSpawner");
```

There is no way for KIS to change the number of KISInventoryModule modules on the part, since there is no event generated when the CrewCapacity changes. This looks like it will need co-operation between the modules to get it to work. USIAnimation could send some sort of CrewCapacityChanged(old,new) event to which KIS can respond (and any other mod that deals with crew capacities).

**Comment by BobPalmer** [comment]
Closing as there's not much I can do at this point - will need to be a KIS thing.
