### ISSUE TITLE
No power to logistic rear or center wheels

### ISSUE THREAD

**Issue by KronicOffender** [BobPalmer/MKS#878]
I first noticed this when trying to make a logistic rover for my heavily modded save. I then made a pristine stock KSP save and added only the exploration pack and the mks mod. Upon making the logistic rover in the new save, I noticed the same issue. I did some testing and apparently the wheel is slightly clipping into the body, preventing it from dropping on spawn. 

![20160512135428_1](https://cloud.githubusercontent.com/assets/7598073/15225292/d6dd4eac-184b-11e6-9765-14341617cb63.jpg)

![20160512135626_1](https://cloud.githubusercontent.com/assets/7598073/15225323/f70a8cd0-184b-11e6-9a5e-ed4053441534.jpg)

As you can see the wheels won't drop even if the vehicle is suspended. So I decided to add the No-Rockomax micronode to the body, then added the wheel to the micronode. Worked great as the following picture shows:

![20160512140107_1](https://cloud.githubusercontent.com/assets/7598073/15225408/53889baa-184c-11e6-9408-544d4d66853c.jpg)

Lastly, added micro-nodes to all wheels:

![20160512140511_1](https://cloud.githubusercontent.com/assets/7598073/15225451/8131e0a2-184c-11e6-98f6-f52eade79172.jpg)

The texture for the wheel did not load initially and I used info from another post to rename the wheel to "roverwheel1.dds" and it loaded correctly. The IVA appears to be looking down. 

![20160512142508_1](https://cloud.githubusercontent.com/assets/7598073/15225673/63800f1a-184d-11e6-9715-0e64d241fc3d.jpg)

**Comment by BobPalmer** [comment]
This part is going to be deprecated because of the sheer number of alternative rovers and logistics providers I have out there.
