### ISSUE TITLE
Microwave Transceiver missing 'LogisticsConsumer'

### ISSUE THREAD

**Issue by sirreality** [BobPalmer/MKS#884]
as stated, now can't pull power for it's vessel's needs

**Comment by micahculpepper** [comment]
I believe I am having the same issue. My mining rig on Minmus is not getting power. 
* The mining rig was assembled with KIS, and consists of a probe core, a Microwave Power Transceiver, a radiator, drills, storage, and structural parts.
* The base is 450m away, and includes a PDU staffed by an engineer.

I used KIS to bolt a Microwave Power Transceiver onto the PDU for good measure, but that did not change anything.

**Comment by BobPalmer** [comment]
This is fixed in the next release - specifically, anything with ModuleCommand is now a consumer.
