### ISSUE TITLE
Nuclear Waste container launches full, cannot be emptied

### ISSUE THREAD

**Issue by Tsaven** [BobPalmer/MKS#885]
Nuclear Waste container starts off on the launch pad as full of DepletedUranium, and there seems to be no way in the VAB to set it to Empty.  Additionally, there's no way to empty or jettison the contents (like how you can jettison the contents of Ore tanks).

**Comment by BobPalmer** [comment]
They now start as empty.  Intent is that players have to de-orbit or otherwise destroy their toxic waste, as the tanks are non-reuseable.
