### ISSUE TITLE
(Fixed) USI and TACLS Can't Launch Game

### ISSUE THREAD

**Issue by Micro753** [BobPalmer/MKS#887]
Not sure which mod is causing the problems, so I will post this at the TACLS thread as well.

I was using version "0.40.2 - 2016.04.30" of USI Kolonization Systems and version "v0.11.3 for KSP 1.1.2" of TacLifeSupport (https://github.com/KSP-RO/TacLifeSupport/releases). I told MiniAVC to not check for updates. No problems.

Today, I updated the mods to version "0.40.3 - 2016.05.14" of USI Kolonization Systems and version "TACLS v0.12.1 - Mind the Corners" of TacLifeSupport. I told MiniAVC to not check for updates. On the loading screen, the text in the loading bar stops at "UmbraSpaceIndusties/UKS/Parts/MKV_AgModule/MKV_AgModule". The game did not freeze; the witty phrases above the loading bar continued to change every now and then.

Other mods were present, so I tried a clean installation of KSP without any other mods on to see if I could reproduce it. The same thing happens each time; I have recreated the results 10 times now.

Logs: (Had to change the KSP.log and MiniAVC.log files to txt files to post them)

[output_log.txt](https://github.com/BobPalmer/MKS/files/276086/output_log.txt)
[KSP.log.txt](https://github.com/BobPalmer/MKS/files/276088/KSP.log.txt)
[MiniAVC.log.txt](https://github.com/BobPalmer/MKS/files/276092/MiniAVC.log.txt)

Switched back to the old versions, and it all works again.

**Comment by Micro753** [comment]
In case it is needed: 64 bit KSP on Windows10

**Comment by BobPalmer** [comment]
Check for updates with kspavc.  A dll was updated.

**Comment by Micro753** [comment]
A clean install with only USI and TACLS. AVC asked to let TACLS check for updates, but no popups for USI. I clicked yes, but the game did the same thing as before. I tried several times. Is there a .cfg file that I have to change to have AVC downoald the updated dll?


In case you need this:

[MiniAVC.log (2).txt](https://github.com/BobPalmer/MKS/files/276105/MiniAVC.log.2.txt)
