### ISSUE TITLE
Adjust OKS Hub Prices down from 24,000 funds. 

### ISSUE THREAD

**Issue by bendavieshe3** [BobPalmer/MKS#889]
Large and 6-Way OKS seem prohibitively expensive. 

The current prices for OKS hubs are: 

OKS Hub: 4,000
OKS Large Hub: 24,000
OKS 6-Way Hub: 24,000

The stock station hub is 900 funds. 

I can't see any obvious reason why OKS hubs are more expensive, so I wonder if these prices were accidental, temporary, or otherwise not intended as final. I suggest they are revised downwards (dramatically). 

If I had to suggest new pricing I would go for 1,200 / 2,000 / 2,500. Not too fussy but sub-10,000 on the large hubs would be nice. 

Happy to raise a PR with whatever different pricing was wanted for these parts.

**Comment by BobPalmer** [comment]
Fixed in next release
