### ISSUE TITLE
UKS kerbitrail docking port doesn't work with vanilla port

### ISSUE THREAD

**Issue by Cuerdas** [BobPalmer/MKS#890]
I'm having a strange problem: UKS kerbitrail docking port doesn't work with vanilla ports in my orbital station.
On my first trip I dock two addons to my station but in the next trip all the docking ports are buggy.

What can I do?

**Comment by Codebreakerblue** [comment]
My solution to this was to use the kerbtrails on all of my ships that need to dock, with a docking hub with vanilla ports.

**Comment by BobPalmer** [comment]
By design - they are not necessarily interchangeable.
