### ISSUE TITLE
drills dont add metal ore // loading bug without forum fix

### ISSUE THREAD

**Issue by EinPunkt222** [BobPalmer/MKS#891]
/\

**Comment by totalmayhem96** [comment]
Loading becomes stuck while trying to load ag modules

**Comment by kjnicoletti** [comment]
@EinPunkt222 This is a completely unusable bug report. If you can't be bothered to describe the bug so someone else can understand it, why should anyone be bothered to figure out what you intended to report? Pro tip - putting a carrot in the description field is never a good idea

@totalmayhem96 This is an already resolved issue - you need to update Kolonization core. Install KSP-AVC and it will point you in the right direction.
