### ISSUE TITLE
MK-V Regolith Sifter Is bugged

### ISSUE THREAD

**Issue by GeorgeLautenschlager** [BobPalmer/MKS#892]
The sifter will not process dirt until another part (like the MK-V inflatable workshop) has it's converter activated. When activated, the sifter reads 0% efficiency until the workshop has either of it's converters activated. It appears that as soon as the converter in the workshop computes it's efficiency, the sifter begins consuming dirt and electric charge and producing a raw materials, but that's speculation.

Additionally, the sifter only produces 1 resource. It was tested on the following celestial bodies:
- Kerbin, where it produces only water
- Mun, where it produces only ore
- Duna, where it produces only ore
- Laythe, where it produces only water
- Dres, where it produces only ore

Please note, it was only tested in one location on each of these bodies, with the exception of the Mun, where it was tested at two locations which yielded ore in both.

The craft file for the test vehicle is provided below.

[Dirt Miner Test.txt](https://github.com/BobPalmer/MKS/files/288010/Dirt.Miner.Test.txt)

**Comment by BobPalmer** [comment]
This has been sorted in the next release.
