### ISSUE TITLE
MK-V Logistical Rover Disappears

### ISSUE THREAD

**Issue by rtlagler** [BobPalmer/MKS#894]
I've been learning a bit about your tools for base building and have found that the MK-V Logistical Rover on Minmus in the midst of my base disappeared.  I stuck a second rover at the base and found that it disappeared eventually as well.  Both times the rover had a Pilot, both times the Pilot has disappeared alongside the rover (I've also confirmed that the used-to-be-Pilots are no longer showing up in the Kerbonaught Complex on any of the pages).

The rover appeared to be set with plenty of supplies and electricity from a PDU less than 200m away.  The base itself has just about all of the MKS-LS items within a few hundred meters.  If I find additional info I'll provide updates.

I've gone through the save file and can find no trace of the rover or its driver, but I am able to find the Debris left from ploping each of them onto the surface of Minmus.

<edit>Apologies, left out info...  I'm on 1.1.2 using what I believe is the most updated version of the mods.</edit>

**Comment by BobPalmer** [comment]
Going to table this as that part is being deprecated - could be aggressive debris culling, though it should not have culled that vessel.
