### ISSUE TITLE
Hab timer not reducing after habitat turned off

### ISSUE THREAD

**Issue by GHRyanK** [BobPalmer/MKS#928]
Hab and Home time go up as expected when habitat is turned on, but Hab time does not return to reduced amount after habitat is turned off.  Hab time remains as maximum even when hab is not consuming power.  Tried this with Orca and 2.75m Expandable Habitat, using orbit set cheat, attached to Mk1-2 Cmd Pod.  Tried expandable hab in both undeployed and deployed-at-launch states.

**Comment by musiccontrolsus** [comment]
As an addition to this I'm also finding that the Orbital Habs (both ring and normal) are able to be turned on and affect habitation times without being expanded.
