### ISSUE TITLE
Tundra nuclear fuel processor has incorrect description

### ISSUE THREAD

**Issue by stub42** [BobPalmer/MKS#945]
The description for the Tundra nuclear fuel reprocessor has a description about being used as a training akademy. Sounds fun, but probably not a great idea.

**Comment by DavidRWilliamsJr** [comment]
Proposed text included in my part-tag pull request.  

description = Processing plant for nuclear fuel production and refinement.  The centrifuge processes Uraninite using machines spinning really fast and produces EnrichedUranium.  DepletedFuel can also be reprocessed with USI Breeder technology, coaxing out every bit of EnrichedUranium left in the fuel. Sutible for interplanetary operations, spacecraft, stations, and surface bases (radiators not included.) Centrifuge not suitable for Kerbal entertainment purposes.
