### ISSUE TITLE
Ranger Parts too heavy to manipulate via KIS

### ISSUE THREAD

**Issue by Goldenpsp** [BobPalmer/MKS#953]
The Ranger Ag module, hab module and workshop have a mass too heavy (>1 ton) for a kerbal to manipulate solo.

**Comment by LeLeon** [comment]
so bring more!

**Comment by Goldenpsp** [comment]
That's ok to a point.  But there seems a wide discrepancy for inflatable parts that seem fairly close in size.  Given the idea according to Roverdude is they are a shell that uses materialkits to inflate (the kits building out the functional bits inside), I would expect them to be closer.  
Ranger Ag module -  1.251 tons
Ranger Hab module - 4.9 tons
Ranger ISM - .75 tons
Ranger Workshop - 1.832 tons

**Comment by LeLeon** [comment]
5 is much, i agree

**Comment by BobPalmer** [comment]
Fixed
