### ISSUE TITLE
Ratio of Mulch/Fertilizer is different on Duna module

### ISSUE THREAD

**Issue by andreszlima** [BobPalmer/MKS#960]
The ratio of Mulch/Fertilizer on Agriculture modules are the following:

MKS 'Ranger' Agricultural Module = 10/1
**MKS 'Duna' Agriculture Module = 9,28/1**
MKS 'Tundra' Agriculture Module (2,5m) = 10/1
MKS 'Tundra' Agriculture Module (3,75m) = 10/1

Is this intended?

**Comment by BobPalmer** [comment]
Fixed
