### ISSUE TITLE
Planetary Logistics not working with Scavenging very well

### ISSUE THREAD

**Issue by andreszlima** [BobPalmer/MKS#966]
After putting some resources (with HyperEdit) I wasn't able to get all resources I needed back even with Pioneer - Logistics module. I got correctly only 2 of the 4 resources on the Storage Module even with lots of resources of all of them in Planetary Logistics. (Image 1)
After that I wasn't able to send resources to my "rover" that had storage for those materials even with the two vessels under 100m from each other. (Image 2)

Note that I took out all other mods to this final test, the only mods remaining are USI ones (USI core, Konstruction, Karibou, Malemute and Survival Pack) and MM.

![20161020193608_1](https://cloud.githubusercontent.com/assets/19154589/19580507/6e39ac72-9705-11e6-8511-98624e4d76a0.jpg)

It also didn't put the only two that were working at 50% capacity.
![20161020193715_1](https://cloud.githubusercontent.com/assets/19154589/19580508/6e6982bc-9705-11e6-99f2-3a95fde7e6f5.jpg)

[Persistent file on dropbox](https://www.dropbox.com/s/i0rats3f452lbmb/persistent.sfs?dl=0)
[output_log.txt](https://github.com/BobPalmer/MKS/files/543102/output_log.txt)

**Comment by BobPalmer** [comment]
Unable to repro.  Please try again after next release
