### ISSUE TITLE
Please update ToolbarWrapper.cs

### ISSUE THREAD

**Issue by MaceWe** [BobPalmer/MKS#970]

**Comment by jarosm** [comment]
Some code that was added to Contract Configurator has exposed a bug in the toolbar reflection wrapper.
[http://forum.kerbalspaceprogram.com/index.php?/topic/55420-120-toolbar-1713-common-api-for-draggableresizable-buttons-toolbar/&page=55#comment-2770188](url)

**Comment by BobPalmer** [comment]
Will do so with a PR...

**Comment by BobPalmer** [comment]
Actually I think someone already did this one, closing for now, let me know if it persists.
