### ISSUE TITLE
2.75m Expandable Habitat not activating

### ISSUE THREAD

**Issue by GHRyanK** [BobPalmer/MKS#975]
2.75m Expandable Habitat does not show increased hab time when activated.  Habitat state will switch from "inactive" to "operational", but power is not consumed when activated.  Tested with standard config of Mk1-2 Cmd Pod, 3 crew, 2.5m in-line recycler (nice part BTW), and 16,000EC of extra batteries.  2.75m Exp Hab VAB calculated time for 3 crew is 205 days in retracted state (don't know why any bonus applies in this state), 220 days in deployed state (matching VAB math).  While in space, hab time shows 22 days (same as Greenhouse config hab time) regardless of hab activation state.  Tried this again in space while set to Greenhouse config and hab days did not change, nor power consumed, when greenhouse was activated.  With hab starting in retracted state, hab time is 7 days; applying machinery kits to deploy also results in hab time of 22 days (in Hab config).  EDIT: Dropped comment about Prev, Next Bay buttons not working; not required when only two configs for X-->Y button to cycle.

Verified pre-expanded 4.25m Expandable Hab, Habitat Ring, 2.5m Kerbitat , 3.75m Kerbitat (all set to Habitat configurations), plus Hitchhiker properly show hab time as calculated in VAB once activated in orbit (386km, via Alt-F12 orbit cheat).

**Comment by BobPalmer** [comment]
Fixed in next release
