### ISSUE TITLE
Game Crashing Bug with Duna Ag Module

### ISSUE THREAD

**Issue by tarheel1999** [BobPalmer/MKS#978]
While trying to test Crabman's efficiency numbers I discovered a game crashing bug with both the Duna and Tundra Agriculture Modules. Log files attached. I tested in a clean install with just MKS and with just MKS and USI-LS.   Steps to reproduce.
1.   Go to SPH, select the Duna Ag Module and rotate so it's facing up.
2.   Launch and select Start Agroponics from the PAW
3.   Wait 5 seconds and select Stop Agroponics.
4.   Wait 5 seconds and select Start Agroponics.
5.  Your should be shot out of Kerbol's SOI and the console and log file will be spammed with:

Look Rotation viewing vector is zero, and
[ERR 19:12:09.526] Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Duna.Agriculture/model/UmbraSpaceIndustries/MKS/Assets/DunaGeneric(Clone)/GenericModule/Pin/TopShaft/BottomShaft/Foot"

If you revert the flight to the SPH, the console is spammed with Look Rotation viewing vector is zero.

FYI, the same result can be reached by simply spamming the Stop/Start Agroponics button.

[2016-10-26_190834.zip](https://github.com/BobPalmer/MKS/files/554624/2016-10-26_190834.zip)

BTW, MKS is not happy when USI-LS is not installed.  The swappable converters on several of the modules (Kerbitat, Pioneer,etc.) do not gracefully handle the absence of USI-LS and show messages similar to "C1:???" and through RESOURCE errors in the log files.

**Comment by scorpion451** [comment]
Probably related to this issue: https://github.com/BobPalmer/MKS/issues/973
I set up that refinery that does the same thing in the SPH this way- turned it so that it was facing right way up and mounted it on a cradle. The weird part is that I did the same thing with a regolith sifter and it hasn't given me any trouble.

**Comment by Mongrelf** [comment]
Related to the Tundra Ag Module issue.  I changed a converter to convert hydrates to H2O.  Clicking on the start converter exhibited the same behavior referenced above.  NaN error,  thrown out into space followed by gui corruption etc.  Repeatable.

**Comment by BobPalmer** [comment]
Please test this again in the next release as I cannot repro it currently.
