### ISSUE TITLE
MKS Tundra 2.5M Hub (Short) has misplaced or broken attachment nodes

### ISSUE THREAD

**Issue by kaa253** [BobPalmer/MKS#980]
MKS Tundra 2.5M Hub (Short) top and bottom nodes leave big gaps in the vessel structure

![screenshot4](https://cloud.githubusercontent.com/assets/6190454/19801126/97222b9c-9d49-11e6-9b98-25d148e0ec10.png)

**Comment by GHRyanK** [comment]
The full length and short hubs also appear to have contradictory masses - the standard is 0.05t, but the shorter one is 0.5t.  On a related note, both Tundra airlocks have the same mass, despite one being noticeably bigger than the other.

**Comment by BobPalmer** [comment]
Fixed
