### ISSUE TITLE
Recycler gets inactive on Duna Pioneer if Machinery goes down even a little

### ISSUE THREAD

**Issue by andreszlima** [BobPalmer/MKS#981]
Description: Recycler at Duna Pioneer (maybe on Tundra Pioneer too) gets inactive after consuming even a little amount of Machinery. In comparison to agriculture modules, that its production goes down over time, I think this is a bug.

Steps to replicate:
1. Put a Duna Pioneer with a Supplies storage with some Supplies in it.
2. Launch
3. Activate recycler at Kerbitat and see that Supplies consumption goes down to 3,2/day.
4. Time wrap at maximum speed to consume some machinery.
5. In some hours, recycler gets inactive (by the data shown in "Life Support Status", but still says it's operational.

What I expected: Don't consume machinery like Kerbitats OR consume machinery but recycling percent don't go immediately to zero at 99% machinery.

**Comment by BobPalmer** [comment]
Fixed
