### ISSUE TITLE
Recycler in Duna Pioneer deactivates on timewarp

### ISSUE THREAD

**Issue by Pherec** [BobPalmer/MKS#993]
I noticed that activating a high time warp causes the recycler in Duna Pioneer to turn off. The amount of time warp needed for this deactivation seems to vary. 

For comparison, the recyclers of USL Life Support seem to work just fine, even on high time warp. 

Below is a screenshot of what I'm experiencing:

![recycler](https://cloud.githubusercontent.com/assets/23300979/20042859/cacb1078-a481-11e6-90dd-7d9d89ff5609.jpg)

Noticed that ticket #981 states that the Dune Pioneer recycler will stop working whenever machinery drops down even a little. I encountered the same, and in these tests I had enabled the machinery flow to be prioritized to be taken from another container instead of from the Pioneer Module.

**Comment by BobPalmer** [comment]
This is fixed in the next release
