### ISSUE TITLE
Logistics center shares resources without requiring a pilot

### ISSUE THREAD

**Issue by andreszlima** [BobPalmer/MKS#994]
Description: Logistics Center shares resources without requiring a pilot.

Steps to replicate:

1. Add any unmanned command pod at VAB/SPH as first/root part
2. Add a Duna logistics center under the command pod and make sure there is no Kerbal inside it
3. Add an inflatable storage module with any resource
4. Add a drill to mine that resource or just use HyperEdit to increase its amount after launch
5. Fill storage module
6. Resources are sent to planetary logistics

What should happen: Resources should not be sent to Planetary Logistics, because there is no Pilot nearby
What happened: Resources were sent to Planetary Logistics even without any Kerbal/Pilot nearby.

**Comment by BobPalmer** [comment]
Fixed in next release
