### ISSUE TITLE
Drills' extraction rate aren't affected by separators

### ISSUE THREAD

**Issue by andreszlima** [BobPalmer/MKS#995]
If you have one industrial strip miner with only dirt as separator, its resource rate is the same of another one with just one separator to dirt and others to another resource.

![20161106215623_1](https://cloud.githubusercontent.com/assets/19154589/20043642/7dc7cd16-a477-11e6-85c9-204a8bcb1edf.jpg)

**Comment by BobPalmer** [comment]
Fixed in next update
