### ISSUE TITLE
Agriculture modules aren't affected by profession skills

### ISSUE THREAD

**Issue by andreszlima** [BobPalmer/MKS#996]
Agriculture modules aren't affected by scientists, even at level 5.
Here I have an unmanned Cultivate (S) production working at 100% load:

![20161106222401_1](https://cloud.githubusercontent.com/assets/19154589/20043704/422282b4-a478-11e6-9ee9-b4759ac92cff.jpg)

Here I have a manned Cultuvate (S) production with a scientist working at 100% load:

![20161106222316_1](https://cloud.githubusercontent.com/assets/19154589/20043709/56de4bca-a478-11e6-95ec-b090f42716fe.jpg)

What I expected was that Scientists should give bonus % to production, because at its .cfg it is written:

> UseSpecialistBonus = true
> SpecialistEfficiencyFactor = 0.2
> SpecialistBonusBase = 0.05
> ExperienceEffect = ScienceSkill
> Efficiency = 1

**Comment by BobPalmer** [comment]
Fixed in next update
